### ISSUE TITLE
Why use query instead of watchQuery?

### ISSUE THREAD

**Issue by stubailo** [Akryum/vue-apollo#1]
The only difference between query and watchQuery is that watchQuery updates when the client-side cache is updated by a mutation or another query. In `react-apollo`, for example, _all_ queries use `watchQuery`.

What would be the use case for a "non-reactive" query? I feel like it shouldn't be the default. But up to you, of course.

**Comment by Akryum** [comment]
Good suggestion. Maybe reorganize the documentation to make it clearer?

**Comment by Akryum** [comment]
The API is now a bit simpler:

```javascript
// Apollo-specific options
apollo: {
  // 'tags' data property on vue instance
  tags: {
    query: gql`query tagList {
      tags {
        id,
        label
      }
    }`,
    pollInterval: 300, // ms
  },
},
```

**Comment by Akryum** [comment]
Fixed in [v1.0.0-beta.6](https://github.com/Akryum/vue-apollo/releases/tag/v1.0.0-beta.6)

**Comment by stubailo** [comment]
> Maybe reorganize the documentation to make it clearer?

You mean the core js docs?

**Comment by stubailo** [comment]
BTW, please feel free to reach out if you have any questions or need help!
