### ISSUE TITLE
Prefetch + Afterwares

### ISSUE THREAD

**Issue by jamilabreu** [Akryum/vue-apollo#100]
I need to include afterware to have apollo play nice with my Absinthe backend:

https://github.com/absinthe-graphql/absinthe_plug/issues/89

I'm including this code, which works without prefetch: true

```
const absintheAfterware = {
    applyBatchAfterware(res, next) {
      res.responses.forEach((resp) => {
        resp.data = resp.payload.data;
      });
      next();
    },
  };
```

but throws `Network error: Cannot read property 'data' of undefined` when prefetch is enabled. I've narrowed it down to this line:

```await app.apolloProvider.prefetchAll({ route }, components)```

in 

```  if (isServer) {
    beforeNuxtRender(async ({ components, nuxtState }) => {
      await app.apolloProvider.prefetchAll({ route }, components)
      nuxtState.apollo = app.apolloProvider.getStates()
    })

**Comment by Akryum** [comment]
This seems to be unrelated to vue-apollo code.

**Comment by jamilabreu** [comment]
You're right, my apologies! Seems to be related to the await call (when removing await, it works), not sure why though 😞

**Comment by jamilabreu** [comment]
For anyone else that might find this, I found that using a lowercase 'c' for the components variable fixed it :man_facepalming: 

```  if (isServer) {
    beforeNuxtRender(async ({ components, nuxtState }) => {
      await app.apolloProvider.prefetchAll({ route }, components)
      nuxtState.apollo = app.apolloProvider.getStates()
    })
