### ISSUE TITLE
Prefetch: Remove "variables" field when no variables present

### ISSUE THREAD

**Issue by jamilabreu** [Akryum/vue-apollo#101]
Setting `prefetch: true` on a query with no variables sends a request with the following field

`"variables" => true`

Might it be better to either remove that field, or send an empty json object by default instead?

Using `prefetch() { return {} }` in my implementation at the moment.

cc: @benwilson512 for input on the absinthe-graphql side.

**Comment by benwilson512** [comment]
Yeah just to weigh in, this is the only instance where I've seen the `"variables"` param come in as something other than a json object or a string.
