### ISSUE TITLE
this.$apollo.queries is empty inside nested component

### ISSUE THREAD

**Issue by dohomi** [Akryum/vue-apollo#103]
@Akryum I use `nuxt` and on page level I do a `SmartQuery` like you described inside the documentation: 
```javascript
apollo:{
  Page:{
    query: myPageQueryGql
  }
}
```
Inside of a nested component I would like to refetch the `Page` query and tried to call 
```
this.$apollo.queries.Page //=> inside nested queries is null/[]
```
Is there an option to make the queries available in all components or is this restricted in purpose?

**Comment by Akryum** [comment]
You may use an event emitted to the parent component (recommended), or `this.$parent.$apollo...` (not recommended).

**Comment by dohomi** [comment]
@Akryum thanks for clarifying it, I use $emit at the moment
