### ISSUE TITLE
Mutation and Caching

### ISSUE THREAD

**Issue by ferllings** [Akryum/vue-apollo#107]
Hello,

I'm missing about the mutations:

I have a view and update pages for an element. 
When the element has been updated, the element view page still shows the old data.
Probably because the view page doesn't trigger a new data fetch, and use the cache instead.
Unless I use `fetchPolicy: 'cache-and-network'`

What is the correct way to update the cache after a mutation?

Thanks for your help.

**Comment by Akryum** [comment]
You need to update the cache with the new data using the `update` option. [Doc](http://dev.apollodata.com/core/read-and-write.html) [Doc](http://dev.apollodata.com/react/cache-updates.html) [Example](https://github.com/Akryum/vue-apollo#mutations)
If all the objects have an id and the `__typename`, they should be automatically updated (since the cache is a normalized store with object keyed with their type and id) if you don't add or remove items.

**Comment by ferllings** [comment]
Thanks,

I've added
`const client = new ApolloClient({
  dataIdFromObject: o => o.id
});`

Because all my ids are unique. But it doesn't seems to be enough.
So I'll give a try with the 'update' function.

**Comment by ferllings** [comment]
I've managed to use the "update" function, but the produced result is not what I expected.
Here is my workflow:
- I have a list of books, pulled with a "query books..."
- I click on "Edit book A"...
- ...which leads me on an individual form to update this book, populated with "query book(id)"
- I change the book name to X and save with "mutation book(id, name)"
- I use the "update" function to update the "query book(id)"
- The view is redirected to the full list
- The list of books still displays "A"
- If I return to the edit page, the book name is "X"

I understand the result because I only updated the cache for the individual "query book(id)" and not for "query books".

What am I missing? Do I need to update both single and list queries, on each update mutation?
Or is there a better workflow that I'm not seeing?
Maybe using the subscription pattern?

**Comment by Ramzeus** [comment]
I have the same problem. I can see in the Apollo Client Developer Tools that the cache is updated with the correct values after the mutation, but the user interface is still has the old values that are no longer in the cache.
Do I still need to provide an update function in order for Vue to re-read the cache?

**Comment by Samuell1** [comment]
@ferllings you need update all queries not only `query book(id)`, `query books()`

**Comment by ferllings** [comment]
Thanks @Samuell1,
I think I'll disable the caching for now, because it seems very difficult to update all queries related to books (and not mentioning queries with books as sub relation). And do it each time I update/add/delete a book.

It probably works for single page apps, but not for more complex application.

**Comment by Samuell1** [comment]
@ferllings you can use fetchPolicy `cache-and-network` to fetch new data and update automatically after opening page but there will be more requests on api
