### ISSUE TITLE
add `skip` option to queries

### ISSUE THREAD

**Issue by sircharleswatson** [Akryum/vue-apollo#11]
Hi!

First of all, thank you for this project! It's helped me make an amazingly smooth transition to Vue from React.

My question is: Is there a skip method we can use to skip queries like shown here:
http://dev.apollodata.com/react/queries.html#graphql-skip

It would be great if we could skip based on a provided function. Here's what I'm thinking:

```
export default {
  ...
  apollo: {
    user: {
      query: FETCH_CURRENT_USER,
      skip() {
        return !isAuthenticated
      },
      ...
    }
  }
}
```

If the skip uses a reactive data source in it's return, then it would automatically trigger the query if that component is already mounted.

Is this something that would be of interest to add to `vue-apollo`? Can you think of any other ways this can easily be achieved?

I look forward to hearing from you.

**Comment by Akryum** [comment]
This is a very good idea. I'm thinking of something like this:


```
export default {
  ...
  apollo: {
    user: {
      query: FETCH_CURRENT_USER,
      enabled() {
        return !this.isAuthenticated
      },
      ...
    }
  },
  methods: {
  	disableUserQuery() {
      this.$apollo.queries.user.enabled = false
    },
  },
}
```

**Comment by sircharleswatson** [comment]
Would you mind explaining that a bit? It seems a little cumbersome. I'm not sure about the `disableUserQuery` part. And I think `skip()` would be better than `enabled()` since that is the preferred term in the apollo docs.

**Comment by Akryum** [comment]
Or maybe:

```
export default {
  ...
  apollo: {
    user: {
      query: FETCH_CURRENT_USER,
      skip() {
        return !this.isAuthenticated
      },
      ...
    }
  },
  methods: {
    disableUserQuery() {
      this.$apollo.queries.user.skip= true
    },
  },
}
```

The last part is about controlling the apollo query programmatically if needed.

**Comment by sircharleswatson** [comment]
I like that! :D I think it makes sense that way and will be a great feature :D

**Comment by Akryum** [comment]
Implemented in [release 1.2.0](https://github.com/Akryum/vue-apollo/releases/tag/1.2.0).

**Comment by sircharleswatson** [comment]
@Akryum Woot! I'll try this out and let you know how it goes. Can't wait! :)

**Comment by gustawdaniel** [comment]
In release note there is no comments about it

> https://github.com/Akryum/vue-apollo/releases/tag/1.2.0

There is issue

> https://github.com/Akryum/vue-apollo/issues/395

In documentation

> https://vue-apollo.netlify.com/guide/apollo/special-options.html#skip-all

only `skipAll` is presented.

I spend some time to find proper usage example and I can't so there is

```
        apollo: {
            me: {
                skip: !isUerLoggedIn(),
                query: gql`query {
                  me { id name rating numberOfGrades }
                }`
            }
        },
```

**Comment by Rick-McClatchie** [comment]
Hey everyone,

is the skip option also available in the apollo-composable Composition API for Vue 3? It does not seem to be implemented yet. https://v4.apollo.vuejs.org/api/use-query.html#parameters

Thanks.

**Comment by julia-suarez-deel** [comment]
Hello @Rick-McClatchie I need this option too but I can't find it, I guess it's missing, should we open a new feature request? it's reaaaally useful

**Comment by julia-suarez-deel** [comment]
I found a way to do it with the `enabled` option 
![image](https://user-images.githubusercontent.com/26018221/106967501-a848fc00-671d-11eb-8026-cf6cb9fe4531.png)

**Comment by r3plica** [comment]
That's not working for me.
I tried this:

```
export function useSearch(params) {
  const { result, loading, error, fetchMore } = useQuery(search, params, {
    enabled: computed(() => !!params.value?.searchTerm),
  });
  const response = useResult(result, null, (data) => data.search);
  return { response, loading, error, fetchMore };
}
```
And I get an error stating: Type 'ComputedRef<boolean>' is not assignable to type 'boolean'

**Comment by noque-lind** [comment]
Has anyone found a way to integrate the skip option into their Vue js Apollo app? We need this feature badly for async validation. Kinda crazy that there is no way to skip first query without using enabled options (which automatically calls query when changed to true).

**Comment by strickczq** [comment]
https://github.com/vuejs/apollo/blob/757e45cac05e860c0a0cc6d1c513545df4009c72/packages/vue-apollo-composable/src/useQuery.ts#L58

https://github.com/vuejs/apollo/blob/757e45cac05e860c0a0cc6d1c513545df4009c72/packages/vue-apollo-composable/src/useQuery.ts#L152

Since the third argument `options` of `useQuery` can receive a `Ref` or a `ReactiveFunction`, there is no need to make the option `enabled` can too.

Instead of making `enabled` reactive, we can just make the whole `options` reactive.

Example:

```typescript
const variables = ref(something);

useQuery(
  document,
  variables,
  () => ({ enabled: !!variables.value }), // make `options` reactive
);
```

**Comment by Akryum** [comment]
Example in the docs [here](https://v4.apollo.vuejs.org/guide-composable/query.html#disable-a-query)
