### ISSUE TITLE
vue-apollo with Nuxt getting constantly errors if the root_query is changing

### ISSUE THREAD

**Issue by dohomi** [Akryum/vue-apollo#110]
Hello,
I receive constant error message like following:
```
            throw new Error("Can't find field ROOT_QUERY on object (" + objId + ") " + JSON.stringify(obj, null, 2) + ".");
```

This happens if I navigate between pages with different query names. The apollo readStoreResolver function tries to update the caches and looks up old query inside of the new query:
```
oldQuery page1:
allPages{
  ...allPages
}

newQuery page2: ==> ERROR: can't find ROOT_QUERY on object "allPages"
allTravels{
  ...allTravels
}
```
Is there anything more I would need to set up?

**Comment by Akryum** [comment]
Do you still have this issue with the newer versions?

**Comment by dohomi** [comment]
Oh this is a really old one, will close it for now because I think thats not an issue any longer
