### ISSUE TITLE
Update apollo cache after mutation

### ISSUE THREAD

**Issue by wsielski** [Akryum/vue-apollo#111]
I'm trying to update apollo's cache after mutating the list retrieved in another gql query. Unfortunately for some reason I'm receiving this error: 

```
Error: Can't find field versionDataPage({"brandId":1,"page":1,"limit":10}) on object (ROOT_QUERY) {
```

My query is attached to component as following:

```javascript
apollo: {
            versionDataPage: () => ({
                query: versionDataPage,
                variables() {
                    return {
                        page: 1,
                        limit: pageSize,
                        brandId: this.selectedBrand.id
                    };
                },
                skip() {
                    return this.selectedBrand == null;
                },
                result({data: { versionDataPage : { versionsData : [newest] } } }) {
                    if (!this.selectedVersion) {
                        this.$store.commit(SET_CURRENT_VERSION_DATA, newest);
                    }
                }
            })
        },
```

and mutation query is something like this:

```javascript
apollo.apollo.mutate({
                mutation,
                variables: {
                    versionDataId
                },
                update(store, data) {
                    store.readQuery({ query: versionDataPage, variables: { brandId: 1, page: 1, limit: 10  } });
                }
});
```

Gql queries is shared between files nad contains this:

```javascript
export const versionDataPage = gql`query versionDataPage($brandId: Int!, $page: Int, $limit: Int) {
    versionDataPage(brandId: $brandId, page: $page, limit: $limit) {
        versionsData {
            id
            json
            is_published
            created_at
            updated_at
        }
        hasMore
    }
}`;

export const publishVersionData = gql`mutation ($versionDataId: Int!) {
    publishVersionData(versionDataId: $versionDataId) {
        id
        json
        is_published
        created_at
        updated_at
    }
}`;
```

When obviously ROOT_QUERY contains the key like that:

![image](https://user-images.githubusercontent.com/1705688/30114265-97a845f0-9317-11e7-882a-7e68750f572f.png)

**Comment by Akryum** [comment]
I just made [an example app](https://github.com/Akryum/vue-apollo-todos) with a lot of mutations.

**Comment by ojczeo** [comment]
@wsielski I think there is a problem with variables naming passed to `readQuery`, have the same, check it out, should have the same format/naming as original server query.

**Comment by ojczeo** [comment]
@wsielski also remember if you want to add new item to Apollo collection (array) use the structure from existing objects in collection - the best solution is to use GraphQL fragments. The same structure also must be maintained in `OptimisticReponse` object if you to make updating storage working properly.

**Comment by onurkose** [comment]
**To whom arrives this page to find out a solution for this awkward problem.**
You may also have noticed that your query is just there and you can read in the error dump (red lines above ghost's message)

If you check the error message title:

> Error: Can't find field versionDataPage({"brandId":1,"page":1,"limit":10}) on object (ROOT_QUERY) {...

All the parameters are integer formatted. But at the bottom of the error dump you'll read: 

`"versionDataPage({\"brandId\":\"1\",\"page\":1,\"limit\":10})": {`

What you see here is a little bit stupid. Somehow brandId parameter's value is cached as string!

If you try to query this with integer brandId, it'll throw that error.

To fix:

```
const query = { query: VERSION_DATA_PAGE_QUERY, variables: { brandId: "1", page: 1, limit: 10} }
const data = store.readQuery(query)
```

you should investigate what's cached how and turn your integers to strings with toString() function.
