### ISSUE TITLE
Accessing vue-apollo store from other components

### ISSUE THREAD

**Issue by mbajur** [Akryum/vue-apollo#114]
Hello!

I have a pretty basic setup, let's say there is a `ComponentA` and a child `ComponentAB`. `ComponentA` fetches some data (let's say - a products list) from the backend using vue-apollo.

I need to access the fetched products in child component `ProductAB`, it goes down to accessing vue-apollo internal store (which is present in apollo chrome inspector, i can see the products in there). However, i don't know how to do that the "official way". Only options that comes to my mind are passing products list to child using props (that's not an option, my model is a highly simplified version of my real app which is way more nested and complex) or directly using redux lib to access existing redux store - but that smells bad to me, i would rather first ask - is there any "official" way of accessing vue-apollo store from components?

Thanks in advance!

**Comment by Akryum** [comment]
Just use the same query in you ComponentAB. If the data is already in the store, apollo will return it instead of making a request to the server.

**Comment by mbajur** [comment]
Woah, that's amazing. Thank you!
