### ISSUE TITLE
Can not use mutations outside composition function with provideApolloClient

### ISSUE THREAD

**Issue by Zippersk** [Akryum/vue-apollo#1145]
**Describe the bug**
With the current implementation of v4, we can not use `useMutation` function outside Vue3 composition function.

In `UseQuery` [source code](https://github.com/vuejs/vue-apollo/blob/v4/packages/vue-apollo-composable/src/useQuery.ts#L165) we have this condition:
```js
vm && trackQuery(loading)
```

In `UseMutation` [source code](https://github.com/vuejs/vue-apollo/blob/v4/packages/vue-apollo-composable/src/useMutation.ts#L47) a condition is missing.
```js
trackMutation(loading)
```

This cause error when we use mutations outside the composition function:
```
Uncaught (in promise) Error: getCurrentTracking must be used during a component setup
    at getCurrentTracking (loadingTracking.js?b1f0:25)
    at track (loadingTracking.js?b1f0:50)
    at trackMutation (loadingTracking.js?b1f0:71)
    at Module.useMutation (useMutation.js?89f9:57)
```

**Comment by revelaustris** [comment]
Facing the same issue here.

**Comment by anli-xsigns** [comment]
Same for me, changing
```
   trackMutation(loading);
```
to
```
    // Is on server?
    var vm = getCurrentInstance();
    var isServer = vm === null || vm === void 0 ? void 0 : vm.$isServer;
    vm && trackMutation(loading);
```
fixes the issue. Should I create a PR?

**Comment by Zippersk** [comment]
@anli-xsigns I already created PR 3 weeks ago (https://github.com/vuejs/vue-apollo/pull/1146). @Akryum can you look at it, please?

**Comment by reaink** [comment]
@Akryum can you look at it, please?

**Comment by badalya1** [comment]
> Same for me, changing
> 
> ```
>    trackMutation(loading);
> ```
> 
> to
> 
> ```
>     // Is on server?
>     var vm = getCurrentInstance();
>     var isServer = vm === null || vm === void 0 ? void 0 : vm.$isServer;
>     vm && trackMutation(loading);
> ```
> 
> fixes the issue. Should I create a PR?

Can't find `getCurrentInstance()`, did you mean `getCurrentTracking()`?

**Comment by jvmonjo** [comment]
> @anli-xsigns I already created PR 3 weeks ago (#1146). @Akryum can you look at it, please?

Hi @anli-xsigns. Since I really need this working ASAP, is there any way I can Install your modified version of vue-apollo?

**Comment by Zippersk** [comment]
@jvmonjo you can use this if you want https://github.com/Zippersk/vue-apollo/tree/v4

**Comment by TimWeidner** [comment]
I was able to work around this by moving my mutations to the setup function and returning them, but this is some pretty ugly code.

**Comment by hloehrmann** [comment]
Also would love to see this approved soon to use a mutation inside a route guard.

**Comment by TommyCoding** [comment]
Seems like subscriptions are affected too, I get the same error message when using useSubscription(...) outside of setup.

**Comment by Brymes** [comment]
> @jvmonjo you can use this if you want https://github.com/Zippersk/vue-apollo/tree/v4


I have no idea how to use this PR in my code. Also please when would this be merged and a new release made.. Or if at all anyone has a fork of this PR deployed on NPM.. I need it in my project as soon as i can..

All Help would be appreciated
