### ISSUE TITLE
Cannot update cache after a mutation by pushing to an array.

### ISSUE THREAD

**Issue by leggettc18** [Akryum/vue-apollo#1165]
**Describe the bug**
I have a project for managing bookmarks. I have a view component for viewing and managing bookmarks. For some background, this is a Vue3 Typescript project and I have used graphql-codegen with the vue-apollo-typescript plugin to generate some types and hooks like `GetBookmarksDocument` and `useNewBookmarkMutation()`. 

When I run the mutation to create a new bookmark, it completes successfully, but the page doesn't visually update until the query to get all of a users bookmarks re-runs (i.e. on page refresh). So I added an update step on the newBookmark mutation in order to update the cache and not require a page refresh. However, it results in the following error.

```
Uncaught (in promise) Error: Cannot add property 18, object is not extensible
```

The actual number changes depending on how many objects are already in the `bookmarks` array.

Through a bit of troubleshooting I've been able to narrow it down to this line of code:

``` typescript
data?.bookmarks?.push(submittedBookmark);
```

Full setup function for reference:

``` typescript
<script lang="ts">
import { defineComponent, Ref, ref } from "vue";
import { useState } from "@/store/store";
import { Bookmark, BookmarkCreate } from "@/models/bookmark";
import { useResult } from "@vue/apollo-composable";
import {
  GetBookmarksDocument,
  GetBookmarksQuery,
  useGetBookmarksQuery,
  useNewBookmarkMutation,
} from "../generated/graphql";

export default defineComponent({
  name: "Bookmarks",
  setup() {
    const state = useState();
    const token = state.getToken();
    const dialogVisible: Ref<boolean> = ref(false);
    if (!token) {
      return {};
    }
    const { result, loading, error } = useGetBookmarksQuery();
    const bookmarks = useResult(result);

    const newBookmark = ref({
      name: "",
      url: "",
      color: "",
    } as BookmarkCreate);

    const { mutate: submitNewBookmark } = useNewBookmarkMutation(() => ({
      variables: newBookmark.value,
      update: (cache, { data: submitBookmark }) => {
        const data = cache.readQuery<GetBookmarksQuery>({
          query: GetBookmarksDocument,
        });
        console.log(data);
        const submittedBookmark = {
          name: submitBookmark?.newBookmark.name,
          url: submitBookmark?.newBookmark.url,
          color: submitBookmark?.newBookmark.color,
        } as Bookmark;
        console.log(submittedBookmark);
        data?.bookmarks?.push(submittedBookmark);
        console.log(data);
        if (data) {
          cache.writeQuery<GetBookmarksQuery>({
            query: GetBookmarksDocument,
            data,
          });
          console.log(data);
        }
      },
    }));

    const handleSubmit = () => {
      submitNewBookmark();
      dialogVisible.value = false;
    };

    return {
      dialogVisible,
      bookmarks,
      loading,
      error,
      newBookmark,
      handleSubmit,
    };
  },
});
</script>
```

It appears that the `bookmarks` array on the `data` object is readonly or something. I'm not really sure how this is happening though.

**To Reproduce**
1. Create a mutation
2. Write an update function for it that updates the cache by pushing to an array.
3. Run the mutation.
4. See error in DevTools console.

**Expected behavior**
Array is updated with the new object pushed to it during the mutation.

**Versions**
vue: 3.0.7
vue-apollo: 3.0.0-alpha.3
apollo-client: 2.6.10

**Additional context**

**Comment by Akryum** [comment]
Since Apollo Client 3, cache state is immutable.

**Comment by leggettc18** [comment]
So is [this](https://v4.apollo.vuejs.org/guide-composable/mutation.html#making-all-other-cache-updates) outdated then? What's the proper way to update the cache then?

**Comment by leggettc18** [comment]
Nevermind, I got it figured out. rather than directly pushing the new bookmark to the array, I set the data property of parameter of `writeQuery` to a new object with a `bookmark` array constructed from the previous bookmarks array followed by the new one.

``` typescript
cache.writeQuery<GetBookmarksQuery>({
    query: GetBookmarksDocument,
    data: { bookmarks: [...data.bookmarks, submittedBookmark] },
});
```
