### ISSUE TITLE
Error not being triggered on failed WebSocket connection (apolloClient.subscribe)

### ISSUE THREAD

**Issue by nicolas-sentry** [Akryum/vue-apollo#1166]
When using a simple subscription 

```javascript
const observer = apolloClient.subscribe({query})
observer.subscribe({next: () => console.log('All good'), error: (e)=> console.error('All bad',e)})
```

The error is not triggered if there is an server connection error, e.g. 404. I'm working on an environment where WS may be not available, and if that fails use polling instead.

Using the default VueApollo implementation there's no access to the SubscriptionClient to add the `onDisconnected` callback

**Versions**
vue: 2.6.12
vue-apollo: 3.0.5
apollo-client: 2.6.10

**Steps to reproduce**
1. Use a bad endpoint in `wsEndpoint` like `wss://fakeway.google.com/subscription`
1. Add a query subscription
1. No error is triggered (Something that as dev I can use to tell the subscription failed)

**Comment by jpikora** [comment]
You can access subscriptionClient through WebSocketLink. In your apollo setup script you can export it and then import it somewhere else (e.g. vue components) for further usage.

```
const wsLink = new WebSocketLink({
  uri: "ws://domain/subscriptions",
  options: {
    reconnect: true
  }
})

...

export const subscriptionClient = wsLink.subscriptionClient
```

**Comment by nicolas-sentry** [comment]
Thanks @jpikora!

Although I don't use `WebSocketLink`, I'm using the plugin configuration by default, I now see you can extract it from the `createApolloClient` (In case it comes handy for someone)

```javascript
import { createApolloClient } from 'vue-cli-plugin-apollo/graphql-client';

const defaultOptions = {
  httpEndpoint,
  link: authMiddleware,
  persisting: true,
  ssr: false,
  tokenName: AUTH_TOKEN,
  websocketsOnly: false,
  wsEndpoint: GATEWAY_WS,
};

const apolloClientService = createApolloClient(defaultOptions);

// Extract and export apollo clients
export const { apolloClient, wsClient } = apolloClientService;
```
