### ISSUE TITLE
Apollo 2.0 support

### ISSUE THREAD

**Issue by Akryum** [Akryum/vue-apollo#117]
TODO

**Comment by jdus** [comment]
Has work on this already started? or is there a roadmap? I'm about to start a new project and would like to use Apollo Client 2 with Vuex integrated as store right away. I'm just starting with Apollo but I would try to contribute where I can.

Greetings,
Johannes

**Comment by dfee** [comment]
Similarly, I'm unable to use apollo-client v1 as it would require me to [re-write large swaths of the subscription code](https://github.com/apollographql/apollo-client/issues/2228#event-1286191101), that apparently I can rely on `apollo-link` for.

**Comment by shtse8** [comment]
this is my first day to start this project and facing version problem.

**Comment by Akryum** [comment]
Install `apollo-client@^1.0.0` to make it work with vue-apollo for now.

**Comment by shtse8** [comment]
@Akryum thanks. but any progress of 2.0 support? I am worrying if I use apollo-client 1 to start my project, I need to upgrade and migrate one 2.0 support is released.

**Comment by shtse8** [comment]
https://github.com/apollographql/subscriptions-transport-ws/issues/275
not only `apollo-client`, `subscriptions-transport-ws` seems upgrade to 0.9 and removed `addGraphQLSubscriptions`.

**Comment by rnenjoy** [comment]
Caaaant wait for 2.0 of this wonderful package!

**Comment by Akryum** [comment]
https://github.com/Akryum/vue-apollo/tree/next
