### ISSUE TITLE
Using @vue/apollo-option with Vue 3

### ISSUE THREAD

**Issue by entermix** [Akryum/vue-apollo#1175]
**Describe the bug**
I am confused. Please tell me if the `@vue/apollo-option` package is ready to work with Vue 3? 

From the docs:

> This library integrates apollo (opens new window) in your Vue (opens new window) components with declarative queries. Compatible with Vue 2.0+ and 3.0+.

The documentation [describes](https://v4.apollo.vuejs.org/guide-option/setup.html#_3-inject-the-apollo-provider) how to integrate with Vue 2. I tried to integrate with Vue 3, but nothing worked. There is already a similar topic [here](https://github.com/vuejs/vue-apollo/issues/972), but the question remains unanswered. 

Please note the question is about `@vue/apollo-option`, not `@vue/apollo-composable `

**To Reproduce**
https://codesandbox.io/s/priceless-thunder-3om5t

**Expected behavior**
Correct integration with Vue 3 (?) 

**Versions**
vue: 3.0.0
@apollo/client: ^3.3.13
@vue/apollo-option: 4.0.0-alpha.11

**Additional context**
https://v4.apollo.vuejs.org/migration/#installation
https://v4.apollo.vuejs.org/guide-option/setup.html

**Comment by anli-xsigns** [comment]
I think it is not ready (or even intended or necessary) to be used in vue 3. In the example the code is still Vue.use which is deprecated in Vue 3 -> https://v3.vuejs.org/guide/migration/global-api.html#a-note-for-plugin-authors

**Comment by mooori** [comment]
[Vue 3 support is work-in-progress in version 4 of Vue Apollo](https://apollo.vuejs.org/guide/#introduction)

**Comment by Akryum** [comment]
Now available with `@vue/apollo-options` and `@vue/apollo-components` v4.0.0-alpha.13
