### ISSUE TITLE
How install vue-apollo in Nuxt (without module)

### ISSUE THREAD

**Issue by innovaweb-dev** [Akryum/vue-apollo#1179]
**Is your feature request related to a problem? Please describe.**
I'll like to use Vue-apollo in Nuxt without any module.

**Describe alternatives you've considered**
I tried that, but Vue-apollo not work like on documentation.

```javascript
// nuxt.config.js
  plugins: [
    './plugins/apollo',
  ],
```
```javascript 
// ~/plugins/apollo.js
import VueApollo from 'vue-apollo'
import fetch from 'node-fetch'
import {ApolloClient} from 'apollo-client'
import {createHttpLink} from 'apollo-link-http'
import {InMemoryCache} from 'apollo-cache-inmemory'

const httpLink = createHttpLink({
  uri: 'http://localhost:5300/api',
  fetch: fetch,
})

const cache = new InMemoryCache()
const apolloClient = new ApolloClient({
  link: httpLink,
  cache,
})

const apolloProvider = new VueApollo({
  defaultClient: apolloClient,
})

export default ({app}, inject) => {
  inject('apollo', apolloProvider) // Cannot read property 'defaultClient' of undefined
  // OR
  inject('apollo', apolloClient) // ✔ WORKING
}

import Vue from 'vue'
Vue.use(VueApollo)
```

```javascript
// .vue
data() {
    return {
        customers: {},
    }
},
apollo: {
    customers: gql`query {
      customers {
      lastname
      }
    }`,
  },
async fetch() {
    console.log(await this.$apollo.query({ query: gql`query {customers {lastname}}` })) // ✔ WORKING
    console.log(await this.$apollo.queries.customers); // TypeError: Cannot read property 'customers' of undefined
},
```

**Comment by ospira** [comment]
@rifton007 did you figure this out?

I'm curious about this too.

Even just this:

```
import Vue from 'vue'
import VueApollo from 'vue-apollo'

Vue.use(VueApollo)
```

in a Nuxt (client-side) plugin leads to an error:

> DOMException: Failed to execute 'setAttribute' on 'Element': '$apolloData' is not a valid attribute name.

It seems in the community common to suggest that Nuxt and Apollo are best used together using a Nuxt module, but like @rifton007 I want to avoid this too. The reason being that the module in question - https://github.com/nuxt-community/apollo-module - seems to be no longer actively maintained. As I only want to run this using a client side plugin (not using ssr or ssg) I want to avoid dealing with an unmaintained dependency and just use `vue-apollo` directly.

I'd really appreciate any guidance on how to do this in Nuxt.
