### ISSUE TITLE
Loading does not reset to true when refetching or loading new data

### ISSUE THREAD

**Issue by rebz** [Akryum/vue-apollo#1188]
**Describe the bug**
The `loading` computed property returned from `useQuery` never shows `true` when using `refetch`.

**To Reproduce**
1. Clone `https://github.com/rebz/sandbox-gql-apollo-composition-store.git`
2. Run `npm i`
3. Visit the page
4. Click the Refetch button at the top of page, notice the loading indicator never shows `true`

**Expected behavior**
I expect on a refetch for the `loading` computed property to be set to `true` when waiting on the network response.

**Versions**
vue: `2.6.12`
vue-apollo: `4.0.0-alpha.12`
apollo-client: `2.31.1`

I've also tried this in another project with apollo client being `^3`

**Additional context**
Inside of `@/composables/character.js` you can uncomment the block of code under the custom refetch function that wipes out the local apollo cache data... originally I thought having the data in the cache is what kept the loading indicator from switching back to true. But it appears to make zero difference.

**Comment by EmilM32** [comment]
Any update on this? 

For now I use little work around with my own loading ref
```js
const myLoading = ref(false)
```

assign loading value from `useQuery` every time when it's updating

```js
watch(loading, value => {
  myLoading.value = value
})
```

and create my own refetch function to handle loading value
```js
const refetchWithReload = () => {
  myLoading.value = true
  refetch().then(() => {
    myLoading.value = false
  })
}
```

**Comment by Akryum** [comment]
Set the `notifyOnNetworkStatusChange` option to `true`
