### ISSUE TITLE
Dynamic Clients?

### ISSUE THREAD

**Issue by jasonbahl** [Akryum/vue-apollo#119]
I see that there's support for multiple Clients, which is fantastic! 

Is there a way to populate the secondary Clients dynamically? In my app, I have a central GraphQL server that has knowledge of other GraphQL servers. So I would like to do a fetch to that initial server to ask for the additional servers that the current user can access, and populate the secondary Clients with the response. Is that possible and if so, any tips on implementing?

**Comment by Akryum** [comment]
This is totally possible. Quick example:

```js
async function main () {
  const result = await fetch('http://...')
  const clientsConfig = await result.json()
  const clients = {}
  for (const config of clientsConfig.clients) {
    clients[config.name] = // create the client
  }
  const defaultClient = clients[clientsConfig.defaultClient]

  const apolloProvider = new VueApollo({
    defaultClient,
    clients,
  })

  // ...
}

main()
```
