### ISSUE TITLE
Is there a public repo for @vue/apollo-composable?

### ISSUE THREAD

**Issue by jdbdnz** [Akryum/vue-apollo#1191]
Pasting this here since the npm docs for @vue/apollo/composable point to github.com/Akryum/vue-apollo which redirects to github.com/vuejs/vue-apollo 

@Akryum is the code for @vue/apollo-composable published anywhere? The API is great and I'd like to keep using it, but based on the npm package looks like it may have fallen by the way side(?)

**Comment by frandiox** [comment]
@jdbdnz It's here: https://github.com/vuejs/vue-apollo/tree/v4/packages/vue-apollo-composable
