### ISSUE TITLE
V4 -> queries and mutations always throws an exception instead of only populating the error.

### ISSUE THREAD

**Issue by fenilli** [Akryum/vue-apollo#1195]
**Describe the bug**
When running the code, onError and error do have the exception and are only accessible when passing the result to an object before hand, and it always throws to the console an exception.

When running with errorPolicy: 'all', it does not get any errors nor throws an exception.
```javascript
const {
  mutate: createBusiness,
  result,
  loading,
  error,
  onError,
} = useMutation(create, () => ({
    variables: { input: { name: 'vue apollo', code: 'vap01' } },
}));
onError(err => console.log({ err }));

return { result, error, loading, createBusiness };

// Console
{err: Error: Validation failed for the field [businessGroup].
    at new ApolloError (webpack-internal://…}

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler (Promise/async): "Error: Validation failed for the field [businessGroup]."
```

**Expected behavior**
My error and onError should get the error object itself instead of a exception message, and it should not throw an exception or it should be possible to catch it to stop propagation to the console.

**Versions**
vue: 2.6.12
vue-apollo: 3.0.7
vue/apollo-composable: 4.0.0-alpha.12
apollo-client: 3.3.19

**Comment by Akryum** [comment]
There is a new `throws` option to handle this use case.
