### ISSUE TITLE
Optimistic Response - re-render twice?

### ISSUE THREAD

**Issue by sve-odoo** [Akryum/vue-apollo#1198]
**Describe the bug**

I'm working with big datasets.
When a mutation returns a result, it takes 1 or 2 seconds for my components to re-render. ( in addition to the request time )

I wanted to reduce the total time by using Optimistic responses.
Here is what happens:
1/ The mutation is requested
2/ Optimistic response updates the components ( UI lags for 2 seconds )
3/ Whenever the request comes back, the components are updated again, and the UI lags again.

Is that the expected behavior? If the actual response is exactly the same as the optimistic one, I would expect that no update has to be done anymore. Is there a way to disable:
- either the second update of the Apollo cache?
- either the second rerender of the view components?

Thanks!

**Versions**
vue: 2.6.12
vue-apollo: 3.0.5
apollo-client: 2.27.4

**Comment by Akryum** [comment]
AFASK it's expected behavior.
