### ISSUE TITLE
v4 -> onError should prevent exceptions being called.

### ISSUE THREAD

**Issue by fenilli** [Akryum/vue-apollo#1200]
**Is your feature request related to a problem? Please describe.**
If you have a mutation using useMutation and get the onError hook to "catch" the error, it still runs the exception, meaning that the error needs to be handled on both the mutate call using try catch/.catch, and the onError.

So using onError is pretty much useless, it would be better to create a function to call the mutate with try catch and do what you would do with the onError.

**Describe the solution you'd like**
Add an option to the onMutation options to not throw any exception on errors, meaning you would be using the onError to handle that.

**Describe alternatives you've considered**
Instead of using onError, adding a tryCatch with a wrapper function to call mutate.

**Comment by Akryum** [comment]
Fixed in https://github.com/vuejs/vue-apollo/commit/bfd8db4e4bee61d3909eb7143bc3427f0ffe19e2
