### ISSUE TITLE
v4 -> Headers doesnt get sent

### ISSUE THREAD

**Issue by CodingTomato** [Akryum/vue-apollo#1204]
**Describe the bug**
The authorization header doesnt get sent.

**To Reproduce**
1. Implement as shown below
2. Request a query

**Expected behavior**
The authorization header should be sent

**Versions**
vue :^3.0.0-0
vue-apollo: ^4.0.0-alpha.12
apollo-client: ^3.3.20

**Additional context**
I initialized Apollo like this. Every request I do I get the 401 error. If I test the query with Insomnia it works.

```
import { ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client/core';
import { DefaultApolloClient } from '@vue/apollo-composable';

const httpLink = createHttpLink({
  uri: 'https://example.com/api/graph',
  fetchOptions: {
    mode: 'no-cors',
  },
  headers: {
    authorization: 'Bearer ' + localStorage.getItem('token'),
  },
});

const cache = new InMemoryCache();

const apolloClient = new ApolloClient({
  link: httpLink,
  cache,
});

const app = createApp(App)
.provide(DefaultApolloClient, apolloClient)
.use(IonicVue)
.use(router); 
```

**Comment by kpguru20001** [comment]
I am facing this issue. Help me with the solution to this
