### ISSUE TITLE
useQuery doesn't work in Vue 3.1.2 with Apollo Composable

### ISSUE THREAD

**Issue by AydanGaite** [Akryum/vue-apollo#1209]
**Describe the bug**
Calling `useQuery` returns the error `Uncaught TypeError: Cannot read property 'replace' of undefined`

**To Reproduce**
The code I execute looks like this.
```js
useQuery(userQuery, { uid: firebaseUser.uid }, { fetchPolicy: 'no-cache' })
```

**Expected behavior**
I am expecting `useQuery` to send a request and return a request from a network. It seems to die before it makes a request.

**Versions**
vue: 3.1.2
vue-apollo: 4.0.0-alpha.12
apollo-client: 3.3.20

**Additional context**
I am running on a dev environment on electron, with firebase, apollo, and vue
The same code also executes fine on vue `3.0.11`

The stack trace leads back to vue
```
at injectHook (runtime-core.esm-bundler.js?5c40:2923)
    at eval (runtime-core.esm-bundler.js?5c40:2935)
    at useQueryImpl (useQuery.js?a2fd:54)
    at useQuery (useQuery.js?a2fd:22)
    at signInSuccess (app.ts?f35f:107)
    at eval (app.ts?f35f:170)
    at valueCallback (index.esm.js?e947:14654)
    at CallbackContext.onValue (index.esm.js?e947:12487)
    at eval (index.esm.js?e947:13331)
    at exceptionGuard (index.esm.js?e947:661)
```
and throws here, at line `2923` in `runtime-core.esm-bundler.js`:

```js
const apiName = toHandlerKey(ErrorTypeStrings[type].replace(/ hook$/, ''));
```

**Comment by joelmandell** [comment]
Just for troubleshooting. In my case this happens when running dev-mode. Does it work if you do a production/dist build? Or did I have random luckyness :=)

**Comment by beastrovich** [comment]
Just ran into this myself today. Seems to be missing 'sp' (LifecycleHooks.SERVER_PREFETCH) in ErrorTypeStrings record.
