### ISSUE TITLE
[Help](V4) useQuery return await promise

### ISSUE THREAD

**Issue by xxSkyy** [Akryum/vue-apollo#1219]
When I do 
```js
  const{ result } = await useQuery(getUser) 


  console.log(result.value)
  setTimeout(() => {
    console.log(result.value)
  }, 1000)
```
I need to get full result than waiting for it as first result.value is undefined and later on it changes.
Is it somehow possible?

in mixin 
```js
      const res = await this.$apollo
        .query({
          query: getUser,
        })
        .catch((err) => {
          console.error(err)
          return
        })


```
worked perfectly

now I'm whole user info fetching moving from mixin to composable file so there are no this.$apollo to use

**EDIT**

using 
```js
  const{  onResult} = await useQuery(getUser) 

  onResult((queryResult) => {
    console.log(queryResult.data)
    console.log(queryResult.loading)
    console.log(queryResult.networkStatus)
  })

```

it works as intended but its adding excessive code to async function, can it work in async/await way?

**Comment by Akryum** [comment]
Putting `await` in front of `useQuery` does nothing as it is a synchronous function. You can use `useApolloClient` to get the client instance and do a `client.query` directly.

**Comment by guillaumeduhan** [comment]
Thanks @Akryum for this.

What worked for me outside a component:

`import { useApolloClient } from '@vue/apollo-composable'

const { resolveClient } = useApolloClient()
const client = resolveClient()

await client.query...
await client.mutate...
`

**Comment by OctaneInteractive** [comment]
Hi @guillaumeduhan, any chance you could expand on that example?
