### ISSUE TITLE
query function is always evaluated when the component is created, even if skip function returns true

### ISSUE THREAD

**Issue by rDr4g0n** [Akryum/vue-apollo#122]
I have a query function that accesses a prop on my component that is not available in my component at mount (it is populated from an async request). I created a skip function that returns `true` when that prop is not yet set, expecting this to prevent the query function from being evaluated till it is ready.  

However, the query function is always evaluated at least once before the skip function is evaluated. It looks like the query callback is always called during construction, before the skip function is evaluated: https://github.com/Akryum/vue-apollo/blob/master/src/smart-apollo.js#L19  

In fact, simply setting `skip` to `true` is not sufficient to prevent query from being called at least once.

Ideally the query function would only be evaluated after `skip` has been verified to be set to (or evaluate to) `false`.

**Comment by Akryum** [comment]
Currently, skip only prevent the query from running. I agree it would be nice if it also don't run the other callbacks.

**Comment by andrewdalpino** [comment]
What is the preferred way to handle this situation if skip is not the way?

**Comment by RedShift1** [comment]
Just came across this myself, any fix?

**Comment by Waals** [comment]
I find myself repeating the same checks in my `skip()` function and in my `query()` function.
Any advice on where to start if you are open to pull requests ?

**Comment by lperiodbose** [comment]
Can someone clarify what `skip()` actually prevents from happening?
Is it just that future, reactivity-based querying won't happen?
I just spent a half-hour banging my head against this and wonder if there's a way to clarify in the documentation the intended purpose of the skip property...
