### ISSUE TITLE
Error in browser after use package @vue/apollo-composable

### ISSUE THREAD

**Issue by ariran5** [Akryum/vue-apollo#1224]
**Describe the bug**
used variable before initialization, useQuery not work

**To Reproduce**
I use Vitejs bundler
1. Install @vue/apollo-composable
2. use useQuery hook

**Expected behavior**

**Versions**
vue: 3.1.5
vue-apollo: 4.0.0-alpha.13
apollo-client: 3.3.21

**Additional context**

![image](https://user-images.githubusercontent.com/12746457/126045655-35e04be6-f149-424b-ab43-cd0946df69ed.png)

**Comment by ariran5** [comment]
https://codepen.io/Aria-n/pen/abWWPjJ?editors=1010

**Comment by ariran5** [comment]
![image](https://user-images.githubusercontent.com/12746457/126046545-c8717f0a-fd50-4c32-ae4a-4229468d1fe8.png)

**Comment by ariran5** [comment]
https://github.com/vuejs/vue-apollo/pull/1218

**Comment by maartenvn** [comment]
Can be closed, since this is fixed by #1218
