### ISSUE TITLE
When will Vue-Apollo 4 become stable?

### ISSUE THREAD

**Issue by ghost** [Akryum/vue-apollo#1228]
I'd like to use Vue-Apollo 4 with Vue 3 in production, but it states on your site that it's still work in progress.

When do you think it'll become stable?

Also, are there any other for how to make GraphQL work with Vue 3?

**Comment by godbrain** [comment]
Just so you know alpha 14 that just got released fixed some big issues, so I think this is moving ahead  :)

**Comment by ghost** [comment]
Personally I'm convinced, but since I'm working in an enterprise anything other than stable just won't cut it :) Therefore I'm really curious about when it's likely to officially become stable.

**Comment by Akryum** [comment]
When it's ready :cat:
