### ISSUE TITLE
clear error after refetch

### ISSUE THREAD

**Issue by ariran5** [Akryum/vue-apollo#1232]
**Describe the bug**
If I use useQuery with variable1. Server respond with error 404. Error object contains in error field.

After change variable1 to variable2 my component refetch query and error from first request contains in error field too

Its bug ?

**Comment by Akryum** [comment]
Fixed in https://github.com/vuejs/vue-apollo/commit/ea123fa414dc4a4e116dd6d3bc70656f50d831c6
