### ISSUE TITLE
@vue/apollo-composable@4.0.0-alpha.14 requires a peer of vue@^3.1.0

### ISSUE THREAD

**Issue by HansCronau** [Akryum/vue-apollo#1234]
**Description**
When installing `@vue/apollo-composable@4.0.0-alpha.14` alongside `vue@2.6.14`, the following warning will show:

```
npm WARN @vue/apollo-composable@4.0.0-alpha.14 requires a peer of vue@^3.1.0 but none is installed. You must install peer dependencies yourself.
```

**To Reproduce**
Create a Vue 2 project and install `@vue/apollo-composable`.

**Expected behavior**
Compatibility with Vue 2 is maintained and no Vue 3 dependencies are required.

**Versions**
- `vue@2.6.14`
- `@vue/apollo-composable@4.0.0-alpha.14`

**Comment by ChrisAgar** [comment]
Related Issue: #1251 @vue/apollo-option

**Comment by Lappihuan** [comment]
I'm pretty sure peerDependency of vue should be defined like this:
`"vue": "^2.6.14 || ^3.0.0"`
but currently it is defined like this:
`"vue": "^3.1.0"`
