### ISSUE TITLE
refetch didn't change loading's value

### ISSUE THREAD

**Issue by qxchen6** [Akryum/vue-apollo#1235]
**Describe the bug**
refetch function didn't change loading's value

**To Reproduce**
1. const { loading, refetch } = useQuery<T, T2>(query, options)
2. loading is true on first fetch, it's fine.
3. then call refetch function. the `loading` is still false

**Expected behavior**
When start refetch , `loading` should change to true ,and change to false at request done.

**Versions**
vue: 3
vue-apollo:     "@vue/apollo-composable": "^4.0.0-alpha.12"
@apollo/client:  "@apollo/client": "^3.3.19",

**Comment by enzostvs** [comment]
Hello @qxchen6 i dont know if you fixed your problem, but you need to add notifyOnNetworkStatusChange in your options query.
Like this: 
`const { result, refetch, loading } = useQuery(myQuery, { ...params }, { notifyOnNetworkStatusChange: true }  ) `

**Comment by laddi-netapp** [comment]
We're seeing the same issue in my project, and we've already set `notifyOnNetworkStatusChange` to `true`.  It's easy to debug by adding a `result` hook and logging out the value of the `loading` value passed in vs. the value of `$apollo.loading`, even `$apollo.queries.xxx.loading`, and see that the value isn't being updated for the `$apollo` object.

**Comment by jjstanton** [comment]
@laddi-netapp is this affecting all queries or just some? 

I'm having similar issues and I have also set `notifyOnNetworkStatusChange`  to `true`.

**Comment by laddi-netapp** [comment]
@jjstanton it's basically every query we try.

**Comment by ramonparisg** [comment]
This is still happening in version `4.0.0-alpha.17`. Does anyone has a workaround? I've tried setting `notifyOnNetworkStatusChange` to `true` as well. @laddi-netapp @jjstanton @sam585456525 @Akryum

**Comment by jjstanton** [comment]
@ramonparisg `notifyOnNetworkStatusChange` seems to be solving the problem for me. I don't think this was its intended use but has become the go to solution, as its mentioned [here ](https://apollo.vuejs.org/api/apollo-query.html#props:~:text=(you%20may%20need%20to%20set%20notifyOnNetworkStatusChange%20prop%20for%20it%20to%20change))in the documentation. 

We've created a global function that uses this prop, a bit easier than having to rewrite it repeatedly:
```
export const queryFilter = (gql: any, vars: any, fn: any) => {
    const { result, loading, error, refetch, variables, fetchMore } = useQuery(gql, vars, { notifyOnNetworkStatusChange: true });
    const data = fn ? useResult(result, [], fn) : useResult(result, []);
    return {
        data: data,
        loading: loading,
        error: error,
        refetch,
        variables,
        fetchMore
    };
};
```
