### ISSUE TITLE
The installation part of documentation is too confuse

### ISSUE THREAD

**Issue by JoaoHCopetti** [Akryum/vue-apollo#1238]
I'm just reading the documentation trying to setup a apollo app manually and it's really confuse.

First we go to this link https://v4.apollo.vuejs.org/guide/installation.html#manual-installation

where we end up with this code example:
```
import { ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client/core'

// HTTP connection to the API
const httpLink = createHttpLink({
  // You should use an absolute URL here
  uri: 'http://localhost:3020/graphql',
})

// Cache implementation
const cache = new InMemoryCache()

// Create the apollo client
const apolloClient = new ApolloClient({
  link: httpLink,
  cache,
})
```

After that on **Next steps** section we have the frist option "Option (Classic) API" that go to https://v4.apollo.vuejs.org/guide/installation.html#next-steps

It says "Make sure you have installed Apollo Client." clicking on "installed Apollo Client" redirect us to url i linked above, no problems until now.

But here we have a lot of confuse steps that override the first "Installation" page, which one do we need to use?

In this page we will end up with a code like this:

```
import { ApolloClient, InMemoryCache } from '@apollo/client/core'
import { createApolloProvider } from '@vue/apollo-option'
import { createApp, h } from 'vue'

const cache = new InMemoryCache()

const apolloClient = new ApolloClient({
  cache,
  uri: 'http://localhost:4042/graphql',
})

const apolloProvider = new createApolloProvider({
  defaultClient: apolloClient,
})

const app = createApp({
  render: () => h(App),
})

app.use(apolloProvider)
```

Now compare the first code i pasted above (first installation page) with the second one (second installation page) we got:

- Duplicate `cache` variable
- Duplicate imports
- Different configs to ApolloClient instance
- `createApp` is unavaliable on Vue 2

The solution to this is obvious, just make one page to setup a apollo config, just saying that because make me really confuse as someone that never used apollo before and would like to understand step by step how to setup without using vue-cli.

**Comment by Akryum** [comment]
I will probably include the apollo client setup part in each parts of the guide.
