### ISSUE TITLE
[question] How to update Vue component's data after a mutation?

### ISSUE THREAD

**Issue by 2Fwebd** [Akryum/vue-apollo#124]
Hello, 

Good job on this integration! 

Quick question I having hard time to solve.. Queries are working fine, mutations as well. However, I don't understand **how the data is dynamically returned to Vue's data after a mutation**. 

Let's say I have a list of Users, I'm able to fetch them trough a query and they are assigned to `users` attribute in my data object. I'm also able to add new users. Works in the database, but the `users` is not refreshed. Even though I'm getting the object, I can even store it in the "store". But it's never updated on the template side: 

                    update: (store, returned ) => {
                        const data = store.readQuery({
                            query: USERS_QUERY
                        });
                        data.users.push(returned.data.userCreateMutation);
                        store.writeQuery({ query: USERS_QUERY, data });
                    }

The first idea was to just push as I'd do with any other kind of API

                 .then((data) => {
                         this.users.push(data.userCreateMutation)
                 })

But apparently the `users` attribute or any attribute set in the `apollo` is protected and can't be changed like that. 

What am I missing to just push a new object in that Vue data attribute after a mutation?

Just an example but my question would also make sense for deleting and editing object. 

Thanks a lot.

**Comment by 2Fwebd** [comment]
Okay, so for those who could be interested in the answer: 

         this.users = this.updateStoreAfterCreate(store, userCreateMutation, USERS_QUERY, variables, 'users');

Here is what this method is doing: 

         updateStoreAfterCreate (store, payload, query, queryVariables, field) {
            // We get our current store for the given Query
            const data = store.readQuery({
                query: query,
                variables: queryVariables
            });
            //We add the new data
            data[field].push(payload);
            //We update the cache
            store.writeQuery({ query: query, data });
            return data[field];
        },
         
Not sure if there is another "best way" to do it though.

**Comment by Samuell1** [comment]
You doesnt need to set component data if you using smart query, data will be automatically refreshed

**Comment by dfee** [comment]
@2Fwebd make sure you are adding an `id` attribute to your GQL query. That's key to getting the update.

**Comment by 2Fwebd** [comment]
Thanks for the feedback here guys! Will test it out but for some reasons, even with an ID. We still need to assign it back. We'll use that a lot so will do more tests on this. As long as it works! :)

**Comment by jbbr** [comment]
This methods does work for updates and new objects - but how to delete objects from the store? The vue component does not get updates data after deleting objects from the store - it needs to be remounted...

**Comment by Samuell1** [comment]
@jbbr if you doesnt gets updated data in your component then you have something wrong
