### ISSUE TITLE
Release version 4 of @vue/apollo-composable standalone

### ISSUE THREAD

**Issue by cndev123** [Akryum/vue-apollo#1245]
**Is your feature request related to a problem? Please describe.**
A vue 3 compatible apollo client is urgently required by many developers who started with vue 3 in the expectation that the rest of the vue libraries would soon follow with releases compatible with vue 3.

**Describe the solution you'd like**
My understanding is that version 4 of @vue/apollo-composable is ready for usage with vue 3. My own tests support this conclusion. If this is the case, can this package be released as stable version independently of the rest of packages?

**Describe alternatives you've considered**
The only alternative I see is that developers either have to stay on vue. 2 or try to integrate the apollo-client into vue 3 on their own.

**Comment by Akryum** [comment]
All the packages on the branch support Vue 3 now

**Comment by cndev123** [comment]
But isn't everything related to version 4 of vue-apollo still in alpha release? I am talking about a stable release of vue 3 support.
Or is version 3 now also supporting vue 3?
