### ISSUE TITLE
`SubscribeForMore`: Documentation Error?

### ISSUE THREAD

**Issue by dfee** [Akryum/vue-apollo#125]
Under the [`subscribe`](https://github.com/Akryum/vue-apollo/blob/master/README.md#subscribe) section there is a note:
> ⚠️ If you want to update a query with the result of the subscription, use subscribeForMore. The methods below are suitable for a 'notify' use case.

However, I can't find any information on `subscribeForMore` in this repo or [apollo-client](https://github.com/apollographql/apollo-client/search?utf8=%E2%9C%93&q=subscribeformore&type=).

Should this instead be `subscribeToMore`?

**Comment by Akryum** [comment]
Thanks! This is a typo.
