### ISSUE TITLE
useResult in @vue/apollo-composable 4.0.0-alpha.14 is adding undefined to the result type

### ISSUE THREAD

**Issue by LanFeusT23** [Akryum/vue-apollo#1250]
**Describe the bug**
The useResult's pick parameter is getting the data as the type of the useQuery but appending `| undefined` to it.

alpha.12 did not have that behavior.

**To Reproduce**
1. get the result of a useQuery that has a type set
2. call the useResult function with the result of that query and use the pick parameter

**Expected behavior**
The data from that pick should be of the same type as the useQuery type:

Alpha 12 behaviour:
![image](https://user-images.githubusercontent.com/2448410/130854358-6aef949a-3de3-48ca-af90-edad1b14d01b.png)

Alpha 14 behaviour:
![image](https://user-images.githubusercontent.com/2448410/130854379-b55762b0-1bf2-4255-b8bb-080087b118cc.png)

**Versions**
vue: 3.2.6
@vue/apollo-composable: 4.0.0-alpha.14: 
@apollo/client: 3.3.19

**Comment by backbone87** [comment]
this is the correct behavior since data may not be present in the result or may be null.

**Comment by rhangai** [comment]
I don't think this behavior is intended. Even though the result property from the useQuery can be undefined, I thought the purpose of the useResult is to explicitly check for this case and return a defaultValue. 

https://github.com/vuejs/vue-apollo/blob/3792daa5864b8d080f61377deefcd561f233ed27/packages/vue-apollo-composable/src/useResult.ts#L76-L81

Also, there is an open PR https://github.com/vuejs/vue-apollo/pull/1233 and a related issue https://github.com/vuejs/vue-apollo/issues/1231
