### ISSUE TITLE
Problem trying to install @vue/apollo-option

### ISSUE THREAD

**Issue by ChrisAgar** [Akryum/vue-apollo#1251]
**Describe the bug**
I am using this guide for the vue options api.
https://v4.apollo.vuejs.org/guide-option/setup.html#_1-install-vue-apollo-option

I was under the impression this was for Vue 2, but this error is saying it requires Vue 3?

When I npm install @vue/apollo-option I get a dependency error:

npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.1.0" from @vue/apollo-option@4.0.0-alpha.14
npm ERR! node_modules/@vue/apollo-option
npm ERR!   @vue/apollo-option@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Am I being dumb?

**To Reproduce**
1. vue create test
    I used these options:
        Vue CLI v4.5.13
        ? Please pick a preset: Manually select features
        ? Check the features needed for your project: Choose Vue version, Babel, TS, PWA, Router, Vuex, Linter
        ? Choose a version of Vue.js that you want to start the project with: 2.x
        ? Use class-style component syntax? No
        ? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
        ? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
        ? Pick a linter / formatter config: Airbnb
        ? Pick additional lint features: Lint on save
        ? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
        ? Save this as a preset for future projects? No
2. cd test
3. vue add apollo
    I used these options:
        Successfully installed plugin: vue-cli-plugin-apollo
        ? Add example code Yes
        ? Add a GraphQL API Server? No
        ? Configure Apollo Engine? No
4. npm install --save @vue/apollo-option
5. See error

**Expected behavior**
The package should be installed

**Versions**
vue: "^2.6.11"
vue-apollo: "^3.0.0-beta.11"
@apollo/client:

**Comment by Akryum** [comment]
> I was under the impression this was for Vue 2, but this error is saying it requires Vue 3?

Yes it requires Vue 3.

**Comment by ChrisAgar** [comment]
Oh, ok. You might wanna indicate it somewhere in the option api guide.

'Compatible with Vue 2.0 and Vue 3.0'

![131015481-d80ff602-80b8-449c-8113-b2023407365d~2](https://user-images.githubusercontent.com/25499326/131050673-4e4d8f51-e36d-475d-bd9c-8fccf51f4736.jpg)
