### ISSUE TITLE
Default $error handler is passed the Vue component instance instead of error object

### ISSUE THREAD

**Issue by jonstaryuk** [Akryum/vue-apollo#126]
The [default error handler](https://github.com/Akryum/vue-apollo#special-options), defined in a Vue component's `apollo.$error` property, receives the Vue instance as an argument instead of receiving the error object.

Both the [global error handler](https://github.com/Akryum/vue-apollo#constructor) and any [query-specific error handler](https://github.com/Akryum/vue-apollo#advanced-options) seem to work correctly.

For example, this handler:

```js
apollo: {
    // ...
    $error (err) {
      console.warn('component error handler', err)
    },
}
```

produces this console output:

![screen shot 2017-10-08 at 12 34 56 pm](https://user-images.githubusercontent.com/4214270/31320189-20977ba8-ac25-11e7-9785-5881103695a2.jpg)

**Comment by Akryum** [comment]
What is displayed in the browser console?

**Comment by jonstaryuk** [comment]
I just realized the $error handler always gets called, even if there is no error. In which case there's no output from anything except the handler itself.

The output below is when there's an actual network error (with the first warning from the handler itself, as before). The handler is called before the network error happens.

![screen shot 2017-10-08 at 1 30 47 pm](https://user-images.githubusercontent.com/4214270/31320638-f34ec932-ac2c-11e7-9f18-8d722e824b6b.jpg)

**Comment by jonstaryuk** [comment]
Sorry, let me clarify... that last item is from a global error handler defined as

```js
const apolloProvider = new VueApollo({
  // ...
  errorHandler (error) {
    console.log('Vue-Apollo global error handler', error)
  },
})
```

**Comment by mjpvandenberg** [comment]
Same here. The $error option isn't doing what it's supposed to do. I was hoping I could use it to prevent all the `console.error()` calls in vue-apollo's `catchError` function, but no luck.

Is there any way to prevent the default `catchError` function from running? I don't want a 401 Unauthorized to result in a console error.

**Comment by bachdgvn** [comment]
@jonstaryuk if you want to catch 401 error, just try:
```
const apolloProvider = new VueApollo({
  defaultClient: apolloClient,
  defaultOptions: {
    $loadingKey: 'loading'
  },
  errorHandler (error) {
    console.log('Global error handler', error.networkError.statusCode)
  }
})
```

**Comment by Adverbly** [comment]
I am also seeing this issue, but I am having trouble using the error handler to read the response on a 400 error as I am getting a body stream already read error when awaiting err.networkError.response.json(). How are we supposed to access the response body for errors? I can see it being sent in the network debugger tab...

**Comment by kicktipp** [comment]
same here. The $error method is always called when setting up the component as this is called in `defineReactiveSetter(key, func, deep)`. So the $error special option is useless in my opinion

It works if you set it up like this:

```
  const apolloProvider = new VueApollo({
        defaultClient: apolloClient,
        defaultOptions: {
            $error() {
                return (errors) => {
                    console.log("Provider $error handler")
                    console.log(errors.graphQLErrors)
                }
            },
        },
    });

```

But still: this method behaves different than documented. It is called exactly like the default errorHandler and NOT if there is an error inside the default errorHandler

This options seems to be useless for me.
