### ISSUE TITLE
avoid to use /* silent error */, for example useResult has such a code

### ISSUE THREAD

**Issue by stephane303** [Akryum/vue-apollo#1265]
**Is your feature request related to a problem? Please describe.**
An exception happened in useResult.pick callback, and this exception was silenced.
I only received the default value without any explanations. 
This makes debugging extremely difficult.

**Describe the solution you'd like**
Do not silence exception, or if this is necessary, this should cleary stated in the api, of switch on/off with a parameter

**Describe alternatives you've considered**
I am using a try catch in every call I do with useResult, but that can be easily forgotten.

**Additional context**
the issue I am referring to can be found here:
```
export function useResult<
  TResult,
  TDefaultValue,
  TReturnValue,
> (
  result: Ref<TResult>,
  defaultValue?: TDefaultValue,
  pick?: (data: DeepRequired<DeepNonNullable<TResult>>) => TReturnValue,
): UseResultReturn<TResult | TResult[keyof TResult] | TDefaultValue | TReturnValue | undefined> {
  return computed(() => {
    const value = result.value
    if (value) {
      if (pick) {
        try {
          return pick(value as DeepRequired<DeepNonNullable<TResult>>)
        } catch (e) {
          // Silent error
        }
      } else {
        const keys = Object.keys(value)
        if (keys.length === 1) {
          // Automatically take the only key in result data
          return value[keys[0] as keyof TResult]
        } else {
          // Return entire result data
          return value
        }
      }
    }
    return defaultValue
  })
}```

**Comment by Akryum** [comment]
`useResult` is in part a "safe get" so working as intended.
