### ISSUE TITLE
How should i use multiple clients?

### ISSUE THREAD

**Issue by loremru** [Akryum/vue-apollo#1274]
```
import { defineNuxtPlugin } from '#app'
import { DefaultApolloClient } from '@vue/apollo-composable'
import { authApolloClient, catalogApolloClient, apolloProvider } from '~/apollo-client'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.app.provide(DefaultApolloClient, authApolloClient)
  nuxtApp.app.provide('gateway', catalogApolloClient)
})
```

```
await useQuery(CATALOG_LOCALES_QUERY, null, {
        clientId: 'gateway'
      })
```

this code leads to error:  Uncaught (in promise) Error: No apolloClients injection found, tried to resolve 'gateway' clientId

So how should i use multiple clients with vue 3 (nuxt 3) and with composition api? 

It is working with setting default client, but not with multiple.

**Comment by Akryum** [comment]
https://v4.apollo.vuejs.org/guide-composable/setup.html#multiple-clients
