### ISSUE TITLE
OnError is executed as many times as the number of errors executed.

### ISSUE THREAD

**Issue by hiwatee** [Akryum/vue-apollo#1289]
**Describe the bug**
OnError is executed as many times as the number of errors executed when using useMutation.

**To Reproduce**
1. create mutation
```
    const {
      mutate,
      onDone,
      onError
    } = useMutation(MUTATION_QUERY, () => ({
      variables
    }))

    const submit = () => {

      mutate()

      onError(error => {
        console.log(error)
      })

      onDone(result => {
        console.log(result)
      })
    }
```

2. Please occur an graphQLErrors.

3. When an error graphQLErrors, the number of console.log() increases proportionally.

**Expected behavior**
When an error occurs, onError should be executed only once, regardless of the number of previous attempts.

**Versions**
vue: 2.6.14
vue-apollo: 4.0.0-alpha.15
@apollo/client: 3.3.18

**Additional context**
The following code will work as expected.

```
const { client } = useApolloClient()

//...

const submit = () => {
  client
    .mutate<Mutation>({
      mutation: MUTATION_QUERY,
      variables
    })
    .then(result => {
      console.log(result)
    })
    .catch(error => {
      console.log(error)
    })
}
```

**Comment by Akryum** [comment]
Reading your code sample, you are adding `onError` and `onDone` handlers each time your `submit` function is executed, hence the exponential increase in logs. A solution would be to move them out of the `submit` function.
