### ISSUE TITLE
How to update child elements using writeFragment?

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#129]
@Akryum Thanks a lot for pointing me to [Direct Cache Access](http://dev.apollodata.com/core/read-and-write.html). I'm now able to update the cache. But I've pretty big query like below

```
query {
 customer(id:1) {
  pages{
   users {
    messages{
     id
     text
   }
  }
 }
}
```

It's basically a chat dashboard for our customer. A customer can switch between his pages, each page has many users and each user has a conversation (messages). 

When someone sends a new message (its received as a socket io payload) I need to push it to the corresponding user's 'messages;

**Whats the best approach?**
While checking [Direct Cache Access](http://dev.apollodata.com/core/read-and-write.html) I found readFragment and writeFragment should be used to do this. But I'm not able to declare a fragment in vue-apollo. The docs of Vanilla JS is also not working

Or is it ok to update the entire query using readQuery and writeQuery?

**Comment by Akryum** [comment]
[Here](https://github.com/Akryum/devfest-nantes-2017/blob/master/app/src/graphql/QuestionFragment.gql) is an example of a fragment, which is used [here](https://github.com/Akryum/devfest-nantes-2017/blob/master/app/src/graphql/QuestionUpdated.gql). Make sure to have the [right loader](https://github.com/Akryum/devfest-nantes-2017/blob/82c56a4f190a64744d795a3628d9c703d93e21b1/app/build/webpack.base.config.js#L41-L45) configured in webpack.

**Comment by gijo-varghese** [comment]
So I don't have to use `createFragment `? In the Apollo docs it's like below:
```
import { createFragment } from 'apollo-client';
// Save the fragment into a variable
const bookInfoFragment = createFragment(gql`
  fragment bookInfo on Book {
    name
    coverImage
    numPages
  }
`);

// Use the fragment in a query
// Note that we use the fragment name to refer to it, not the variable name from JavaScript.
client.query({
  query: gql`
    {
      author(id: 5) {
        books {
          id
          ...bookInfo
        }
      }
    }
  `,
  fragments: bookInfoFragment,
})
```

**Comment by gijo-varghese** [comment]
@Akryum Thanks :)
