### ISSUE TITLE
v4: Subscriptions don't stop after the component equipped with $apollo is unmounted

### ISSUE THREAD

**Issue by BoHuny** [Akryum/vue-apollo#1290]
**Describe the bug**
When a vue component composed with $apollo is unmounted, the subscriptions still go on
After investigations of the source code, it seems that it is caused by the instance being renamed to $apollo from $_apollo

![image](https://user-images.githubusercontent.com/54338615/143562218-fef2968a-ec6e-47b9-aa24-59a278af25b1.png) (instance creation)

![image](https://user-images.githubusercontent.com/54338615/143562257-aba25767-93cb-4449-8095-086f5d279e88.png) (inaccessible condition, this._apollo will always be undefined, thus the destroy method that does the unsubscribing is never called)

**To Reproduce**
1. Use subscriptions within a component under $apollo
2. Unmount the component during the execution

**Expected behavior**
All subscriptions are removed and no more query is sent to the backend

**Versions**
vue: 3.2.20
@vue/apollo-option: 4.0.0-alpha.15
@apollo/client: 3.5.5

**Comment by svyatoslav-e** [comment]
I faced with very similar behavior. When router go back in history, apollo query still calls without stopping

**Comment by Akryum** [comment]
Fixed in https://github.com/vuejs/vue-apollo/pull/1273
