### ISSUE TITLE
TypeError: Cannot set property someProperty of #<Object> which has only a getter in production build

### ISSUE THREAD

**Issue by svyatoslav-e** [Akryum/vue-apollo#1295]
**Describe the bug**
After migration to Vue3 and vue-apollo v4  the error is only displayed in the production build, not in dev.

**To Reproduce**
In vue component:
`apollo: {
   someProperty: {
      query: GET_SOME_PROPERTY
   }
},
created() {
   this.someProperty = {}
}
`

**Expected behavior**
"TypeError: Cannot set property someProperty of #<Object> which has only a getter in production build" should displays in development

**Versions**
vue: 3.2.21
vue-apollo: 4.0.0-alpha.16
@apollo/client: 3.5.5

**Comment by Akryum** [comment]
Use `data () { return { someProperty: {} } }`

**Comment by svyatoslav-e** [comment]
I use `data () { return { someProperty: {} } }` , but when I try to modify someProperty in methods or hook, this error appears. I can see this error only in production build. I understand that is not good approach to rewrite someProperty, but to fix this I need to have ability see this kind of error during developing. This is a problem.

**Comment by svyatoslav-e** [comment]
@Akryum can I somehow tweak this behavior? Thanks
