### ISSUE TITLE
Setting loadingKey property to true by default

### ISSUE THREAD

**Issue by matteodem** [Akryum/vue-apollo#13]
In a test app I'm setting up to have SSR I get an error that the markup that is served (from the server) is different from the one generated on the client. (because on the client the loading property is true even if instantiated with false in the `data` method)

That message goes away when setting the loadingKey property to `true`, but then apollo doesn't call the graphql endpoint anymore. Any reason why that is?

To reproduce, change `0` to `1` or `true` in here https://github.com/Akryum/frontpage-vue-app/blob/master/src/PostList.vue#L48.

**Comment by Akryum** [comment]
Won't you mind sharing your app code?

**Comment by matteodem** [comment]
here it is https://github.com/matteodem/vue-apollo-loadingkey-bug,  see https://github.com/matteodem/vue-apollo-loadingkey-bug/blob/master/src/app/components/About.vue#L43

**Comment by matteodem** [comment]
any idea?

**Comment by Akryum** [comment]
Well I can't launch your app, I'll have to make a SSR version of frontpage when I have time.

![image](https://cloud.githubusercontent.com/assets/2798204/20867754/fa7efaa2-ba4b-11e6-9168-635fe28e2b30.png)

`Specified access path not found`

**Comment by matteodem** [comment]
oh. seems to work on OSX. isn't the simple reprodctuon description I have sufficient? 

> To reproduce, change 0 to 1 or true in here https://github.com/Akryum/frontpage-vue-app/blob/master/src/PostList.vue#L48.

It should just display "loading" and not load the data from the graphql endpoint.

**Comment by matteodem** [comment]
adding apollo configuration like following helps:

```js
posts: {
      query: postsQuery,
      loadingKey: 'loading',
      watchLoading(isLoading) {
        // TODO: remove this hack after resolving: https://github.com/Akryum/vue-apollo/issues/13
        this.loading = isLoading;
      }
    },
```

but this shouldn't be required IMO.

**Comment by matteodem** [comment]
The problem is here: https://github.com/Akryum/vue-apollo/blob/master/src/vue-plugin.js#L160. Do you remember any reason the `if` is in there?

**Comment by Akryum** [comment]
If you don't define `loadingKey` in the apollo options.

**Comment by matteodem** [comment]
ah yes. ignore that sorry

**Comment by matteodem** [comment]
What's the reasoning behind using numbers instead of booleans for the loading key?

**Comment by Akryum** [comment]
So that you can have multiple queries for one loading spinner. :smile_cat:

**Comment by matteodem** [comment]
I guess it's just weird to me that the counter is set to 1 even before the component is mounted. That's why on the server it renders it with false (as in 0) and then the mismatch happens on the client. 

Do you have any suggested solution to this? I'll happily submit a PR later today

**Comment by Akryum** [comment]
The `q` function is called the first and then every time Vue dispatch a change in the reactive data inside the `variables` function. This in turns increment your `loadingKey` property. This means that as soon as your component's `created` is called, a query is sent and the counter equals `1`. It may be the reason you have a mismatch in the HTML, since it was 0 on the server, and before the component is mounted it will be 1.

**Comment by Akryum** [comment]
We may have to make a server-side version of the package to increment the value of `loadingKey` for each query defined on the component.

**Comment by Akryum** [comment]
We could also add the option to run the queries on the server. What results do you get by installing the Vue plugin in your server-side code too?

**Comment by matteodem** [comment]
I get errors when running it on the server

**Comment by matteodem** [comment]
```
Error sending the query undefined ReferenceError: fetch is not defined
    at HTTPBatchedNetworkInterface.HTTPFetchNetworkInterface.fetchFromRemoteEndpoint (/Users/Matteo/Projects/personal/relaxstack/kits/standard/src/networkInterface.ts:186:12)
```

**Comment by Akryum** [comment]
Since `fetch` is only available in a browser, try installing [node-fetch](https://www.npmjs.com/package/node-fetch) and exposing it globally:

```javascript
import fetch from 'fetch'
global.fetch = fetch
```

**Comment by matteodem** [comment]
awesome! so with `loading: false` by default it now loads all the data on the server side before delivering the result. Even though that's great, it doesn't save the same markup on the client.

(on the client it's loading for a split second and on the server it's not loading at all as it already has the data).

**Comment by matteodem** [comment]
probably need to get this to work with vuex to have a consistent state on the server and client

**Comment by Akryum** [comment]
Could you try with the latest version of `vue-apollo`?

**Comment by matteodem** [comment]
What can I try?

**Comment by Akryum** [comment]
If there are still issues with `loadingKey` like described in the original post, since I rewrote that feature recently.

**Comment by Akryum** [comment]
Please re-open if you still have this issue.
