### ISSUE TITLE
Can't pre-populate fields in edit forms

### ISSUE THREAD

**Issue by kjetilge** [Akryum/vue-apollo#130]
I find it very difficult to populate a form with existing data derived from a query. in order to update the v-model connected variables in data(), I've tried to do this:
```
created () {
  this.description = this.Post.description
}
```

but it only works once in a while. (wrong timing)

I've also tried: 
```
watchLoading (isLoading, countModifier) {
 if (!isLoading) {
  this.description = this.Post.description
 }
}
```

But that does not work either. Any suggestions ?

**Comment by dennisbrandenberger** [comment]
Found a "solution" - at least it works for now:
```
watchLoading (isLoading, countModifier) {
  if (!isLoading) {
    this.$nextTick(() => {
      this.description = this.Post.description
    })
  }
}
```

I have no idea if this is anything near best practice. For a more elegant method (but with a lot more code) the vue-apollo-todos example is perhaps the way to do it: https://github.com/Akryum/vue-apollo-todos

**Comment by dennisbrandenberger** [comment]
Oops, seems like the above solution is not so good. When using Vue-router, the second time I go to the edit page the data disappears again. However, if I refresh the page – the data comes back. Strange..

**Comment by dennisbrandenberger** [comment]
I've got it working again. For this to work we need fetchPolicy: 'cache-and-network',
complete code:
//.......
variables () {
  return {
    postId: this.$route.params.carId
  }
},
fetchPolicy: 'cache-and-network',
watchLoading (isLoading, countModifier) {
  if (!isLoading) {
    this.$nextTick(() => {
      this.description = this.Post.description
    })
  }
}

**Comment by Samuell1** [comment]
you can simply use `result` callback

```
  result ({ data, loading }) {
    if (!loading) {
      this.items = data.items
    }
  }
```

**Comment by dennisbrandenberger** [comment]
Wow! Thank's – that's so much better :-)
