### ISSUE TITLE
useLazyQuery missing in docs

### ISSUE THREAD

**Issue by bicarlsen** [Akryum/vue-apollo#1308]
I just spent a while working with `useLazyQuery` which doesn't seem to be documented on the [Vue Apollo Docs site](https://v4.apollo.vuejs.org/api/use-query.html). Is it possible to contribute to these docs? If not would it be possible to at least add a section to the docs for `useLazyQuery` so people know it exists?

**Comment by Akryum** [comment]
Sure you can contribute to the docs! 👍

**Comment by bicarlsen** [comment]
@Akryum Can you elaborate on how to do that? I was searching for the docs, but couldn't find it in any of the repositories.

**Comment by Akryum** [comment]
The docs are located [here](https://github.com/vuejs/apollo/tree/v4/packages/docs), it's a vuepress app with markdown files.

**Comment by bicarlsen** [comment]
Completely missed that. I was thinking it would be in its own repository. Thank you.
