### ISSUE TITLE
Vue apollo requiring variables to refetchQueries attribute after mutation

### ISSUE THREAD

**Issue by JoaoHCopetti** [Akryum/vue-apollo#1326]
**Describe the bug**
So i've been reading the Apollo Graphql documentation and in this part it says:
> Each included query is executed with its most recently provided set of variables.

https://www.apollographql.com/docs/react/data/mutations/#refetching-queries

So it means if i try to refetch any query after a mutation, for example:
```
import { clothingTypeUpdate, clothingTypes } from '@/graphql/ClothingType.gql'

await this.$apollo.mutate({
  mutation: clothingTypeUpdate,
  variables: {
    id: clothingType.id,
    input: {
      is_hidden: !clothingType.is_hidden
    }
  },
  refetchQueries: [
    { query: clothingTypes }
  ]
})
```

It should use the most recently provided variables, but that isn't what is happening, i have two `clothingTypes` queries, in one view i don't use any variable, but in another i use, the thing is that the only query being refetched is the one in the view without variables, to refetch both i need to explicit set the variables like that:

```
import { clothingTypeUpdate, clothingTypes } from '@/graphql/ClothingType.gql'

await this.$apollo.mutate({
  mutation: clothingTypeUpdate,
  variables: {
    id: clothingType.id,
    input: {
      is_hidden: !clothingType.is_hidden
    }
  },
  refetchQueries: [
    { query: clothingTypes },
    { query: clothingTypes, variables: { is_hidden: false } }
  ]
})
```

So why i need to inform the variables, is it right? Because according to documentation of Apollo it says it should use the most recently used variables.

I also tried using only the query name as string, the behavior is the same.

**Versions**
vue: ^2.6.11
vue-apollo: ^3.0.0-beta.11
@apollo/client:

**Comment by ThibaultNocchi** [comment]
I have the same problem. It seems I need to put the query with each variable set I used instead of refreshing all the queries of the same name.

**Comment by JoaoHCopetti** [comment]
@ThibaultNocchi I figured out that this is the Apollo version outdated that Vue Apollo installs, you probably made the same mistake that i did reading the recent version of apollo documentation, but with and old apollo version of it installed.

If you want to refetch queries with the most recently set of variables provided you can do it by specifing the name of the query in the array `refetchQueries` as string, like so:
```
refetchQueries: ['myQuery', 'myOtherQuery']
```

Looks like currenctly the version of Apollo provided by Vue Apollo doesn't allow to pass a imported `.gql` file, so if you try something like:
```
import { myQuery } from '@/graphql/schema.gql'

refetchQueries: [myQuery]
```

It will throw an error.

And, of course, if you use and object inside the array you will need to specify the params of the query.

I recommend you to set up your own Apollo config so that way you can install the latest version, use the `@apollo/client/core` package provided by Apollo React to use Apollo without React: 
https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#using-apollo-client-without-react

Here is my setup with Vue if it helps:

```
// vue-apollo.js
import Vue from 'vue'
import VueApollo from 'vue-apollo'

import { ApolloClient, createHttpLink } from '@apollo/client/core'
import { InMemoryCache } from '@apollo/client/cache'
import { setContext } from '@apollo/client/link/context'

Vue.use(VueApollo)

const AUTH_TOKEN_NAME = 'auth-token'

const httpLink = createHttpLink({
  uri: process.env.VUE_APP_GRAPHQL_HTTP
})

const authLink = setContext(async (_, { headers }) => {
  const authToken = localStorage.getItem(AUTH_TOKEN_NAME)

  return {
    headers: {
      ...headers,
      authorization: authToken ? `Bearer ${authToken}` : ''
    }
  }
})

const defaultOptions = {
  link: authLink.concat(httpLink),
  // cache
}

export const createApolloClient = () => ({
  apolloClient: new ApolloClient({ ...defaultOptions })
})

export const apolloClientInstance = createApolloClient()

export function createProvider (options = {}) {
  const { apolloClient } = apolloClientInstance

  const apolloProvider = new VueApollo({
    defaultClient: apolloClient,
    errorHandler: async (error) => {

      // eslint-disable-next-line no-console
      console.log(
        '%cError',
        'background: red; color: white; padding: 2px 4px; border-radius: 3px; font-weight: bold;',
        error.message
      )
    }
  })

  return apolloProvider
}

export async function onLogin (apolloClient, token) {
  if (typeof localStorage !== 'undefined' && token) {
    localStorage.setItem(AUTH_TOKEN_NAME, token)
  }

  // if (apolloClient.wsClient) restartWebsockets(apolloClient.wsClient)

  try {
    await apolloClient.resetStore()
  } catch (e) {
    // eslint-disable-next-line no-console
    console.log(
      '%cError on cache reset (login)',
      'color: orange;',
      e.message
    )
  }
}

// Manually call this when user log out
export async function onLogout (apolloClient) {
  if (typeof localStorage !== 'undefined') {
    localStorage.removeItem(AUTH_TOKEN_NAME)
  }

  // if (apolloClient.wsClient) restartWebsockets(apolloClient.wsClient)

  try {
    await apolloClient.resetStore()
  } catch (e) {
    // eslint-disable-next-line no-console
    console.log('%cError on cache reset (logout)', 'color: orange;', e.message)
  }
}

```

**Comment by ThibaultNocchi** [comment]
Thank you, I'll try it!
