### ISSUE TITLE
"Failed to resolve component: ApolloQuery"

### ISSUE THREAD

**Issue by newfrontab** [Akryum/vue-apollo#1332]
**Overview**
I'm trying to migrate my previous setup Vue Apollo (Vue 2) to Vue 3. I've followed the migration guide as instructed in 
https://v4.apollo.vuejs.org/migration/. When trying to use the [ApolloQuery component](https://v4.apollo.vuejs.org/api/apollo-query.html) it doesn't work. 

I've tried:
- Adding `dangerousTaggedTemplateString: true` to chainWebPack options.
- Removing all Apollo related packages and installing the ones shown in the guide.
- Confirm the library is running by running Apollo in the script instead of template.

**To Reproduce**
Use the <ApolloQuery></ApolloQuery> tag:

```
<ApolloQuery
  :query="gql => gql`
    query MyHelloQuery ($name: String!) {
      hello (name: $name)
    }
  `"
  :variables="{ name }"
>
  <template v-slot="{ result: { error, data }, isLoading }">
    <!-- Loading -->
    <div v-if="isLoading" class="loading apollo">Loading...</div>

    <!-- Error -->
    <div v-else-if="error" class="error apollo">An error occurred</div>

    <!-- Result -->
    <div v-else-if="data" class="result apollo">{{ data.hello }}</div>

    <!-- No result -->
    <div v-else class="no-result apollo">No result :(</div>
  </template>
</ApolloQuery>
```

1. Warning gets displayed in console:
```
[Vue warn]: Failed to resolve component: ApolloQuery
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
```

2. Followed up by an error trying to access the result slot within the ApolloQuery component:
`TypeError: Cannot read properties of undefined (reading 'result')`

**Expected behavior**
Data gets fetched and renders in the template.

**Versions**
vue: 3.2.30
@apollo/client: ^3.5.10
@vue/apollo-option: ^4.0.0-alpha.16,
graphql: ^16.3.0,
graphql-tag: ^2.12.6,

**Comment by Akryum** [comment]
You also need  `@vue/apollo-components`

**Comment by newfrontab** [comment]
> You also need `@vue/apollo-components`

It's working, much appreciated!
