### ISSUE TITLE
Uncaught Invariant Violation: eviction is not implemented on InMemory Cache

### ISSUE THREAD

**Issue by JoaoHCopetti** [Akryum/vue-apollo#1334]
**Describe the bug**
Looks like i just can't evict any query from cache like Apollo Graphql, the method evict from InMemoryCache always throws this error.

```
this.$apollo.getClient().cache.evict()
```

```
Uncaught Invariant Violation: eviction is not implemented on InMemory Cache
```

I couldn't find anywhere else how to implement eviction so i think it's not something we should implement.

**Expected behavior**
We should be able to evict data from cache using `evict` method from InMemoryCache like:
```
this.$apollo.getClient().cache.evict({fieldName: 'something'})
this.$apollo.getClient().cache.gc()
```

**Versions**
vue: "^2.6.11",
vue-apollo: "^3.0.0-beta.11"

**Additional context**
I'm using the default cache from vue cli setup, no changes was made on cache config of vue-apollo.js.

**Comment by abhishek-7span** [comment]
Hey @JoaoHamerski, Did you find anything about this? I am facing this issue right now.

Thanks!
