### ISSUE TITLE
vue-apollo-components are registered twice

### ISSUE THREAD

**Issue by KammererTob** [Akryum/vue-apollo#1336]
While migrating my project to Vue 3 i noticed (and got a warning) that the vue-apollo-components seem to be registered twice. Is there a specific reason for this?

Here is the code:
```
export function install (app, options) {
  app.component('ApolloQuery', CApolloQuery)
  app.component('ApolloQuery', CApolloQuery)
  app.component('ApolloSubscribeToMore', CApolloSubscribeToMore)
  app.component('ApolloSubscribeToMore', CApolloSubscribeToMore)
  app.component('ApolloMutation', CApolloMutation)
  app.component('ApolloMutation', CApolloMutation)
}
```

And those are the warnings i get:
> [Vue warn]: Component "ApolloQuery" has already been registered in target app.
> [Vue warn]: Component "ApolloSubscribeToMore" has already been registered in target app.
> [Vue warn]: Component "ApolloMutation" has already been registered in target app.

The only thing i am doing in my app is this:
`app.use(VueApolloComponents);`

**Expected behavior**
The components to be registered only once

**Versions**
vue: =3.2.20
@apollo/client: ^3.5.10
@vue/apollo-components: ^4.0.0-alpha.16

**Comment by websitevirtuoso** [comment]
Have the same issue

**Comment by websitevirtuoso** [comment]
Version 
"@vue/apollo-components": "^4.0.0-alpha.17"
path to the file
node_modules/@vue/apollo-components/dist/vue-apollo-components.esm.js

![image](https://user-images.githubusercontent.com/5112918/174529260-244c3260-5012-42c5-9553-38304ee4b3a9.png)

**Comment by websitevirtuoso** [comment]
@Akryum
