### ISSUE TITLE
Unable to reuse Fragments

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#134]
I have a query like this:
```
query customer($id: ID!) {
  user (id: $id) {
    id
    last_message {
      id
      message
    }
    messages {
      id
      message
    }
  }
}
```
Since `id` & `message` are used many times, I created a fragment for this:
```
fragment message on Message {
  id
  message
}
```

And final query as:
```
query customer($id: ID!) {
  user (id: $id) {
    id
    last_message {
      ...message
    }
    messages {
      ...message
    }
  }
}
```
But I'm getting an error:
` "Fragment "message" cannot be spread here as object…ype "LastMessage" can never be of type "Message"."`

What did I do wrong? I thought fragments are somethings that I can reuse! What does this '**on Message**' in fragment really mean? Because when I create another fragment with '**on LastMessage**' and use ...lastmessage it works

**Comment by Samuell1** [comment]
You cant use it because you have in last_message other typename then in messages

**Comment by gijo-varghese** [comment]
@Samuell1 so they've to be of the same type? But how does graphql client knows it?

**Comment by Samuell1** [comment]
@gijo-varghese because in graphql scheme is that typename defined and you shoud have same typename for same things

**Comment by gijo-varghese** [comment]
@Samuell1 ok. Thanks :)
