### ISSUE TITLE
Can't find field <foo> on ROOT_QUERY (Mutations that write data to the cache for queries with variables)

### ISSUE THREAD

**Issue by mekhami** [Akryum/vue-apollo#135]
https://gist.github.com/mekhami/16bcd5aec1f909a584cde820f5acc1ad

Here's the code for the original query, the mutation that should add its results to that query/cache, and the error message I'm getting.

Handling queries and related mutations when the query has variables has been giving me headaches on and off for a few weeks. There's a desperate need for both some documentation and maybe a more helpful error message here.

**Comment by Samuell1** [comment]
I think we solved this on Vue discord

**Comment by thomasaull** [comment]
If you found a solution, could you please provide it here? I'm struggeling with the same issue

**Comment by Samuell1** [comment]
@thomasaull i think problem was because he wanted to update cache before query was cached

**Comment by thomasaull** [comment]
I get the same error, however, if I specify the exact variables I used for the initial query, it works fine. So I gess, no variables = not cached yet, variables = cached?

**Comment by Samuell1** [comment]
Your variables must be exact same in query and when you updating cache otherwise you get errors

**Comment by ffxsam** [comment]
I'm getting this on a simple query:

```js
  apollo: {
    tracks: {
      query: gql`
        {
          tracks {
            items {
              id
              name
              key
            }
          }
        }
      `,
      pollInterval: 5000,
    },
  },
```

Does anyone have a solution? This is a total brick wall.

**Comment by Samuell1** [comment]
@ffxsam vue-apollo cant do anything with this, its simply apollo caching thing

Btw you query is in bad format, this 
```
query: gql`
  query tracks {
    tracks {
      items {
        id
        name
        key
      }
    }
  }
`,
```

**Comment by ffxsam** [comment]
"its simply apollo caching thing" - meaning what, it's a bug?

And `query tracks { } ` is not necessary if I'm not passing variables into it. So it's not a bad or wrong format.

**Comment by Samuell1** [comment]
@ffxsam its not a bug its telling you your query is not same as what you want

Thats maybe true, but better check where is your every in cache with apollo devtools
