### ISSUE TITLE
useQuery result not valid after variable change with graphql error

### ISSUE THREAD

**Issue by Schloemicher** [Akryum/vue-apollo#1352]
**Describe the bug**
~~When the variables change in useQuery the result doesnt get updated anymore~~
When the variables change in useQuery the result doesnt get updated anymore if an apollo error exists

**To Reproduce**
1. component
```typescript
// component props: scope; query
const propsRefs = toRefs(props);
const read = useQuery(props.query, { scope: propsRefs.scope, fallback: false }, { fetchPolicy: "no-cache" });
```
2. run frontend with set scope property
3. change scope
4. query refetches 
5. graphql server sends error
6. returns old result

**Expected behavior**
if for example the propsRefs.scope value changes, the query should refetch and return the correct result

**Versions**
vue: 3.2.33
@apollo/client: 3.6.2
@vue/apollo-composable: 4.0.0-alpha.17

**Additional context**
in @vue/apollo-composable: 4.0.0-alpha.16 it works as expected

**Comment by wreality** [comment]
I believe the entire variables object needs to either be a reactive or a ref.

```
const scope = toRef(props, 'scope') // Note: toRef not toRefs
const variables = computed(() => ({scope: scope.value, fallback: false}));

const read = useQuery(props.query, variables);
```

**Comment by Schloemicher** [comment]
thanks for the reply!

Your version and my version work.

The problem is that if a variable is changed and the response is an error -> the result is not changed to undefined/null

i don't know if this is intended

**Comment by wreality** [comment]
Check out error policies in the docs: https://v4.apollo.vuejs.org/guide-composable/error-handling.html

Specifically:

> The possible options for errorPolicy are:

> none: This is the default policy to match how Apollo Client 1.0 worked. Any GraphQL Errors are treated the same as network errors and any data is ignored from the response.

**Comment by Schloemicher** [comment]
Ahh thanks!

I don't know why it worked in the minor version before
But the current version works indeed as described  in the docs
