### ISSUE TITLE
getResult deprecation question

### ISSUE THREAD

**Issue by wreality** [Akryum/vue-apollo#1353]
Is it safe to assume that with getResult being [removed](https://github.com/vuejs/apollo/commit/2e65263329fa8c9d30cd681778bf7a8fcc22bfed)  from the documentation (rather than a deprecation note added to the documentation) that the intention is that it will be removed for the 4.0 release ?

Just figuring out where it needs to live in our project's priorities.

**Comment by Luferov** [comment]
And in general, why useResult is deprecated? What is the reason? Because this function is very usefull.

**Comment by Akryum** [comment]
@wreality Yes it will be removed before 4.0

@Luferov It's not that useful anymore now that optional chaining and nullish coalescing operators are available in stadnard JavaScript. So it makes sense to remove it to cleanup the API a bit.
