### ISSUE TITLE
version 3.0.0-alpha.1: Query results not updated after page reload

### ISSUE THREAD

**Issue by jvbianchi** [Akryum/vue-apollo#136]
hi, after I updated to version 3.0.0-alpha.1 my app works fine. But if I reload a page with a Query, vue-apollo executes the query gets the result, but doesn't update the query result.

 ```  
apollo: {
    cboOptions: {
      query: CboAllQuery,
      update(result) {
        return result && [{ codigo: '', nome: '' }, ...result.allCboLookups];
      },
      loadingKey: 'cboLoading',
    },
  },
```
is this example the variable `cboOptions` will not be updated with the query results
 
but if I change the route and then come back, the results are shown

I don't know why with version 2.1.0-rc.8 this doesn't happen

**Comment by Akryum** [comment]
Do you have a reproduction to share?

**Comment by rnenjoy** [comment]
@Akryum, just wanted to say you're the best! Thanks for 3.0!!!

**Comment by jvbianchi** [comment]
Reproduction, I don't know how to do that.

I put a `console.log` in the update function to see when it runs:
```
  apollo: {
    cboOptions: {
      query: CboAllQuery,
      update(result: ICboAllQuery) {
        console.log(result);
        return result && [{ codigo: '', nome: '' }, ...result.allCboLookups];
      },
      loadingKey: 'cboLoading',
    },
  },
```
After I reload the page this function doesn't run. But if I call 
`this.$apollo.queries.cboOptions.refetch();` 
then the function runs and the cboOptions gets populated with the results.

**Comment by Akryum** [comment]
A reproduction is a repository or zip where you can reproduce the issue so that I can look at it. :wink:

**Comment by jvbianchi** [comment]
Reproduction: https://github.com/jvbianchi/vue-apollo-error

**Comment by Akryum** [comment]
See: https://github.com/nuxt-community/apollo-module/issues/38
