### ISSUE TITLE
loading value does not change after refetch completed

### ISSUE THREAD

**Issue by aki77** [Akryum/vue-apollo#1361]
**Describe the bug**
After the change of 082acf90c2c22edf28f443306da39b535d2b0a1d, loading is not updated from `true` to `false` even after refetch.

**To Reproduce**
1. const { loading, refetch } = useQuery<T, T2>(query, options)
2. loading is true on first fetch, it's fine.
3. then call refetch function. the loading changes to `true`.
4. loading is still `true` when the request is complete.

**Expected behavior**
When start refetch , loading should change to true ,and change to false at request done.

**Versions**
vue: 3.2.36
@vue/apollo-composable: 4.0.0-alpha.17
@apollo/client: 3.6.5

**Additional context**
This will not occur if the `notifyOnNetworkStatusChange` option is enabled.

**Comment by nevermin9** [comment]
The same problem here,
completing of execution `refetch` doesn't change useQuery's`loading`.
Though, `refetch().then(result => console.log(result))` result consist of `loading: false`

**Comment by sonphnt** [comment]
I have the same issue with useQuery() and refetch(variables). The first time, loading true -> false when it is done, This is correct
But I have a button to refetch data with the same variables, sometimes I get data undefined with networkStatus = 2 and loading = true when it is done with onResult().

**Comment by nevermin9** [comment]
@sonphnt yh, it's because result of refetch isn't handled
https://github.com/vuejs/apollo/pull/1366/files#diff-6bc7e9678664512fca6286f9a45bc6bdb7f3e02b733c2954ff1fb8210e2f87deR433

**Comment by sonphnt** [comment]
@nevermin9 Ok, I see, but will it set loading to false as well? I don't see the code loading.value = false in your PR

**Comment by nevermin9** [comment]
@sonphnt look at `processNextResult`
in my pr
https://github.com/vuejs/apollo/pull/1366/files#diff-6bc7e9678664512fca6286f9a45bc6bdb7f3e02b733c2954ff1fb8210e2f87deR436
and it's declaration
https://github.com/vuejs/apollo/pull/1366/files#diff-6bc7e9678664512fca6286f9a45bc6bdb7f3e02b733c2954ff1fb8210e2f87deR277
it is used everywhere, where query result should be processed

**Comment by sonphnt** [comment]
OK, then it will guarantee useGlobalQueryLoading() keeps working properly with refetch as well.

**Comment by aki77** [comment]
@nevermin9 @Akryum  Thanks!

**Comment by LighthouseKeeperYN** [comment]
The issue is still present for useGlobalQueryLoading
