### ISSUE TITLE
Share Query data across components and router-view?

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#137]
I've big query like this:
```
{
      customer(id: 1) {
        pages {
          id
          name
          users{
            id
            first_name
            messages{
              id
              message
            }
          }
        }
      }
    }
```
and I'm loading the query inside a `app.vue` that have child components and router-view. 
Child components (they're inside the router view) can be `<users>`,  `<messages>`, `<customer>` etc
The app.vue may look like this:
```
<template>
  <pages></pages>
  <router-view></router-view>
</template>
```
How can I use the data from query in inner components (including router-view)?

What about splitting the query into fragments and call `readFragment` in each component? Or is there a better way?

**Comment by Akryum** [comment]
You can use the same query in multiple components (or subset of it).

Le dim. 29 oct. 2017 à 17:11, Gijo Varghese <notifications@github.com> a
écrit :

**Comment by gijo-varghese** [comment]
Ok. So since it's cached it won't make another request, right?

**Comment by Akryum** [comment]
Yes

Le dim. 29 oct. 2017 à 18:20, Gijo Varghese <notifications@github.com> a
écrit :

**Comment by gijo-varghese** [comment]
Awesome! Thanks :+1:
