### ISSUE TITLE
Apollo client is not resolved in nested callback

### ISSUE THREAD

**Issue by senritsu** [Akryum/vue-apollo#1370]
**Describe the bug**
When calling a mutation in a nested callback inside a composable, the apollo client is not found and the resolver throws an error. Using `provideApolloClient` in addition to `provide` works.

**To Reproduce**

I unfortunately cannot provide a full working reproduction at the moment, as the code is part of a company-internal app. The following outlines the situation.

```ts
// App.vue setup
useApollo()
useProblematicCode()
```
```ts
// apollo.ts
export function useApollo() {
  const apolloClient = createApolloClientWithConfig()

  // omitted: verbose split link setup with reactive auth headers

  // provideApolloClient(apolloClient) // <-- this fixes the issue, but should not be necessary if in a setup function according to docs
  provide(DefaultApolloClient, apolloClient)
}
```
```ts
// problematic-code.ts

export function useProblematicCode () {
  const { mutate } = useMutation(someDocument)
  
  const outerCallback = (userId) => {
    const innerCallback = async () => {
      await mutate()
      console.log('mutation done')
    }
    
    // for minimal reproduction only
    document.addEventListener('test-event', innerCallback)
    // our actual code looks more like
    // unrelatedThing.addListener('some-event', innerCallback)
    // unrelatedThing.doSomethingAsync(userId)
  }

  watchEffect(() => {
    if (!userStore.userId) return

    outerCallback(userId)
  })
}
```

In roughly this setup, when (for testing) calling `document.dispatchEvent(new CustomEvent('test-event))` from the console, the mutation fails because apollo cannot resolve the client. When debugging into `resolveClient` inside [useApolloClient](https://github.com/vuejs/apollo/blob/v4/packages/vue-apollo-composable/src/useApolloClient.ts), the closure-captured `savedCurrentClient` is `undefined` and resolution from the setup scope apparently also does not work.

```stacktrace
useApolloClient.ts:68 Uncaught (in promise) Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.
    at resolveClient (useApolloClient.ts:68:13)
    at mutate (useMutation.ts:78:20)
    at HTMLDocument.<anonymous> (push-notification.ts:63:13)
```

**Expected behavior**
Mutation works.

**Versions**
vue: 3.2.31
vue-apollo: 4.0.0-alpha.17
@apollo/client: 3.6.0

**Additional context**

Adding `provideApolloClient(apolloClient)` in addition to the regular `provide` call fixes the problem.

**Comment by Akryum** [comment]
Try to move it under the root component? Looks like it's a provide/inject issue

**Comment by senritsu** [comment]
`App.vue` is the root component, the 2 composables are called directly in root `setup`. 

When debugging into [useApolloClient.ts@L49](https://github.com/vuejs/apollo/blob/fdbb65f3f8aaf80034973953316878b9cd118819/packages/vue-apollo-composable/src/useApolloClient.ts#L49) it also shows both injections as `null`, but `getCurrentInstance().provides` has a key `Symbol(default-apollo-client)` with the correct client as its value

`getCurrentInstance().provides[DefaultApolloClient]` in the console returns the correct client, while `inject(DefaultApolloClient)` returns `undefined`.

**Comment by Akryum** [comment]
Yes because you are on the root, so it can't inject things from itself.

**Comment by senritsu** [comment]
Right, that makes sense, I just realized that when looking up `inject` details again. That pretty much means that the root component can never use any apollo queries with the default setup (with `useMutation` etc.), is that correct?

I remember some other issue about directly returning and/or specifying a client to use, that would probably work as a workaround. Obviously `provideApolloClient` also works, since it sidesteps the whole `provide`/`inject` mechanism.

Thanks for the quick resolution, I will think about how we can reorganize things in our app for a more idiomatic usage.

**Comment by productdevbook** [comment]
how to fix ? @senritsu

**Comment by senritsu** [comment]
@productdevbook either don't use Apollo directly in the root component (or more specifically, the component you `provide` Apollo from, further down the component tree should work fine), or use `provideApolloClient` (commented out in my original `apollo.ts` in the issue)

**Comment by productdevbook** [comment]
> provideApolloClient

iam App.vue

```ts
import { DefaultApolloClient, provideApolloClient } from '@vue/apollo-composable'
import { apolloClient } from './modules/apollo'
provideApolloClient(apolloClient)
```

and delete main.ts etc 

main.ts
```
  app.provide(DefaultApolloClient, {
    default: apolloClient,
  })
  ```
  
  add only 
  
  what is problem ?

**Comment by senritsu** [comment]
I don't really understand the problem, can you provide an example on [StackBlitz](https://stackblitz.com/) or something?

**Comment by productdevbook** [comment]
maybe i will try

> I don't really understand the problem, can you provide an example on [StackBlitz](https://stackblitz.com/) or something?

![image](https://user-images.githubusercontent.com/38668796/188203433-02c41c3d-97bc-43bf-b245-6896b9ab4c6c.png)


![image](https://user-images.githubusercontent.com/38668796/188203459-3225dde5-8ea9-4fd1-b79a-08b2a4b19e4c.png)
