### ISSUE TITLE
Root instance not found when using with Vue 2.7

### ISSUE THREAD

**Issue by chanlito** [Akryum/vue-apollo#1377]
Error in setup: "Error: Instance $root not found"

![image](https://user-images.githubusercontent.com/15667259/176995485-24024381-762a-4bf5-b2d2-59da1f1b74b4.png)

Most likely cause by the following:

https://github.com/vuejs/apollo/blob/757e45cac05e860c0a0cc6d1c513545df4009c72/packages/vue-apollo-composable/src/util/loadingTracking.ts#L15

It should be ` const vm = getCurrentInstance().proxy;`

**Comment by watsuyo** [comment]
I'm facing the same problem too.

**Comment by ChadLefort** [comment]
Also running into this issue and preventing a project I'm working on to upgrading to vue 2.7. I tested out the change @chanlito has mentioned and can confirm that fixed the issue for me.

**Comment by jeremysq** [comment]
Any update on this being updated in an official release? I also have a project that requires Vue 2.7, as the recent Nuxt composition API update depends on it, and usage of the @nuxtjs/apollo module is required, which utilizes vue/apollo-composable in order to function in the composition API.
