### ISSUE TITLE
Reactive Variables with 'cache-first' not working in new version

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#138]
I recently upgraded to the latest client 2.0. But after that reactive queries are not working. However, this is the case only for `cache-first`. For `network-only` its working. I think there is a bug in the new version. Looks like it can't read from cache

**Comment by gijo-varghese** [comment]
Sorry it was a error from my side

**Comment by gijo-varghese** [comment]
@Akryum I think its a bug with the latest version, after upgrade to v2. 

The query below was working fine. But after upgrading, it's not working anymore
```
apollo: {
    user: {
      query: USER,
      variables() {
        return {
          id: this.$route.params.user_id
        }
      },
      fetchPolicy: 'cache-first' // If I change it to 'network-only' its works. But using devtools I found that the required data is already there
    }
  }
```

**Comment by Akryum** [comment]
Do you have a reproduction to share?

**Comment by gijo-varghese** [comment]
@Akryum mine is a little big code base and it's in localhost. So have to host 3 projects in order to show it to you

**Comment by Akryum** [comment]
Well, you don't have to share your entire project, but if you can, it would be great to have a minimal reproduction of the issue in a separate repository (or zip).

**Comment by gijo-varghese** [comment]
@Akryum ok. I'll create a simple repo and send it to you soon

**Comment by gijo-varghese** [comment]
@Akryum Its think its not a problem with the new version. Something wrong in my code. I'm getting an error when I read from cache:
`vue-apollo.esm.js?ebd5:2812 Missing page attribute on result {Symbol(id): "ROOT_QUERY"}`

What does this mean? 
Can I have more than one ROOT_QUERY?

**Comment by gijo-varghese** [comment]
@Akryum I've created for you: https://github.com/gijo-varghese/vue-apollo-demo
The `master` branch is with Apollo Client v1: Works Perfectly
The `apollo-client-v2` is with Apollo Client v2: Not working as expected.

**Comment by gijo-varghese** [comment]
@Akryum are you able to reproduce it? I'm using a sample API developed by Graph Cool. Not sure how long will they exists

**Comment by Akryum** [comment]
I didn't have time to check it out just yet.

Le sam. 4 nov. 2017 à 10:53, Gijo Varghese <notifications@github.com> a
écrit :

**Comment by gijo-varghese** [comment]
@Akryum can you please check it

**Comment by thomasaull** [comment]
I got the same problem, any updates on this?

**Comment by gijo-varghese** [comment]
@thomasaull try updating your packages. It's working for me now

**Comment by thomasaull** [comment]
@gijo-varghese No, unfortunately it doesn't solve the issue for me… I got an array of ids I want to filter my data with:
```
// Add 2: Works
const ids = [2]

// Add 5: Works
const ids = [2, 5]

// Remove 5: Doesn't work, my view doesn't get updates
const ids = [2]
```

This is only true if I use ´fetchPolicy: 'cache-first'` which is the default afaik. If I change it to 'cache-and-network' it does work, but it needs another request of data, which is already present…

**Comment by gijo-varghese** [comment]
Can you pls provide a link to the repo? I'll check it

**Comment by gijo-varghese** [comment]
Or try my repo: https://github.com/gijo-varghese/vue-apollo-demo (there is a branch with Apollo client v2)

**Comment by thomasaull** [comment]
I tried to create a test repo yesterday, but there this error did not occur… :/

**Comment by cnoter** [comment]
I think this is not an error.
my recommendation is this.

you need to make separate queries for both type.
one, not-using reactive variable query.
the other one, using reactive variable query.

then, with the second type of query, you need specify in apollo inmemory-cache's option
about how do you want characterize that type of query's dataIdFromObject.

for example:
__typename + id + 'reactive var'

then, you can using apollo cache as you want.

**Comment by gijo-varghese** [comment]
I left VueJS though 😐
