### ISSUE TITLE
Support Vue 2.7 in @vue/apollo-option

### ISSUE THREAD

**Issue by fabis94** [Akryum/vue-apollo#1381]
**Is your feature request related to a problem? Please describe.**
I was able to get @vue/apollo-option working in a Vue 2.7 app, but there were a few issues that I had to work around:

1. The TypeScript types were off, I had to create my own, since the ones in @vue/apollo-option only work with Vue 3. For anyone interested, my type augmentation file looks like this:

```ts
// vue-apollo-options.d.ts
import Vue from 'vue'
import { CombinedVueInstance } from 'vue/types/vue'

import { ApolloProvider } from '@vue/apollo-option'
import { DollarApollo } from '@vue/apollo-option/types/vue-apollo'
import { VueApolloComponentOptions } from '@vue/apollo-option/types/options'

type DataDef<Data, Props, V> = Data | ((this: Readonly<Props> & V) => Data)

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue, Data, Methods, Computed, PropsDef, Props> {
    apolloProvider?: ApolloProvider
    apollo?: VueApolloComponentOptions<
      Data extends DataDef<infer D, any, any>
        ? CombinedVueInstance<V, D, Methods, Computed, Props>
        : CombinedVueInstance<V, Data, Methods, Computed, Props>
    >
  }
}

declare module 'vue/types/vue' {
  interface Vue {
    $apolloProvider: ApolloProvider
    $apollo: DollarApollo<this>
  }
}
```

2. Vue 2.7 doesn't support the `app.use(apolloProvider)` style installation process used by @vue/apollo-option and Vue 3. That said, I was able to successfully install it and get around errors with this kind of installation:

```js
import Vue from 'vue'
import {createApolloProvider} from '@vue/apollo-option'

const apolloProvider = createApolloProvider(...)
Vue.config.globalProperties = Vue.config.globalProperties || {}
Vue.prototype.$apolloProvider = apolloProvider
apolloProvider.install(Vue)
```

**Describe the solution you'd like**
It would be great if @vue/apollo-options would be updated to officially support Vue 2.7 without needing to do any workarounds. Even with the current workarounds, there are no guarantees that further versions of the package will work with Vue 2.7, so official support would give us that guarantee.

**Describe alternatives you've considered**
See my workarounds above

**Comment by Akryum** [comment]
Why not trying `vue-apollo` which is for Vue 2? `@vue/apollo-option` is for Vue 3.
