### ISSUE TITLE
useLazyQuery requires the document again when calling `load`

### ISSUE THREAD

**Issue by TheDutchCoder** [Akryum/vue-apollo#1386]
**Describe the bug**
When destructuring `load` from `useLazyzQuery`, you need to provide the query _again_ for some reason, eventhough it should already be provided.

Example:
```ts
const { load } = useLazyQuery<GetCollection, GetCollectionVariables>(GET_COLLECTION)

const doThing = async () => {
  load({ id: '1' }) // Error, because the first argument is the document, even though it's already passed into `useLazyQuery`
}

// This works
const doOtherThing = async () => {
  load(GET_COLLECTION, { id: '1' })
}
```

**To Reproduce**
1. Destructure `load` from `useLazyQuery` with a provided document
2. Call load in some secondary function with just the variables
3. You should see an error in your IDE, because `document` is the first argument

**Expected behavior**
`load` to already know the document (as it's passed into `useLazyQyery`) and just be able to call it with variables, just like you do with mutations.

**Versions**
vue: 3.2.36
vue-apollo: 4.0.0-alpha.16
@apollo/client: 3.5.10

**Comment by haaah** [comment]
i am facing the same issue as well, is this the intended behaviour that we need to import document on the callback function again? 

versions
"graphql": "^16.6.0",
"@apollo/client": "^3.7.0",
"@vue/apollo-composable": "^4.0.0-alpha.19",

**Comment by Dykmi** [comment]
even though you have provide document at useLazyQuery ,you should still pass a null to load , example ： load(null,{ id: "1" })

**Comment by haaah** [comment]
Thanks @Dykmi 
it works, but i do get a typescript warning of 

`Argument of type 'null' is not assignable to parameter of type 'DocumentCode | undefined`

I replace null with undefined
