### ISSUE TITLE
readFragment vs normal query for cached data

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#139]
I need to retrieve some data inside a component. The result is already in the cache. I've splitted the main query into fragments. So both methods are working. Which is the best approach, `query with cache-only `or `readFragment`?

**normal query with 'cache-only'**
Pros: reactive variables, $loadingkey
Cons: throws error in inner component till the main query has finished

**readFragment**
Pros: No errors
Cons: No $loadinKey, have to write 'watcher' to implement 'reactivity'

**Comment by Samuell1** [comment]
Reading fragments are only good if you want change and save cache for getting data from cache is best using queries

**Comment by gijo-varghese** [comment]
@Samuell1 yes, I've to update the cache a lot!

**Comment by Akryum** [comment]
You should use normal queries (the default `cache-first` fetch policy is fine) with fragments inside the GraphQL documents. [Here is a great read](https://blog.manifold.co/graphql-fragments-are-the-best-match-for-ui-components-72b8f61c20fe) about fragments.

**Comment by gijo-varghese** [comment]
@Akryum but inside the components, I don't want to user 'cahce-first', the required data is going to load in a second by the result of a root query. So cache first may create additional network request. So I should use 'cache-only'. ReadFragment also do the same job right, read only from cache!

**Comment by Akryum** [comment]
Do you have examples of your queries?

**Comment by gijo-varghese** [comment]
It's little to show as a code. I'll tell you my scenario. Consider I'm building a chat application like Slack.
There are teams, teams contain user, users have messages, profile etc etc..

The main root query may look like this:
```
{
  customer(id:1) {
    teams {
      id
      name {
        users {
          id
          name
          message {
            id
            message
            time
          }
        }
      }
    }
  }
}
```

And I've several components like: TeamList.vue, UserList.vue, Messages.vue, Profile.vue etc.

Basically, in these components, I'm going to display the content that is fetched from the main query

**Comment by Akryum** [comment]
Use normal queries in the components, and call the big query with all the fields in a parent component.

I made a complete example [here](https://codesandbox.io/s/vq2ypzzrl7) ([server](https://launchpad.graphql.com/v95849ll3)). The important part is in `apollo.js`:

```js
const dataIdFromObject = object => `${object.__typename}:${object.id}`

const cache = new InMemoryCache({
  cacheResolvers: {
    Query: {
      customer: (root, { id }) => toIdValue(dataIdFromObject({ __typename: 'Customer', id })),
      team: (root, { id }) => toIdValue(dataIdFromObject({ __typename: 'Team', id })),
    },
  },
  dataIdFromObject,
})
```

See [Query splitting](https://www.apollographql.com/docs/react/recipes/query-splitting.html) for more info.

Additionally, you can use [fragments](https://www.apollographql.com/docs/react/recipes/webpack.html#Fragments) to organize this in a better way (I didn't do it in the example).
