### ISSUE TITLE
Bug in usage outside of setup?

### ISSUE THREAD

**Issue by xvaara** [Akryum/vue-apollo#1412]
I get `Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.` with the latest, and it works on alpha-16.

Is it not supposed to work, or is the newer version buggy?

### Discussed in https://github.com/vuejs/apollo/discussions/1410

<div type='discussions-op-text'>

<sup>Originally posted by **xvaara** September 16, 2022</sup>
so I have a codebase with graphql-codegen which wraps the queries in functions...
 ```
const { resolveClient } = useApolloClient();
      const client = resolveClient();

provideApolloClients({ myCustomClientId: client })(() => {
    const { onResult: onCurrentuserResult } = useCurrentUserUpdatedSubscription(() => ({
      enabled: this.$state.loggedIn,
      clientId: "myCustomClientId"
    }));
....
})
```
and i get `Error: Apollo client with id myCustomClientId not found. Use provideApolloClient() if you are outside of a component setup.`

It's inside a pinia action. It worked with 4.0.0-alpha.16 without the provideApolloClients in pinia, but with .19 it complains the same but with id default.

How is this supposed to work now?

I've downgraded to alpha.16 for now.
</div>

**Comment by websitevirtuoso** [comment]
To get ApolloClient instance I have to define what to get. 
```
const defaultApolloClient = useApolloClient('default').client
```
But I have 2 apollo instances. not sure if it helps. But I use apollo in pure functions and I am on v19

**Comment by xvaara** [comment]
Classical pebkac-problem. I didn't check that I upgraded the module also in a different package in my yarn workspace. So the problem was that build included two versions, and they conflicted. It worked with dev server, so I was confused and miffed it didn't work in production.
