### ISSUE TITLE
package resolve with yarn fails on 3.0.0-alpha.2

### ISSUE THREAD

**Issue by dohomi** [Akryum/vue-apollo#142]
@Akryum is it possible that there is a type in the last vue-apollo 3 alpha.2? If I try to install the package with yarn then I receive 
``` 
> Error: Error 500 from http://10.100.51.20/vue-apollo/-/vue-apollo-3.0.0-alpha.2.tar
```
Inside of your releases it also states `alpha.2next.tar` but I think on npm its without the next.

**Comment by Akryum** [comment]
Please try the latest release.
