### ISSUE TITLE
📝 DOCS: Missing import for `apolloClient`

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Akryum/vue-apollo#1441]
On the setup page there is no indicator where the `apolloClient` actually comes from.

https://github.com/vuejs/apollo/blob/372892855d76622128ac560e8fadc689c50675bc/packages/docs/src/guide-composable/setup.md?plain=1#L48

**Comment by Akryum** [comment]
https://github.com/vuejs/apollo/blob/372892855d76622128ac560e8fadc689c50675bc/packages/docs/src/guide-composable/setup.md?plain=1#L3
