### ISSUE TITLE
useLazyQuery doesn't work again after first load called

### ISSUE THREAD

**Issue by xxBingoBongoxx** [Akryum/vue-apollo#1445]
**Describe the bug**
When destructuring `load` from `useLazyzQuery` and calling it once, it doesn't work anymore.

**To Reproduce**
1. Destructure `load` from `useLazyQuery` with a provided document, variables
2. Bind to let's say @click event of button and call it once
3. After clicking the second, third... time you should see it doesn't invoke anymore

**Expected behavior**
To be able call `load` more than once. 

**Versions**
vue: "^3.2.13",
@vue/apollo-composable: "^4.0.0-alpha.19",
@apollo/client: "^3.6.9",

**Comment by hahn-kev** [comment]
I believe this is by design. When using load it'll only call the API again if the variables have changed. I believe you want to use `refetch` instead. Load is setup so that you can call it a bunch of times but if it's already loaded then it won't load again, just the first time.
