### ISSUE TITLE
Unsubscribe wit useSubscription

### ISSUE THREAD

**Issue by VaclavS16** [Akryum/vue-apollo#1446]
Hello,
I'am using useSubscription with composition api, but I miss the opportunity to unsubscribe. Or is there some way to do it?

**Comment by dominikklein** [comment]
When I see it correctly in the documentation you can use the enabled flag to disable a subscription: https://v4.apollo.vuejs.org/guide-composable/subscription.html#disable-a-subscription
But seems to be that this is not working correctly at the moment, at least there is this comment in the code:

```
    // @TODO doesn't fully work yet
    // enabled,
```

Another way would be to use the `stop` function which is returned from the composable call. This `stop` function is also used during unmount, so should be a save way.

**Comment by Akryum** [comment]
You can either use the `enabled` option or call `stop` which is returned by `useSubscription`.

**Comment by Akryum** [comment]
> But seems to be that this is not working correctly at the moment

This refers to this:

```js
const { enabled } = useSubscription()
enabled.value = false
```

**Comment by VaclavS16** [comment]
Thank you for help
