### ISSUE TITLE
Outdated documentation for `useResult`

### ISSUE THREAD

**Issue by ramonwenger** [Akryum/vue-apollo#1453]
According to the [documentation](https://v4.apollo.vuejs.org/guide-composable/query.html#useresult) for the composable API of Vue Apollo, one is supposed to use `useResult`. According to the last committed change to the mardown readme file, this should no longer be used, see [here](https://github.com/vuejs/apollo/commit/2e65263329fa8c9d30cd681778bf7a8fcc22bfed).

The documentation page seems to just be outdated, I suspect the process of updating it should be simple. Can I help somehow to make the change on the documentation page?

**Comment by bmulholland** [comment]
I came here to file the same bug. The docs [still suggest useResult](https://v4.apollo.vuejs.org/guide-composable/query.html#useresult), but then TS tells me it's deprecated? Either way, something's outdated, so I don't think this is completed.
