### ISSUE TITLE
SSR error - "SyntaxError: Unexpected token 'export'" with @vue/apollo-option@4.0.0-beta.4

### ISSUE THREAD

**Issue by bryanpackman** [Akryum/vue-apollo#1469]
**Describe the bug**
I get the following error message in the node environment with `@vue/apollo-option@4.0.0-beta.4`

```
(node:70395) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
12:02:02 PM [vite] Error when evaluating SSR module /src/apollo/apollo.ts: failed to import "@vue/apollo-option"

12:02:02 PM [vite] Error when evaluating SSR module /src/apollo/main.ts:

12:02:02 PM [vite] Error when evaluating SSR module /src/apollo/entry-server.ts:

/Users/packman/code/behance/sandbox/gql-cache-prototypes/node_modules/@vue/apollo-option/dist/vue-apollo-option.esm.js:1500
export { ApolloProvider, createApolloProvider };
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1195:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

**This bug only happens on 4.0.0-beta.4. It works fine on 4.0.0-beta.2**

**Versions**
vue: 3.2.47
@vue/apollo-option: 4.0.0-beta.4,
@apollo/client: 3.7.11

**Additional Context**
I am importing `entry-server.ts` with `vite.ssrLoadModule`

**Comment by bryanpackman** [comment]
This error also happens with @vue/apollo-ssr@4.0.0-beta.4

**Comment by Olli1080** [comment]
Workaround that works for me is to insert "type": "module" into the package.json and prefixing the exports with "./"
```
...
"type": "module",
"exports": {
    ".": {
      "types": "./dist/esm/index.d.ts",
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    },
    "./*": "./*"
  },
...
```
Also changeing from
`import * as serializeJs from 'serialize-javascript';`
to
`import serializeJs from 'serialize-javascript';`
in the esm/index.js

**Comment by itpropro** [comment]
Is there a fix planned for the next beta-5, rc or major release @Akryum ?

**Comment by raymondtri** [comment]
I'm still experiencing issues directly related to esm imports with this package. It seems to only work when the steps above (https://github.com/vuejs/apollo/issues/1469#issuecomment-1494960430) are manually changed in node_modules.
