### ISSUE TITLE
`useQuery` and `useLazyQuery` should also return a promise

### ISSUE THREAD

**Issue by ibex-david** [Akryum/vue-apollo#1486]
The problem is that i still want to wait for a specific request made by the lazy query.

```js
// at my store:
const { load, loading, error, result } = useLazyQuery()

// inside the component:
const data = await load()
```

Because `load` doesn't return the current request promise, many reactive variables needed to be watched unwillingly.

### The suggested solution
`load()` should return the promise to the current request.
also every other fetching function like `rerun` etc.

**Comment by Csszabi98** [comment]
For now you can do:

```typescript
function waitApolloQuery({ onResult, onError }) {
  return new Promise((res, rej) => {
    const { off: offResult } = onResult((result) => {
      offResult()
      res(result)
    })
    const { off: offError } = onError((error) => {
      offError()
      rej(error)
    })
  })
}

const query = useLazyQuery()

try {
  query.load()
  const data = await waitApolloQuery(query)
} catch(e) {
  // Handle error
}

```

**Comment by sschneider-ihre-pvs** [comment]
> For now you can do:
> 
> ```ts
> function waitApolloQuery({ onResult, onError }) {
>   return new Promise((res, rej) => {
>     const { off: offResult } = onResult((result) => {
>       offResult()
>       res(result)
>     })
>     const { off: offError } = onError((error) => {
>       offError()
>       rej(error)
>     })
>   })
> }
> 
> const query = useLazyQuery()
> 
> try {
>   query.load()
>   const data = await waitApolloQuery(query)
> } catch(e) {
>   // Handle error
> }
> ```
`{loading: true, networkStatus: 1, partial: true}` doesn't seem to work

**Comment by tcitworld** [comment]
You can make sure the promise is only resolved when the query is no longer loading. 
```diff
const { off: offResult } = onResult((result) => {
+     if (result.loading === false) {
        offResult()
        res(result)
+     }
    })
```

**Comment by Csszabi98** [comment]
@sschneider-ihre-pvs That is a different issue, `useLazyQuery` does not invoke `onServerPrefetch` in this case. See: https://github.com/vuejs/apollo/issues/1495. You can use the mentioned workaround to fix that.

Also, this is the final implementation of waitForApolloQuery that ended up working for me:

```
import { ApolloError, OperationVariables } from '@apollo/client';
import { UseQueryReturn } from '@vue/apollo-composable';

export function waitForApolloQuery<TResult, TVariables extends OperationVariables>({
  onResult,
  onError,
  forceDisabled,
}: Pick<UseQueryReturn<TResult, TVariables>, 'onResult' | 'onError' | 'forceDisabled'>) {
  if (forceDisabled.value) {
    return Promise.resolve<TResult | ApolloError | undefined>(undefined);
  }

  return new Promise<TResult | ApolloError | undefined>((res) => {
    const { off: offResult } = onResult((result) => {
      res(result.data);
      setTimeout(offResult, 1);
    });
    const { off: offError } = onError((error) => {
      res(error);
      setTimeout(offError, 1);
    });
  });
}

```

Usage of `setTimeout` is required if you have multiple async functions waiting for the same Apollo query. (onResult and onError are invoked inside of a for cycle and synchronous removal of the event handlers will affect their invocation order, leading to not all handlers being called)
