### ISSUE TITLE
How to detect Web socket failure?

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#149]
I use Graphql Subscriptions for real-time events. It's a chat application. When the server goes down or the internet goes disconnect it will throw an error in the console.

Is there any way to detect that show user a custom message/notification? Any hooks/events for that?

`VM4661:164 WebSocket connection to 'ws://localhost:5000/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by Tobino** [comment]
Hello,

When you create your `SubscriptionClient` with `subscriptions-transport-ws`.
You can attach listener on client to get event `connected`, `reconnected`, `disconnected`…

Example:

```javascript
import { SubscriptionClient } from 'subscriptions-transport-ws';
const webSocketNetworkInterface = new SubscriptionClient(process.env.WS_URL, {
	reconnect: true
});

webSocketNetworkInterface.onDisconnected(() => {
	console.log('Disconnected');
});
```

Then you shoud be able to implement the logic you want.

Source: https://github.com/apollographql/subscriptions-transport-ws#oneventname-callback-thiscontext--function

**Comment by gijo-varghese** [comment]
@Tobino awesome! Thanks :) I'll try it

**Comment by mmintel** [comment]
Hi there, I think since last year the implementation of the subscription client changed quite a bit, how would be the current best practice to implement this?

**Comment by Tobino** [comment]
Hi @mmintel,
`subscriptions-transport-ws` hasn't change that much. You could still use this implementation.
I don't think `apollo-link-ws` change anything.
https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-ws
