### ISSUE TITLE
TS warning for "enabled" as Ref

### ISSUE THREAD

**Issue by tsiotska** [Akryum/vue-apollo#1491]
**Describe the bug**
TS warning is shown if you use "enabled" option as Ref

**Unexpected number of arguments** ❗ 

![image](https://github.com/vuejs/apollo/assets/51022409/43ba8aaa-b0db-4dc6-908b-18430043de8c)

```
const isAdmin = computed(() => store.user.state.userRoles.includes("admin"))
useQuery(USERS_QUERY, { variables }, () => ({ enabled: isAdmin }))
```

**Comment by stephenjason89** [comment]
I was about to create the same issue.
as of the moment (4.0.0 beta8) the useQuery declaration file says it should be boolean
<img width="270" alt="image" src="https://github.com/vuejs/apollo/assets/3810177/35ed9de6-0a8b-47a1-aeaa-e41035aa5f4a">

However, the type should be a Ref<boolean>

as mentioned in the docs
<img width="761" alt="image" src="https://github.com/vuejs/apollo/assets/3810177/ab9e6423-9c54-456a-9245-bd0dfc729a4a">

**Comment by kylekz** [comment]
Does `enabled` even work? Any query I explicitly disable still executes.

```ts
  const enableQuery = ref(false);
  const { onResult } = useQuery<{ someData: SomeData[] }>(
    SomeQuery,
    () => ({
      someParam: someRef.value,
    }),
    () => ({ enabled: enableQuery })
  );
```

**Comment by stephenjason89** [comment]
> 

It works, don't make it a function
```
const enableQuery = ref(false);
  const { onResult } = useQuery<{ someData: SomeData[] }>(
    SomeQuery,
    () => ({
      someParam: someRef.value,
    }),
    { enabled: enableQuery }
  );
  ```

**Comment by tsiotska** [comment]
I have opened the PR for this. "Enabled" works as expected when assigning Ref or Boolean, but to remove warning i just extended missing type.
https://github.com/vuejs/apollo/pull/1492/files#diff-6bc7e9678664512fca6286f9a45bc6bdb7f3e02b733c2954ff1fb8210e2f87deR43
