### ISSUE TITLE
Loading does not work

### ISSUE THREAD

**Issue by R0N1n-dev** [Akryum/vue-apollo#1501]
**Describe the bug**
The Loading prop on the result object doesnt seem to work.
On making a query, the 'Loading' does not show up. Instead during the query, the 'no-result' slot renders instead.

**To Reproduce**
1. Install apollo and configure
2. use Apollo queries components according to he examples on documentation page
3. Make query

**Expected behavior**
Whatever is in the 'loading' slot show on making a query before the result is displayed 

**Versions**
vue: 3.3.2
vue-apollo: 4.0.0-beta.5
@apollo/client: 3.8.1

**Additional context**
```js
<template v-slot="{ result: { loading, error, data } }">
  <!-- Loading -->
  <div v-if="loading" class="loading apollo">Loading...</div>

  <!-- Error -->
  <div v-else-if="error" class="error apollo">An error occurred</div>

  <!-- Result -->
  <div v-else-if="data" class="result apollo">{{ data.hello }}</div>

  <!-- No result -->
  <div v-else class="no-result apollo">No result :(</div>
</template>
```

**Comment by websitevirtuoso** [comment]
Try to update your issue with using latest version. If problem still persist I will try to help you

**Comment by R0N1n-dev** [comment]
Same thing. No change. Same issue

**Comment by R0N1n-dev** [comment]
Fuck you guys You are useless.

**Comment by R0N1n-dev** [comment]
Fuck you guys You are useless.
