### ISSUE TITLE
[Documentation] Composition API + Options API Configuration, how to make it work together? 

### ISSUE THREAD

**Issue by yarotskiu** [Akryum/vue-apollo#1539]
**Description**
I am working in Vue project which is quite big 
Recenlty it was upgraded to work with Vue 3 and all of the components were developed in Options API 

We are starting to develop new components with Composition API and would like to migrate step by step
But we can understand how to configure Apollo once, so it works with both type of components 

Regarding documentation in Options API you need to provide ApolloClient through provider: 
```javascript
const apolloClient = new ApolloClient({
  cache,
  uri: 'http://localhost:4042/graphql',
})

const apolloProvider = createApolloProvider({
  defaultClient: apolloClient,
})

app.use(apolloProvider)
``` 

Regarding documentation in Composition API you don't need provider and you can provide it by your self with `DefaultApolloClient` like below: 
```javascript
// Same apolloClient
const app = new Vue({
  setup () {
    provide(DefaultApolloClient, apolloClient)
  },

  render: h => h(App),
})
```
Or, as we did, you can use:

```javascript
// Same apolloClient
app.provide(DefaultApolloClient, apolloClient);
```

BUT, if you want to use different API, you need to provide ApolloClient instance in BOTH ways. 

It doesn't work in Composition API if I remove `app.provide(DefaultApolloClient, apolloClient)` 
It doesn't work in Options         API if I remove `app.use(apolloProvider)`

I should admit that this works if it was configured both ways, but is that good practice?
How can I configure it once and be sure it's supported in both API? 

Documentation is, unfortunately, not clear on that topic. 

**Expected behavior**
Configure it once and expect it will work in Composition API and Options API components

**Versions**
```
"vue": "^3.4.19",
"@vue/apollo-composable": "^4.0.1",
"@vue/apollo-option": "^4.0.0",
```

**Comment by nickmessing** [comment]
Since composition and options were designed basically "isolated" from each other, it's okay if you use both provides.

P.S. As an option, you can add `setup` method in options API to use composition inside options-based component.

**Comment by yarotskiu** [comment]
Thank you for the explanation!
