### ISSUE TITLE
this in updateQuery 

### ISSUE THREAD

**Issue by shtse8** [Akryum/vue-apollo#154]
I want to access some properties of the component in `updateQuery`, but when I'm calliing this in `updateQuery` of Subscription, the `this` is referring to the object itself. How can I access the component this in the `updateQuery`?

```js
subscribeToMore: {
  variables () {
    console.log('variables.this', this) // it's correct, vue component
    return {}
  },
  updateQuery (result, { subscriptionData }) {
    console.log('updateQuery.this', this) // it's wrong, just the object itself, I guess missing binding this
  }
}
```

**Comment by duyduc-nguyen** [comment]
You have to use arrow func like in the example:
`updateQuery: (previousResult, { subscriptionData }) => {
        // Here, return the new result from the previous with the new data
  },`

**Comment by shtse8** [comment]
@duyduc-nguyen it can't because the arrow function this is just pointing to the outside object instead of the vm instance.

**Comment by Samuell1** [comment]
You can access it, as you can see in this example https://github.com/Akryum/devfest-nantes-2017/blob/apollo2/app/src/components/PageHome.vue#L94

**Comment by shtse8** [comment]
@Samuell1  the `this` just access the https://github.com/Akryum/devfest-nantes-2017/blob/apollo2/app/src/components/PageHome.vue#L87 object. but not the `vm`.

**Comment by razorabhu1995** [comment]
@Samuell1 how did you fix it sir?

**Comment by deathg0d** [comment]
Has this been fixed? Still cannot access `this`, which show as undefined. (`3.0.0-beta.29`)

**Comment by pascoual** [comment]
Same for me.

**Comment by garcianavalon** [comment]
I can confirm that using arrow function does not work (`this` will be undefined) but using a function does work `updateQuery (result, { subscriptionData }) `

The problem is that [the docs show an arrow function](https://vue-apollo.netlify.com/guide/apollo/subscriptions.html#subscribe-to-more), which leads many to this error. A quick fix would be to update the docs to change the example, so copy-paste is safer 😆
