### ISSUE TITLE
useQuery is crashing if clientId is set in the options

### ISSUE THREAD

**Issue by tukanoidd** [Akryum/vue-apollo#1557]
**Describe the bug**
I'm working on a web app. I need to mock graphql requests in those tests. I use mock-apollo-client with @vue/apollo-composables. It only breaks in tests, not dev/production builds, and only when clientId is set manually (including literal "default" value) in the useQuery call.

**Expected behavior**
It just works?

**Versions**
vue: ^3.3.13
vue-apollo: ^4.0.1
@apollo/client: ^3.9.4
@vue/apollo-composable: ^4.0.1

**Additional context**
After hours of searching for information and debuggin the code, I think I found the source of the issue: https://github.com/vuejs/apollo/blob/6fa46ab12271134dbe74c57586caf00e66619a90/packages/vue-apollo-composable/src/useApolloClient.ts#L46 from the code it's see that by default it just sets the clients dict to null and for some reason decides to use that first to see if it can find the client. But because providedApolloClients is null, the resolveClientWithId function throws an error (https://github.com/vuejs/apollo/blob/6fa46ab12271134dbe74c57586caf00e66619a90/packages/vue-apollo-composable/src/useApolloClient.ts#L27), making this check (https://github.com/vuejs/apollo/blob/6fa46ab12271134dbe74c57586caf00e66619a90/packages/vue-apollo-composable/src/useApolloClient.ts#L52) obsolete and not going forward with checking savedCurrentClients, which provideApolloClients actually sets, while resolveDefaultClient, which gets called in cases where clientId isn't defined, doesnt throw but instead just uses undefined (https://github.com/vuejs/apollo/blob/6fa46ab12271134dbe74c57586caf00e66619a90/packages/vue-apollo-composable/src/useApolloClient.ts#L21) and allows the logic to continue with accessing savedCurrentClients (https://github.com/vuejs/apollo/blob/6fa46ab12271134dbe74c57586caf00e66619a90/packages/vue-apollo-composable/src/useApolloClient.ts#L61), where it ultimately gets the default client.

**Proposed solution**
Don't throw in resolveClientWithId and use a similar hack like in resolveDefaultClient, or throw the error after both resolvers fail, not after the first one. 

EDIT: pretty sure it's the same issue as [here](https://github.com/vuejs/apollo/issues/1494), although I might be wrong

**Comment by svelue** [comment]
I have the same problem using
@apollo/client 3.11.4
@vue/composable 4.0.2
vue 3.4.37

It seems like everything is working as expected with at least vue 3.4.26 to I'm not sure if this is an apollo or vue issue?!

**Comment by tukanoidd** [comment]
> I have the same problem using
> @apollo/client 3.11.4
> @vue/composable 4.0.2
> vue 3.4.37
> 
> It seems like everything is working as expected with at least vue 3.4.26 to I'm not sure if this is an apollo or vue issue?!

Hmmm, interesting, I'm on vacation currently, but will relay this info to my coworkers.

**Comment by tukanoidd** [comment]
> I have the same problem using
> @apollo/client 3.11.4
> @vue/composable 4.0.2
> vue 3.4.37
> 
> It seems like everything is working as expected with at least vue 3.4.26 to I'm not sure if this is an apollo or vue issue?!

Hmmm, interesting, I'm on vacation currently, but will relay this info to my coworkers.
