### ISSUE TITLE
Subscribe to Same Subscription with Multiple ids?

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#156]
I have a subscription like this:
```
$subscribe: {
      newMessage: {
        query: NEW_MESSAGE,
        variables() {
          return {
            page_id: this.page[0].id
          };
        }
      },
}
```
Basically it subscribes to new message in a 'page'.  Is it possible to add multiple subscription? The subscription will be same, but I want to subscribe to page[1].id, page[2].id etc (every pages inside the page's array)

**Comment by Akryum** [comment]
Use an array parameter?

**Comment by gijo-varghese** [comment]
@Akryum I didn't any documentation that I can look into?

**Comment by gijo-varghese** [comment]
@Akryum ok

So instead of:
`newMessage(page_id: ID!): Message`

this one?
`newMessage(page_id: [ID]!): Message`

Am I correct?

**Comment by Akryum** [comment]
Yes.

**Comment by gijo-varghese** [comment]
@Akryum Thanks. I think it will work for me. Also any other way (just curious ;)?

**Comment by Akryum** [comment]
I think it's the best way. 👍
