### ISSUE TITLE
Multiple pagination inside same query

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#157]
I have a query like this:
```
{
  customer(id: "1") {
    id
    name
    pic
    pages {
      id
      users (offset: 0, limit: 10) {
        id
        first_name
        last_name
      }
    }
  }
}
```
Each Customer have multiple pages and each page have multiple users.

My doubt is how I can do pagination for 'users'. For eg, if the customer has selected the first page, and he has to load the next 10 users? I can set the offset to 10, but it will load the users from all other pages too, right?

**Comment by gijo-varghese** [comment]
@Akryum can you help me?

**Comment by Akryum** [comment]
> but it will load the users from all other pages too, right?

Yes. For this specific use case, I would split the queries in two and use the `users` part of the query inside a sub-component (that displays the users).

**Comment by gijo-varghese** [comment]
@Akryum ok. But that will create multiple requests, right?

**Comment by Akryum** [comment]
You can include the first batch of users in the initial query like you did in your op.  Then you can use query-splitting with a query like this in the sub-component:

```gql
{
  page (id: $id) {
    id
    users (offset: 0, limit: 10) {
      id
      first_name
      last_name
    }
  }
}
```

See: https://github.com/Akryum/vue-apollo/issues/139#issuecomment-341279148

**Comment by gijo-varghese** [comment]
hmmm. I was trying to reduce the requests. Because the same case exists for multiple scenarios. Anyway Thanks a lot :+1:

**Comment by Akryum** [comment]
If you do like I wrote, you will have one initial request with the 10 first users for the pages of the customer, then in the sub-component you will have this evaluated query:

```gql
{
  page (id: 'foo') {
    id
    users (offset: 0, limit: 10) {
      id
      first_name
      last_name
    }
  }
}
```

If you setup the cache resolvers correctly, you can tell apollo to use the cached values form the previous big query. If offset changes, it will do an additional request.

Example cache resolver (untested):

```js
Customer: {
  page: (customer, { id, offset }) => toIdValue(`CustomerPage:${id}:${offset}`),
},
```

**Comment by gijo-varghese** [comment]
What are cache resolvers? Any detailed docs for it?

**Comment by Akryum** [comment]
You also need to change `dataIdFromObject` to account for this case:

```js
const dataIdFields = [
  '__typename',
  'id',
  'offset',
]

const dataIdFromObject = object => dataIdFields.reduce((id, field) => {
  const value = object[field]
  if (value) id += ':' + value
  return id
}, '')

const cache = new InMemoryCache({
  cacheResolvers: {
    Page: {
      users: (page, { offset }) => toIdValue(dataIdFromObject({__typename: 'CustomerPageUsers', id: page.id, offset}),
    },
  },
  dataIdFromObject,
})

```

> What are cache resolvers? Any detailed docs for it?

https://github.com/Akryum/vue-apollo/issues/139#issuecomment-341279148

**Comment by gijo-varghese** [comment]
This is the new Apollo client, right? version 2?

**Comment by Akryum** [comment]
> This is the new Apollo client, right? version 2?

Yes.

**Comment by gijo-varghese** [comment]
I'm still stuck in v1, because I can't upgrade to v2 due to a bug: https://github.com/Akryum/vue-apollo/issues/138
