### ISSUE TITLE
Access Vuex in apollo client config

### ISSUE THREAD

**Issue by pSchaub** [Akryum/vue-apollo#162]
I want to have access to vuex inside the apollo client config.

Reason:
I want to check for network errors globally. If a specific network error occurs I want to show the user a message that the server is currently offline / not working as expected.

I think it would be the best to set a value to the vuex store to enable the error message.
Or do you have another good idea?

Notice: I currently use `nuxt` but this issue is also relevant for default vue.

Idea (inside my apollo client config):
```
const logoutLink = onError(errors => {
    if (errors.networkError === 'TypeError: Failed to fetch') {
      window.$nuxt.$store.commit('SET_SERVER_DOWN', true)
    }
}
```

Issue with the above idea: It uses `window` - so it will not be compatible with SSR.
I need a solution to access vuex without accessing it through `window`.

**Comment by Samuell1** [comment]
If you using nuxtjs you can access store from ctx

**Comment by pSchaub** [comment]
Thank you. It works.

```
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: {authorization: `Bearer ${ctx.store.state.user.token}`}
    })
    return forward(operation)
  })
```

**Comment by wackyapps** [comment]
> window.$nuxt.$store.commit('SET_SERVER_DOWN', true)



> If you using nuxtjs you can access store from ctx

@Samuell1 can you help me how to call mutation defined in vuex module names auth
