### ISSUE TITLE
Compose / Combine imported queries or mutations

### ISSUE THREAD

**Issue by pSchaub** [Akryum/vue-apollo#163]
I want to compose / combine queries or mutations.

Example:
```
  import getUserQuery from '~/apollo/queries/User'
  import allPermissionsQuery from '~/apollo/queries/AllPermissions'
```

Normally I know how to use e.g. `getUserQuery` with apollo.
But how can I combine both imported graphQL queries?

**Comment by Samuell1** [comment]
use fragments: http://graphql.org/learn/queries/#fragments
