### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by LukeusMaximus** [Akryum/vue-apollo#165]
In the readme, it is suggested that a client be created for subscriptions like this:

```
import { ApolloClient, createNetworkInterface } from 'apollo-client'
// New Imports
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws'

<snip>

// Create the apollo client with the new network interface
const apolloClient = new ApolloClient({
  networkInterface: networkInterfaceWithSubscriptions,
  connectToDevTools: true,
})
```

However, `networkInterface` is no longer a parameter of the [apollo client options](https://www.apollographql.com/docs/react/reference/index.html#ApolloClientOptions), createNetworkInterface is not an export of apollo-client, and addGraphQLSubscriptions is not an export of subscriptions-transport-ws.

I assume this is because of a recent API change to using Apollo Links. Please update your documentation to account for this change.

**Comment by Akryum** [comment]
See #150

**Comment by LukeusMaximus** [comment]
Sorry, I was unaware I was using Apollo 2.x
