### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by pSchaub** [Akryum/vue-apollo#167]
Is there a way to set the timeout (globally)? I want to set the timeout until a "failed to fetch" error happens (e.g. because the server is offline or not responding fast enough).

**Comment by ian-slq** [comment]
I have the same issue!

**Comment by 1103036128** [comment]
Could you tell me how the Apollo request timed out ? Thank you

**Comment by pSchaub** [comment]
@1103036128 You just need a server that starts the connection but needs "endless" time to respond - for example if the server takes very long to aggregate a lot of data. This may take a lot of time (e.g. more then 60 seconds).

It would be helpful to be able to specify a limit until a timeout happens.

Maybe there is already a way to do it? I don't know.

**Comment by Akryum** [comment]
This is an issue with:

- Nodejs timeout (which default to two minutes)
- Browser timeout (which is difficult to configure depending on the browser)

To work around this, you can use a Websockets-only configuration:

```js
import { ApolloClient } from 'apollo-client'
import { SubscriptionClient } from 'subscriptions-transport-ws'
import { WebSocketLink } from 'apollo-link-ws'

// Web socket
const wsClient = new SubscriptionClient(base.replace(/^https?/i, 'ws') +
endpoints.subscription, {
  reconnect: true
})

// Create the subscription websocket link
const wsLink = new WebSocketLink(wsClient)

const apolloClient = new ApolloClient({
  link: wsLink,
  cache
})
```
