### ISSUE TITLE
Adding list of fields from array

### ISSUE THREAD

**Issue by jstrika** [Akryum/vue-apollo#169]
Probably I'm not searching correctly, but I can not find any reference how build a query with a list of fields from the array. 
```
apollo: {
    books: gql`query { books {
        title
        author
      }}`
  },
```
For example, instead of defining **title** and **author** in gql string, I would like to define (add) these fields after Vue instance is mounted. Is there a method that can make this posible?

**Comment by Samuell1** [comment]
You can put inside gql query what you want with template literals
```js
const mydefinedconst = `title author`

// somewhere in your code
books {
${mydefinedconst}
}
```

**Comment by jstrika** [comment]
Thanks @Samuell1 for idea. I end up expanding on your suggestion. Here is an example for others if they are looking for similar thing:

```

export default {
  apollo: {
    UserMany () {
      return this.gqlBuildQuery('UserMany', ['name', 'age', '_id'])
    }
  },
  data () {
    return {
      UserMany: []
    }
  },
  methods: {
    gqlBuildQuery (tableName, myfields) {
      return {
        query: gql`query { ${tableName} { 
          ${myfields.join(' ')}
        }}`
      }
    }
  }
}
```
