### ISSUE TITLE
vue-apollo@2.x compatibility

### ISSUE THREAD

**Issue by ZMN8** [Akryum/vue-apollo#170]
Can't used in  the old version of system, the iphone 6s and iphone 5 throw such errors.  Whether to show that I should use the vue-apollo@1.x ? 
![_20171220104531](https://user-images.githubusercontent.com/20635903/34188752-eb6e07da-e572-11e7-8d4a-11e36f45ca1a.jpg)

**Comment by Akryum** [comment]
You need to polyfill `fetch` which is not natively supported on this browser.
