### ISSUE TITLE
how to fetch the new graphql response not cache

### ISSUE THREAD

**Issue by jianjungki** [Akryum/vue-apollo#174]
i'm building a cms using graphql and front-side using vue-apollo, always i reload, the network in chrome show nothing and the data is old.

i want the newest data from database to show, have anyone know that how to config ?

**Comment by Simskii** [comment]
If you set fetchPolicy to "network-only", apollo will not cache your data.
https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-fetchPolicy

**Comment by Akryum** [comment]
You can also use [cache-and-network](https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-fetchPolicy).
