### ISSUE TITLE
can i upload img?

### ISSUE THREAD

**Issue by wangxiangyao** [Akryum/vue-apollo#176]
How to upload img use graphql ?

**Comment by paulpdaniels** [comment]
You need to use something like: https://github.com/jaydenseric/apollo-upload-client

**Comment by wangxiangyao** [comment]
thanks !!!

**Comment by razorabhu1995** [comment]
@paulpdaniels  @wangxiangyao  Can anyone give be an example query to upload image?

**Comment by dmitry** [comment]
https://marvinrabe.de/graphql-vue-upload/
