### ISSUE TITLE
query result auto inject __typename into each schame type. when i submit a mutation with the result data, i got an error

### ISSUE THREAD

**Issue by wangxiangyao** [Akryum/vue-apollo#177]
My client-side, i query data in my component and store the result into vuex.
the data like this
![image](https://user-images.githubusercontent.com/23569474/34595478-568b78b6-f213-11e7-984d-82f402772df2.png)
then i change data and send a mutation:
![image](https://user-images.githubusercontent.com/23569474/34598060-8a57b1ca-f225-11e7-9602-169251718178.png)

![image](https://user-images.githubusercontent.com/23569474/34598032-5c08243a-f225-11e7-9876-de92af0f4de9.png)

i got an error: "__typename is not defined"
![image](https://user-images.githubusercontent.com/23569474/34598288-c6868c2e-f226-11e7-908c-984427c0f145.png)

i really didn't defined __typename at my server-side
![image](https://user-images.githubusercontent.com/23569474/34598283-bb8b5ff2-f226-11e7-8b94-584869871edd.png)

but the field "__typename" is auto_inject into the result

so what am i supposed to do ?

**Comment by wangxiangyao** [comment]
Why use __typename? and How to submit a mutation with data has property __typename?

**Comment by Samuell1** [comment]
You cant send typename, you need to clone your result to other object where you have only values that you need to send back with mutation.
