### ISSUE TITLE
When using with TypeScript, type inference not working for "this" inside query variables

### ISSUE THREAD

**Issue by ozguruysal** [Akryum/vue-apollo#178]
```js
apollo: {
  getUser: {
    query: GET_USER_QUERY,
    variables: {
      id: this.$route.params.id  // 'this' implicitly has type 'any' because it does not have a type annotation.
    },
  },
},
```

In this example above type inference is not working on `this` . TypeScript compiler complains 
> 'this' implicitly has type 'any' because it does not have a type annotation.

The workaround to fix this issue is to define `variables` property as a function that returns an object of variables:

```js
apollo: {
  getUser: {
    query: GET_USER_QUERY,
    variables() {
      return {
        id: this.$route.params.id,
      };
    },
  },
},
```
I'm not sure if this is a proper way. It would be nice to be able to use the same syntax as in the first example.

**Comment by Samuell1** [comment]
Yes, proper way is to use `variables` as function

**Comment by Akryum** [comment]
This has nothing to do with Typescript, your first code snippet is wrong even in plain Javascript. As @Samuell1 pointed out, you need to use a function. If you don't, this will be the `window` object and variables won't be reactive.

**Comment by ozguruysal** [comment]
Thank you very much both for your feedback. Absolutely my bad. I looked at https://github.com/Akryum/vue-apollo#query-with-parameters but saw that now https://github.com/Akryum/vue-apollo#reactive-parameters. Thanks again! 👍
