### ISSUE TITLE
How can I give a gql object into custom component?

### ISSUE THREAD

**Issue by AlexVasilenko** [Akryum/vue-apollo#179]
Hello! I want to create a component which get gql object and after that use this object into the custom component. 

How I try to do it:
1) I created Table component which can paint table and has next props: columns - object with configs for table and query - it's graphql Object.
2) I add graphql object into apollo: data: { query: this.query }.

Small part of my Table component: https://codepen.io/anon/pen/ppWMeE?editors=0110#anon-login

Also I try to use another way, I set a query string like props and then called gql`{this.query}`.

![2018-01-05 19-20-22](https://user-images.githubusercontent.com/6567429/34620550-80e515fa-f24e-11e7-8885-89ff4a041c09.png)

Sorry for my English. Thank you.

**Comment by Akryum** [comment]
See https://github.com/Akryum/vue-apollo#reactive-query-definition

**Comment by AlexVasilenko** [comment]
Thank you. I should have read this documentation.
