### ISSUE TITLE
Does not work with meteor "apollo" package

### ISSUE THREAD

**Issue by matteodem** [Akryum/vue-apollo#18]
Get following error:

```
http://localhost:3000/graphql 405 (Method Not Allowed)
HTTPFetchNetworkInterface.fetchFromRemoteEndpoint @ VM8112:73
(anonymous) @ VM8112:90
localhost/:1 Fetch API cannot load http://localhost:3000/graphql. Response for preflight has invalid HTTP status code 405
vue-plugin.js?3c73:207 Error sending the query undefined TypeError: Failed to fetch
```

Using https://atmospherejs.com/meteor/apollo. Any idea for why the `OPTION` request needs to be made? Or is that the apollo client that is doing that?

**Comment by Akryum** [comment]
I can't replicate this. I just tested with the latest meteor, latest apollo-client, and I could connect successfully to the meteor server apollo, and to an external graphql server.

**Comment by matteodem** [comment]
oh, I used a custom frontend (not meteorjs). But thanks for showing me an example, I'll try setting up the config similiarly to how the `apollo` package does.

**Comment by matteodem** [comment]
Try upgrading the npm packages. The problem comes up when I upgrade graphql-tools to `0.8.4`

**Comment by Akryum** [comment]
I just tested with these versions and it works:
https://github.com/Akryum/meteor-vue-component/blob/master/package.json
https://github.com/Akryum/meteor-vue-component/blob/master/.meteor/versions#L17

**Comment by matteodem** [comment]
I'll test it later today

**Comment by matteodem** [comment]
Still doesn't work. Did you already try connecting  with `apollo-client` from a custom webpack project? I can upload the project if it's not reproduceable for you

**Comment by Akryum** [comment]
Yes, I'm working on an official vuejs.org app with Webpack and vue-apollo + an Apollo server.

**Comment by Akryum** [comment]
Do you still encounter this issue?

**Comment by matteodem** [comment]
Yes... I'll upload the repository again later today and hopefully you can reproduce it.

**Comment by Akryum** [comment]
OK!

Le mar. 24 janv. 2017 17:06, Matteo De Micheli <notifications@github.com> a
écrit :

**Comment by matteodem** [comment]
here it is: https://github.com/matteodem/vue-apollo-bug

Simply go once into `code/api` and `code/web-app` and do following for each folder:

```
npm install
npm run dev
```

Both apps need to be running. The api app is the graphql endpoint and the web-app just a webpack project with vuejs. I get following error when visiting the web app url:

![error](http://i.imgur.com/zqwMuOp.png)

**Comment by matteodem** [comment]
any success?

**Comment by Akryum** [comment]
Didn't have time to try yet. ;)

**Comment by matteodem** [comment]
sure, sorry to stress you

**Comment by Akryum** [comment]
I've tried the app, with the same error. In one of my project with apollo-server, the client makes 2 requests with the OPTIONS method, with an empty response. But the meteor package rejects it, so I wonder if its internal apollo packages are up-to-date.

**Comment by Akryum** [comment]
@matteodem Did you try setting up apollo server manually?

**Comment by matteodem** [comment]
no, do you have an example of doing that with meteorjs?

**Comment by Akryum** [comment]
You can get inspiration from [this](https://github.com/apollographql/meteor-integration/blob/master/main-server.js) or maybe try to clone the meteor/apollo package and update the dependencies.

**Comment by matteodem** [comment]
This has been solved in the meantime, thanks for helping out

**Comment by ecerroni** [comment]
Just for reference I had the very same problem although I'm not using meteor. Indeed I'm using the classic vue webpack dev server and an express apollo server.

I solved my problem thanks to this post. I hope it'll help others too facing the same issue:
https://forums.meteor.com/t/solved-cors-errors-with-apollo-on-meteor-1-4x/29465
