### ISSUE TITLE
Adding Optimistic Response to a List

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#184]
I'm using optimistic UI to add an item to a list. So after calling a mutation, it adds the object to list with `id: -1`. Then I'll get the response of server with the actual id and I'll add it to the list again. So after receiving the actual data, how do we remove the optimistic response?

**Comment by Akryum** [comment]
It should do it automatically.

**Comment by gijo-varghese** [comment]
Ok. In my case I'm calling a mutation 'sendMessage' that will trigger

**Comment by gijo-varghese** [comment]
Ok. In my case I'm calling a mutation 'sendMessage' that will publish it to a subscription. So the new message will be received by all clients. Then all clients subscribed to it will receive the data and add it to the store.

Basically I want optimistic response to be added and then replace it with the message from subscription

**Comment by Akryum** [comment]
I would rather update the message list from the mutation rather than the subscription which will be more performant. You can filter out the user that made the mutation so it doesn't receive a duplicate message.

**Comment by gijo-varghese** [comment]
Ok. Thanks!
