### ISSUE TITLE
[Bug] Cached result/update gets called twice

### ISSUE THREAD

**Issue by TheCheat** [Akryum/vue-apollo#185]
When fetching cached item with fetchPolicy 'cache-first', result/update on apollo query gets called twice
Example: http://jsfiddle.net/oyejk2qL/111/

**Comment by kavalcante** [comment]
Find the same bug today...

**Comment by Lahori-Jawan** [comment]
yeah, I noticed that too.

**Comment by ffxsam** [comment]
I don't know if this is related, but when I call `this.$apollo.mutate()`, it writes to the database twice. In my Network tab in Chrome, I can see two calls to my GraphQL endpoint.

**Comment by ffxsam** [comment]
I fixed my issue by adding an optimistic response object.

**Comment by ffxsam** [comment]
Ok, adding an `optimisticResponse` property prevents two database writes. But I can still see `update()` is getting called twice. @Akryum any ideas?

**Comment by Akryum** [comment]
Add `result: result => console.log(result)` to your smart query and report back with the values.

**Comment by ffxsam** [comment]
`result` never gets called. is it supposed to, in a mutation? This is the general structure of my mutation:

```js
this.$apollo
  .mutate({
    mutation: createTrackMutation,
    variables: {
      createdAt: new Date().toISOString(),
      duration,
      name,
      userId: this.$store.state.auth.user.username,
    },
    update: (store, { data: { createTrack } }) => {
      // ...
    },
    optimisticResponse: {
      // ..
    },
    result: x => console.log('result:', x),
  })
  .then(data => {
    console.log('done!', data);
  })
  .catch(err => {
    console.log('error', err);
  });
```

I'm having multiple problems. I think it has to do with the fact that my query doesn't return an array of items:

```graphql
type Query {
  listTracks(userId: ID!, limit: Int, nextToken: String): TrackList
}

type TrackList {
  items: [Track]
  totalCount: Int!
}
```

**Comment by Akryum** [comment]
Oh sorry, didn't see this was about mutation!

**Comment by Akryum** [comment]
Maybe you could open a new issue?

**Comment by ffxsam** [comment]
Well, to be fair, I kind of hijacked the issue.. I thought it was related. The original poster's problem is with queries. But I was getting duplicate network calls. I'll open a new issue.

**Comment by Akryum** [comment]
If someone still has issues with **queries**, please reopen with the result of this:

> Add `result: result => console.log(result)` to your smart query and report back with the values.

**Comment by GlennMatthys** [comment]
Still having issues with result() being called twice (with the default fetchPolicy):

![image](https://user-images.githubusercontent.com/31989842/38981301-553c55cc-43bf-11e8-812f-af1e289582f9.png)

**Comment by tyvdh** [comment]
I just ran into this issue today as well. When using a function for the variables when the variables change result gets called twice. Once with the old values and once with the new ones.

**Comment by tyvdh** [comment]
![screen shot 2018-08-13 at 5 53 44 pm](https://user-images.githubusercontent.com/4383610/44060206-e21b1c18-9f21-11e8-9471-b8a29b39023a.png)

**Comment by jdus** [comment]
Can confirm that. When using reactive parameters (function) for variables, update will be triggered twice. As @tyvdh correctly stated, once with the old values and once with the new ones.

![update_twice](https://user-images.githubusercontent.com/5982613/44524316-50e57b80-a6dd-11e8-8584-433817b3f3fb.png)

**Comment by lensanag** [comment]
Someone more with this issue twice on query?

**Comment by jdus** [comment]
Okay, I have been looking into this more closely. At one point I actually started thinking this was intended behaviour. The 'networkStatus' of '2' tells us that 'setVariables' has been called and the query is currently in process. We get a 'networkStatus' of '2' for the first (old) result. A 'networkStatus' of '7' means 'ready' and we get the updated result.
But then I tried again using 'no-cache' as fetchPolicy, meaning any result will not be taken or put into the cache. I still kept getting two updates, but this time both with 'networkStatus' of '7'. The first with 'stale' being 'false', the second with 'stale' being 'true'. The results are identical, so 'stale' being 'false' on the second result makes sense.
@Akryum, is this intended behaviour after all? Do I need to check networkStatus/stale values to decide whether to run code in the update method?

**Comment by jackylam1985** [comment]
I ran into the same issue as well.

**Comment by ValdoGhafoor** [comment]
I run the same issue too
Also maybe related:
I have a keep-alive around my router-view and one of my pages is holding an apollo smart query.

If I go to another page and go back, keep alive does his job and preserves component data but vue apollo still launches two cached queries.

**Comment by tqhoughton** [comment]
I am facing this problem too, the only "fix" I've found is adding `disableOffline: true` to my App sync client config. I have no clue why that is.

**Comment by tyvdh** [comment]
@ValdoGhafoor If you turn off keep-alive does the issue go away?

**Comment by jdus** [comment]
So, has this been resolved for anyone else or is it intended behaviour that update() gets called twice, if the variables change?

**Comment by hounded** [comment]
appsync problem described here
https://stackoverflow.com/questions/48942175/apollo-update-method-getting-called-twice-both-times-with-optimistic-fake-d/54262143#54262143
I used your fix `disableOffline:true` @tqhoughton thanks!

**Comment by samarti** [comment]
Solved it by changing query's `fetchPolicy` from `cache-and-network` to `no-cache`.

**Comment by ericzaev** [comment]
`const cache = new InMemoryCache({
    addTypename: false,
    resultCaching: false 
  });`

**Comment by reinoldus** [comment]
I hit the same issue today, disabling caching doesn't look like a solution to me.

Is this considered fixed?

**Comment by OttoTS** [comment]
I am experiencing this same issue. When the component renders the query is called and if you console log the result using a result hook you can see there are two responses. One of them is from the network and the other is from the cache. interestingly in my case, both have network status: 7 and stale: false but the data in each response object differs.

**Comment by bathyscaaf** [comment]
I am also having this issue.  Changing the fetchPolicy to "network-only" did not fix it.  I am getting an initial result, and then 5 seconds later I get it again.  Only a single call goes out to the network, but I get 2 results, 5 seconds apart.

**Comment by pffigueiredo** [comment]
I had a similar problem, where I was querying with a **variable with new Date() value**. As the **new Date()** keeps changing while the fetching is taking action, the query ended up running again because the variable had changed...

My solution was defining the date variable before `export default {...` like so `const date= new Date(),` and use this variable in the query's variables.

**Comment by MaevskiyE** [comment]
Anybody solved this issue?
