### ISSUE TITLE
Error when starting frontpage-vue-app, says error is in vue-apollo

### ISSUE THREAD

**Issue by rnenjoy** [Akryum/vue-apollo#19]
I get this:

ERROR in ./~/vue-apollo/index.js
Module not found: Error: Can't resolve './lib/vue-plugin' in '/srv/http/frontpage-vue-app/node_modules/vue-apollo'
 @ ./~/vue-apollo/index.js 1:17-44
 @ ./src/main.js
 @ multi main

It worked for me yesterday when i cloned the package, but not today.

**Comment by Samuell1** [comment]
+1
