### ISSUE TITLE
Tries to run queries before Apollo is ready/hydrated

### ISSUE THREAD

**Issue by ffxsam** [Akryum/vue-apollo#194]
This is most likely a thing specific to AWS AppSync, but:

I'm getting errors because my Apollo queries are running before the hydration process (restoring from cache vs network?) is complete.

See issue here: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/16

Is there some way to make instantiated Apollo client wait for `client.hydrated()` to resolve before performing any operations?

**Comment by Akryum** [comment]
Use `ssrForceFetchDelay` option on Apollo client.

**Comment by ffxsam** [comment]
@Akryum I don't think specifying an arbitrary delay is the solution.

**Comment by Akryum** [comment]
Then I didn't understand your issue, but when you create the Apollo Client, it's when you also specify the cache to restore.

**Comment by ffxsam** [comment]
No worries.. this is a very specialized thing. 👍 The solution was super simple. If I can find somewhere to document it appropriately here, I will. AppSync is still in beta/preview now, but I'm sure at some point many people will be using it.

**Comment by ffxsam** [comment]
@rimutaka Sure! Sorry I didn't already share, I hate when people say "FIXED IT!" and don't share how. 😅 

Basically you just wrap the main part of your application in this:

### App.vue
```html
<div v-if="hydrated">
  ...your main components
</div>
```

And then in the script portion of App.vue:

```js
export default {
  data() {
    return {
      hydrated: false,
    };
  },

  async created() {
    await this.$apollo.provider.defaultClient.hydrated();
    this.hydrated = true;
  },
}
```

**Comment by rimutaka** [comment]
@ffxsam Sam, thanks a lot. It didn't help my case, but I do see your point. 👍

**Comment by domsen123** [comment]
@ffxsam hmm... I get "this.$apollo.provider.defaultClient.hydrated is not a function" 🤔 maybe there was an update? cant get it to work...
