### ISSUE TITLE
Is there a similar solution like getDataFromTree (react-apollo)?

### ISSUE THREAD

**Issue by ahalimkara** [Akryum/vue-apollo#197]
I know there is a [willPrefetch](https://github.com/Akryum/vue-apollo/blob/370c286b4355d96c318c613ca2f77de7f5ae1c22/src/apollo-provider.js#L169) function but it is working globally. I need to run all queries only for current route (even on child components).

I have a repo if you want to test: [here](https://github.com/ahalimkara/nuxt-apollo/blob/d1e87a0ae570b1915fecc7abf08d531978a67520/layouts/default/Nav.vue#L38) I am setting `viewer` query and `Nav` is [a child component](https://github.com/ahalimkara/nuxt-apollo/blob/d1e87a0ae570b1915fecc7abf08d531978a67520/layouts/default.vue#L3) of `default` layout. When I call `/` home page from browser I expect that this query run only on server and [restore apollo state](https://github.com/nuxt-community/apollo-module/blob/c62d59a420e48bf1b175585a79380e3ca8aa25e9/plugin.js#L32) on client side. But the query runs both on server and client. You can see logs because I am using [a custom logger](https://github.com/ahalimkara/nuxt-apollo/blob/master/graphql/apollo/ApolloLogger.js).

I have another question about willPrefetch: lets say I have a query on child component on `/rare-route` page and wrapped with willPrefetch. First time when the application is started, that query will never be executed till somebody requested `/rare-route`, once requested that query will run for every requests because it uses [module global variable](https://github.com/Akryum/vue-apollo/blob/370c286b4355d96c318c613ca2f77de7f5ae1c22/src/apollo-provider.js#L167). So for every application restart `/rare-route` must be requested for application state consistency. I am not sure how node keeps state of module global variables but it looks like it will remain at memory till application restarted (what I understand from my tests). Please correct me if I am wrong.

**Comment by Akryum** [comment]
You can now pass a callback as the 2nd argument of `willPrefetch`, that will get the context and should return a boolean (`false` ➡️ the component will not prefetch).
