### ISSUE TITLE
Support for Firebase Hosting

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#199]
I recently saw a video from Firebase about hosting vue/nuxt apps in Firebase. My app is built with vue-apollo and nuxt.  Is Apollo compatible with their hosting? Any demo repo with Apollo? I'm using `prefetch: true`

**Comment by Akryum** [comment]
Firebase has its own data-layer, not sure if you can integrate GraphQL into it. I'm not a firebase expert though.

**Comment by gijo-varghese** [comment]
Ok. Let me try it
