### ISSUE TITLE
Accessing data from error callback

### ISSUE THREAD

**Issue by jleskovar** [Akryum/vue-apollo#20]
Vue, vue-apollo, apollo-client et al are new technologies for me, so excuse the newbie question :-)

I'm trying to implement a simple error callback for my vue component (vue-loader) to set a variable in my data context, as follows:

```
  apollo: {
    requestMappings: {
      query: requestMappings,
      update(data) {
        return data.spring.requestMappings;
      },
      error: (err) => {
        console.log(this)
        showNetworkError = true
      }
    }
  }
```

Here, showNetworkError is not accessible, as the "this" object is the apollo query object. I've tried different styles of "error: function(err) { .. } and "error(err) { ... }", with not much luck. Clearly I feel like I've missed something obvious - how are we able to set data from the callbacks?

Kind regards
James

**Comment by Akryum** [comment]
Try the `1.2.3` version of `vue-apollo`.

**Comment by jleskovar** [comment]
Looks like it's fixed now 👍

Can now access data via this.$data...
