### ISSUE TITLE
Use cookie as a variable for Query in Nuxt

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#200]
I'm using https://github.com/S64/vue-universal-cookies to use cookies on both server side and client side. This library works perfectly. However if I use it as a variable in the query, it doesn't work. Any idea?

```
<template>
 <div>
  {{ $cookies.get('customerId') }} // this works
 </div>
</template>
<script>
import CUSTOMER from "~/graphql/queries/CUSTOMER.gql";

export default {
created() {
  console.log(this.$cookies.get('customerId)) // this works on both server and client
},
  apollo: {
    customer: {
      query: CUSTOMER,
      prefetch: true,
      variables(){
        return {
         customerId: this.$cookies.get('customerId) // this doesn't work
        }
      }
   }
 }
}
```

**Comment by Samuell1** [comment]
Pass it to component `data` in created hook, then `this.myCookie`.

**Comment by gijo-varghese** [comment]
@Samuell1 but data variables are not accessible from server rendering. I'm getting an error in nuxt: `Network error: Response not successful: Received status code 400`

and in graphql server: `GraphQLError: Variable "$customerId" of required type "ID!" was not provided.`

**Comment by Samuell1** [comment]
@gijo-varghese you can use middleware in nuxt to get cookies from request. Here is example how to get user object from cookies https://github.com/Samuell1/nuxt-login/blob/master/middleware/check-auth.js

**Comment by gijo-varghese** [comment]
Ok. Let me try that

**Comment by gijo-varghese** [comment]
Finally made it https://github.com/Akryum/vue-apollo/issues/227
