### ISSUE TITLE
Consuming Vue-Apollo in a library

### ISSUE THREAD

**Issue by JasonLi914** [Akryum/vue-apollo#201]
Hi, so I'm trying to use vue-apollo, however from the docs, it looks like I have to install the plugin globally and also create a single provider for all apollo-client instances that I put on the app's root Vue instance. I unfortunately do not have the ability to control injecting the provider, as I am not the app owner, but am developing a single library of Vue components that I would like to interface with my GraphQL endpoint. Was wondering if what I am trying to do is possible or if I should be looking at another approach?

**Comment by Kocal** [comment]
Hey,

Vue-apollo is just a Vue wrapper of [apollo-client](https://github.com/apollographql/apollo-client), so it means that you can directly use apollo-client like that:

```js
// https://github.com/apollographql/apollo-client#usage

const client = new ApolloClient({
  // ...
});

client.query({
  query: gql`
    query TodoApp {
      todos {
        id
        text
        completed
      }
    }
  `,
})
  .then(data => console.log(data))
  .catch(error => console.error(error));
```

**Comment by littletower** [comment]
@Kocal how would you pass the data to the component after the call has finished loading?

**Comment by Kocal** [comment]
Can you provide some code please? thx

**Comment by JasonLi914** [comment]
@Kocal - So a couple things with using ApolloClient directly, is that it doesn't include the nice syntax that vue-apollo has via the `apollo` object on components options. 

This is less of an issue than my main concern with using apollo-client directly in that I'm designing a widget that interfaces with a GraphQL endpoint and there can be multiple widgets on the page. If each widget was to create its own ApolloClient, would I not lose out on the benefit of all widgets on the same page sharing the same cache? I guess I could extract out apollo-client into a singleton that gets used by all widgets on the page, but not sure if there is a better method?

**Comment by Kocal** [comment]
Well, yeah that's true. 

Tbh, I can't answer to your questions, I'm not again comfortable with VueApollo nor ApolloClient, sorry :man_shrugging:

**Comment by Akryum** [comment]
You can now use the `provide`/`inject` api with `apolloProvider.provide()`. You shouldn't have to worry about it if done by the user, but you can also add one yourself now.

```html
<script>
const apolloProvider = new VueApollo({ /* ... */ })
export default {
  provide: apolloProvider.provide(),
}
</script>
```

Also, `willPrefetch` is exposed on `window` or `global` as `vueApolloWillPrefetch`.

**Comment by georgyfarniev** [comment]
@Akryum thanks for example. Can you give some example how it could be used inside the library itself?
