### ISSUE TITLE
How to using sync mode to the request

### ISSUE THREAD

**Issue by lizhongit** [Akryum/vue-apollo#203]
I had this code:

```js
export default {
  name: 'app',
  apollo: {
    // Apollo specific options
    hello: gql`{hello}`,
  },
  mounted: {
    console.log(this.hello) // Output: null
  }
}
```
 But my template
```html
 <div>{{ hello }}</div>
```

Should be rendered this
```html
<div>World</div>
```

I know it is need a time to create a POST request and waiting the server-side respond a JSON to render the HTML.
But how can I know that finished the work? Or setting it request mode to be synchronized, like await、async

**Comment by Akryum** [comment]
Use conditionals in your template.
