### ISSUE TITLE
How to use Apollo Client in js file?

### ISSUE THREAD

**Issue by thetre97** [Akryum/vue-apollo#204]
No doubt I'm missing something obvious - I apologize in advance because I'm new to all this :)

I'm trying to use Auth0 to authenticate requests to Graphcool. I have a Vue app, copied from the [Auth0 tutorial](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login), which when authenticated etc returns an id_token. To my understanding, this then needs to be sent to the graphql backend, to use the [authenticateUser mutation](https://github.com/graphcool/templates/blob/master/auth/auth0/example/index.js) to create/check if a user exists in the db, and then it returns a token which can be used to authenticate further graphcool requests.

My question is, how do I use `this.$apollo` in a javascript file, not a Vue Component? Do i need to import a package or something? I thought to put the authenticateUser mutation in this file https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/auth/AuthService.js so it returns a token, which can be set to local storage. But when I use this.$apollo it logs an error that it is undefined.

I would be grateful for any help!

**Comment by Akryum** [comment]
You can use the apollo client directly.

**Comment by thetre97** [comment]
thanks - and again, apologies for the newbie questions, but how do I do that?
I added `import { apolloClient } from 'apollo-client'` then tried using `apolloClient.mutate`, but it threw this: `Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_7_apollo_client__.a.mutate is not a function`?

**Comment by Akryum** [comment]
You need to use the `apolloClient` you created (the one you used in `apolloProvider`).

**Comment by thetre97** [comment]
ah, got it, thank you!

**Comment by eddivalen** [comment]
Hey guys! I got the same issue, can you show me an example of this? @thetre97  @Akryum

**Comment by thetre97** [comment]
Assuming you used the `vue add apollo` command, you will get a `vue-apollo.js` file in the `src` folder.
In that file, there is a function like so:

```javascript
export function createProvider (options = {}) {
  // Create apollo client
  const { apolloClient, wsClient } = createApolloClient({
    ...defaultOptions,
    ...options,
  })
  apolloClient.wsClient = wsClient

  // Create vue apollo provider
  const apolloProvider = new VueApollo({
    defaultClient: apolloClient,
    defaultOptions: {
      $query: {
        // fetchPolicy: 'cache-and-network',
      },
    },
    errorHandler (error) {
      // eslint-disable-next-line no-console
      console.log('%cError', 'background: red; color: white; padding: 2px 4px; border-radius: 3px; font-weight: bold;', error.message)
    },
  })

  return apolloProvider
}
```

You will need to move these lines (where it is creating the actual apollo client) outside of the function, and turn it into an export.

```javascript
 // Create apollo client
 export const { apolloClient, wsClient } = createApolloClient({
    ...defaultOptions
    // removed ...options
  })
  apolloClient.wsClient = wsClient

export function createProvider (options = {}) {
...
```

You can then use this in any file, by simply importing it, and using it instead of `this.$apollo`:

```javascript
import { apolloClient } from '@/vue-apollo' // @ is an webpack alias to the src/ folder

apolloClient.query({
    query: gql`{hello}`
}).then(data => console.log(data))
```

**Comment by eddivalen** [comment]
@thetre97 Amazing! thanks a bunch!  also I've had to remove createProvider() from main.js

**Comment by samuveth** [comment]
> `apolloClient.query({})`

@thetre97 I can't find this in any of the Apollo docs for some reason.

**Comment by chenqiao0306** [comment]
If you want to use Apollo Client in js file with vue, you can add to Vue.prototype when the Apollo Client was created.
```
import Vue from 'vue'
const apolloClient = new ApolloClient({
  link: from([authLink, errorLink, httpLink]),
  cache: new InMemoryCache(),
  defaultOptions
})
Vue.prototype.$apolloClient = apolloClient
```
use it in js file
```
import Vue from 'vue'
function test() {
  const apolloClient = vue.prototype.$apolloClient
  return apolloClient.query({
    query: gql,
    variables: {... }
  })
}
```
