### ISSUE TITLE
Allow adding apollo context option on a component level

### ISSUE THREAD

**Issue by TheDeveloperTom** [Akryum/vue-apollo#205]
![image](https://user-images.githubusercontent.com/25426552/35962455-2a3fa982-0cba-11e8-90a7-0f60658fc92f.png)

![image](https://user-images.githubusercontent.com/25426552/35962687-f97d2f26-0cba-11e8-8b80-3d28796cf01b.png)

**Comment by Akryum** [comment]
`context: ...` in the queries isn't working for you?

**Comment by Akryum** [comment]
`context` is now reactive.
