### ISSUE TITLE
Support for Fragments

### ISSUE THREAD

**Issue by anuragnagarkota** [Akryum/vue-apollo#207]
Hii

Is is possible to use fragments?

Thanks in advance

**Comment by Akryum** [comment]
Yes, here is an example: https://github.com/Akryum/vue-summit-app/blob/master/app/src/graphql/QuestionAdd.gql

**Comment by anuragnagarkota** [comment]
Hey Akryum 

I have just implemented a sample of this. Can you plz have a look at this and let me know if I am doing it correctly or not? I am just passing down the data via props(is this correct approach or not?)

main.vue 

//====================================================
<template>
<License :licenses="licenses"/>
    </template>
    <script>
import License from "./License";
import LicenseFragment from "./LicenseFragment";
import gql from "graphql-tag";

const fragments = {
  LicenseFragment: LicenseFragment
};
export default {
  fragments,
  name: "FragmentSample",
  components: { License },
  apollo: {
    licenses: {
      query: gql`
        query {
          licenses {
            ...LicenseFragment
          }
        }
        ${fragments.LicenseFragment}
      `
    }
  }
};
</script>
//====================================================

License.vue

//====================================================
<template>
 <div>
<ul>
    <li v-for="l in licenses" :key="l.id">
{{l.id}}
    </li>
  </ul>
  </div>
</template>

<script>
import gql from "graphql-tag";
import LicenseFragment from "./LicenseFragment";
export default {
  name: "License",
  props: ["licenses"]
};
</script>

 
//====================================================

LicenseFragment.js
//====================================================
import gql from 'graphql-tag'
const fragment = gql `fragment LicenseFragment on License {
  id
}`
export default fragment
//====================================================

Thanks
