### ISSUE TITLE
Is there a less boilerplate way to handle mutations?

### ISSUE THREAD

**Issue by ffxsam** [Akryum/vue-apollo#209]
It would be nice to have some sort of helper function to handle the `update()` and optimistic UI code.

```js
update: (store, { data: { createTask } }) => {
  // Add to All tasks list
  const data = store.readQuery({ query: TASKS_ALL })
  data.allTasks.push(createTask)
  store.writeQuery({ query: TASKS_ALL, data })
  // Add to Todo tasks list
  const todoQuery = {
    query: TASKS_ALL,
    variables: { filter: { done: false } },
  }
  const todoData = store.readQuery(todoQuery)
  todoData.allTasks.push(createTask)
  store.writeQuery({ ...todoQuery, data: todoData })
},
optimisticResponse: {
  __typename: 'Mutation',
  createTask: {
    __typename: 'Task',
    id: null,
    done: false,
    label,
  },
},
```

Aside from the query and variables, I imagine this is typically going to be the same code over and over throughout every mutation. This is not very DRY.

**Comment by Akryum** [comment]
I think this is outside of the scoped of vue-apollo.

**Comment by ffxsam** [comment]
Devs could easily write their own properties/methods to condense this and make it more reusable. Just saying, it would be handy for vue-apollo to include helper functions.

Would you consider a PR?

**Comment by Akryum** [comment]
I think this would be cluttering vue-apollo a bit too much. Maybe in another new package?
