### ISSUE TITLE
vue-apollo how to mapStateToProps

### ISSUE THREAD

**Issue by Qquanwei** [Akryum/vue-apollo#21]
apollo-client worked in redux ,  so how to implement  a vue component get data from apollo store to share data between with another component.  thanks

**Comment by Akryum** [comment]
Use the same query, it will get the data from the apollo cache (which is a redux store).

**Comment by Qquanwei** [comment]
If some query or mutation execute , store changed , can every component be update immediately?

**Comment by Akryum** [comment]
They should be updated, yes.

**Comment by Qquanwei** [comment]
thanks 👍
