### ISSUE TITLE
"Not defined" error when using apollo properties in 3.0 beta

### ISSUE THREAD

**Issue by jbbr** [Akryum/vue-apollo#213]
After upgrading from `3.0.0-alpha` to `3.0.0-beta.4` the behavior of reactive properties changed in a breaking way:

Code:
```js
export {
  apollo: {
    users: {query: usersQuery}
  }
}
// template: <div>{{users}}</div>
```
( users query returns array, pseudo code for demonstration)

This used to work in 3.0 alpha.
In `3.0.0-beta.4` I get the following error in dev console:

> Property or method "users" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

Workaround:
```js
export {
  apollo: {
    users: {query: usersQuery}
  },
  data() {
    return {users: null}
  }
}
// template: <div>{{users}}</div>
```

Is this new behavior intended or a bug?

Thanks

**Comment by Zauberklavier** [comment]
This is a little diversion but I think it might be related. In the project I'm working on the `this.$apollo.queries` was empty and on `3.0.0-beta.4` and no requests were being sent to the graphql server. A downgrade to`3.0.0-alpha.1` and no changes in code did the trick.

Regarding the upgrade to 3.0, I can't find any docs on what has changed and I spent the entire day trying to figure out how to do queries in 3.0 😢

**Comment by Akryum** [comment]
This new behavior is intended. I had the old one working but wanted to ditch it and now I got a good reason to do so (it doesn't work with the usage of provide/inject - related to lifecycle hooks).
Explicitly declaring the properties initial values in the `data` hook is a much better practice.
