### ISSUE TITLE
Multiple clients usage

### ISSUE THREAD

**Issue by fnoop** [Akryum/vue-apollo#216]
Hi, I've got multiple clients setup and working, in that I can either set 
`apollo: { $client: 'a'` or set `client: 'a'` in the query.

a) However, I want to be able to select the active client dynamically at runtime and have a query switch between the different clients.  But setting client or $client to a property doesn't change the query when the client is updated.  How can I do this?

b) I would like to be able to connect to multiple clients simultaneously within a component and display data from each clients.  How can I do this?

Thanks for the great software :)

**Comment by fnoop** [comment]
Is it possible to do this at the moment?  Am I doing something wrong, or is there a workaround that would allow this?

**Comment by fnoop** [comment]
```
[Vue warn]: Error in render: "TypeError: Cannot set property client of #<SmartQuery> which has only a getter"
```
Can't set query client, and can't use function for apollo.$client.

**Comment by fnoop** [comment]
Ok so I've worked around this by setting :key="activeClient" in the child component definition, and then within the child component:
```
computed: {
   activeClient () { return this.$store.state.activeClient }
},
apollo: {
      $client () { return this.activeClient },
      ...
```
So as activeClient is set by the interface (eg dropdown), the :key="activeClient" forces vue to rerender the component, which then sets the apollo client.  So it involves recreating the entire component which is pretty clunky, but it does at least allow for the same query to be used on different clients.
It would be significantly easier if either the apollo or the query client property could be set as a function or variable and was reactive.

**Comment by fnoop** [comment]
The remaining problem I have is this:
 - Connect to and display the same query from multiple clients simultaneously, within a component.

This should be straight forward and there are all sorts of use cases for this.  But it doesn't look like you can create separate addSmartQuery for the same query with different clients, because they are all keyed by the message name.
Is there anyway to work around this?

**Comment by Akryum** [comment]
You can with the manual mode in the next release.
