### ISSUE TITLE
Reactivity in objects

### ISSUE THREAD

**Issue by pSchaub** [Akryum/vue-apollo#219]
Let's say we have this data:
```
filters: {
  name: null,
  email: null
}
```

Let's change the email through `v-model="filters.email"` on an `input` field.

We want that the query will be refetched once the email changes.

This is working:
```
variables () {
  return {
    filter: {
      name: this.filters.name,
      email: this.filters.email
    }
  }
}
```
This is NOT working:
```
variables () {
  return {
    filter: this.filters
  }
}
```

So I think the reactivity is not working if there are changes inside objects. Is there a way we can easily fix this inside vue-apollo so usage of `filter: this.filters` will be possible?

**Comment by Akryum** [comment]
I think a `deep: true` param on the watcher is missing in smart-apollo. 😅

**Comment by pSchaub** [comment]
@Akryum If that simple flag will solve this "issue" it would be very great to enable it. Maybe it should be enabled by default but be able to disable it for a single query in case somebody has very huge objects.

**Comment by vladimir-chernenko** [comment]
@pSchaub 
I'm not js expert, but may be you can use this approach?

```
variables () {
  return {
    filter: {...this.filters}
  }
}
```
