### ISSUE TITLE
Queries aren't running in beta

### ISSUE THREAD

**Issue by Zauberklavier** [Akryum/vue-apollo#221]
Here's a snippet, it runs well on `3.0.0-alpha.1` but not on `3.0.0-beta.4`:
```javascript
import gql from 'graphql-tag'

export default {
  name: 'Grades',
  data() {
    return {
      grades: null // I figured I should define the props explicitly since beta
    }
  },
  apollo: {
    grades: gql`
      {
        grades {
          id
          title
        }
      }
    `
  }
}
```

In `3.0.0-beta.4` the `grades` query is never ran. There are no outgoing network requests to the graphql server and no errors in the console. The `this.$apollo.queries` is also empty. The `grades` prop stays `null`.

**Comment by ozguruysal** [comment]
There's a [breaking change](https://github.com/Akryum/vue-apollo/releases/tag/v3.0.0-beta.1) since v3.0.0-beta.1. Did you make the required changes?

**Comment by Zauberklavier** [comment]
No, I didn't! I didn't see it when I was searching for a solution. Thanks!
