### ISSUE TITLE
DateTime in query variable 

### ISSUE THREAD

**Issue by morriq** [Akryum/vue-apollo#222]
Hello,

I have query

```
apollo: {
      allChannels: {
        query: allChannels,
        update: (data) => data.allChannels,
        prefetch: true,
        variables: () => ({
          first: 3,
          lastActivity
        })
      }
    }
```

where `lastActivity = new Date().toISOString()` (for example)

That way my component is refreshing data on client side. When I create `lastActivity = "2016-02-20T18:21:41.375Z"`  then it's fine - it's not refreshing content. 
I don't want to refresh data on client side but I want to have posibility to put currentTime (lets say serverside date is enough) in query. How could I achieve that?

**Comment by morriq** [comment]
@Akryum why closed?

**Comment by Akryum** [comment]
I answered on the original issue in the nuxt module.
