### ISSUE TITLE
Error when pushing from a different route

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Akryum/vue-apollo#223]
Don't know if this is related to apollo or nuxt

but it seems to be an issue on ssr

what i'm doing on my code is this

```js
    apollo: {
      result: {
        query: Receipt,
        prefetch({ params }) {
          return {
            id: params.id
          };
        },
        variables() {
          return {
            id: this.$route.params.id
          };
        }
      }
    }
```

I have that code setup on nuxt and prefetch the route parameters from it

then when i do this

```js
          this.$router.push({
            name: "receipts-id",
            params: { id: data.result.receipt.id }
          });
```

it throws an error showing the $apollo.loading is not defined

any ideas?
![image](https://user-images.githubusercontent.com/25447231/36626264-bd1bc648-196a-11e8-8887-4a87c82ba783.png)

It works okay when refreshing it 

pushing routes is the problem i think

**Comment by zerosym** [comment]
I've encountered the same issue.

The problem occurs when the component housing the smart query does not get recreated, such as in your example of route updates where only the parameters change.

When a component initializes for the first time, the following occurs:

1. data() hook is called, which returns the uninitialized/base $apolloData object:
https://github.com/Akryum/vue-apollo/blob/4096d00d63001bc9654b175407de89bce4dca625/src/index.js#L123
2. created hook is called, which initializes the $apolloData object given the component's apollo options
https://github.com/Akryum/vue-apollo/blob/4096d00d63001bc9654b175407de89bce4dca625/src/smart-query.js#L19

When a component is reused, only the data() hook gets called which resets the $apolloData object, leading to the undefined error occurring here:
https://github.com/Akryum/vue-apollo/blob/4096d00d63001bc9654b175407de89bce4dca625/src/smart-query.js#L33

The ugly workaround I'm currently using is to store $data.$apolloData in another data property on the component during the beforeRouteUpdate hook, and then returning it in my own data() function.

**Comment by ralphchristianeclipse** [comment]
@zerosym well if you can make a pr on this it would be great :)

**Comment by UnGast** [comment]
This is probably the same error: #212

**Comment by ralphchristianeclipse** [comment]
@Akryum 

Any updates about this?

**Comment by dohomi** [comment]
Seeing the same error. Not sure if my PR is fixing it though: #237

**Comment by ralphchristianeclipse** [comment]
@Akryum any updates to pull the PR? from @dohomi 

Seems the problem still exists and hard to fix

**Comment by ralphchristianeclipse** [comment]
@Akryum 

```
vendor.js:42239 Uncaught TypeError: Cannot read property 'loading' of undefined
    at SmartQuery.get$$1 (vendor.js:42239)
    at SmartQuery.loadingDone (vendor.js:42143)
    at SmartQuery.nextResult (vendor.js:42083)
    at notifySubscription (vendor.js:76116)
    at onNotify (vendor.js:76151)
    at SubscriptionObserver.next (vendor.js:76205)
    at vendor.js:3032
    at Array.forEach (<anonymous>)
    at Object.next (vendor.js:3032)
    at vendor.js:3500
```

this is still an issue any fix for it ?
