### ISSUE TITLE
Does this work Apollo-boost?

### ISSUE THREAD

**Issue by aaronksaunders** [Akryum/vue-apollo#224]
https://dev-blog.apollodata.com/zero-config-graphql-state-management-27b1f1b3c2c3

**Comment by Akryum** [comment]
Yes! The plugin only needs an ApolloClient.

**Comment by aaronksaunders** [comment]
I will take another look at my code, but code is throwing errors iny migration attempts based on the instructions provided in the medium post. 

I know that post uses react, but I thought it could work with vuejs
