### ISSUE TITLE
Sending Headers to the server failed

### ISSUE THREAD

**Issue by arjitkhullar** [Akryum/vue-apollo#225]
"createnetworkinterface" is deprecated and there is no example of new [Apollo Client Middleware](https://github.com/apollographql/apollo-client/blob/master/Upgrade.md#middleware) with vue-apollo.

Here is the middleware:
```
 var httpLink = createPersistedQueryLink().concat(
    new HttpLink({
      uri: ENDPOINT + '/graphql'
    })
  )
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: {
        authorization: localStorage.getItem('token') || null
      }
    })
    return forward(operation)
  })
  const link = middlewareLink.concat(httpLink)
  const cache = new InMemoryCache()
  const apolloClient = new ApolloClient({
    link,
    cache,
    connectToDevTools: true
  })
```
side note: I have exposed the headers on the server. 
side side note: when i set headers using graphql playground the server receives the headers..

**Comment by Akryum** [comment]
This doesn't seem to be related to vue-apollo. Please ask on the apollo-link repository. Thanks! 👍
