### ISSUE TITLE
Reusing Query data and mutation

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#228]
Consider I've a query '`customer`' to fetch customer details. Right now what I'm doing is set `network-only` in main component and in other components I use `cache-only`. It works fine. But when I look at the components, the same code is used again and again. Is there anyway to solve it? Like inject customer query result globally, so that it will be available in each component's data. Or are there any other best practices?

Similar case for some mutation. It almost 5-10 lines to mutate something. Same code is used in many components. Something that I don't feel good.

Passing through props won't work for me. Not everyone are child components.

**Comment by gijo-varghese** [comment]
Just a side note, I use Nuxt Apollo module

**Comment by Akryum** [comment]
You could use mixins. Also fetching the same query multiple times is perfectly fine for Apollo.
