### ISSUE TITLE
Skip Subscription

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#235]
I want to start/connect to WebSockets only after setting a `cookie`. The cookie setting logic is inside the `mounted` function. But Apollo subscriptions are executed even before that. Is it possible to connect to web socket only after setting the cookie?

Also in the documentation, I saw 
```
skip() {
        return this.skipSubscription
}
```

If the skip is returning true by default, will it open socket connection?

**Comment by Akryum** [comment]
The web socket connection will open as soon as you create the web socket link.

**Comment by gijo-varghese** [comment]
@Akryum ok. How can I `open` it only after setting a cookie?

**Comment by Akryum** [comment]
Well, you control the JS code creating it. 😛

**Comment by gijo-varghese** [comment]
ok. Let me try

**Comment by gijo-varghese** [comment]
@Akryum https://github.com/apollographql/subscriptions-transport-ws#subscriptionclient there is something called `lazy` when set to true, will connect to socket only if a subscription is created. If I create a subscription with default `skip` as true, will that be considered as 'created'?

**Comment by paulpdaniels** [comment]
@gijo-varghese have a look at https://github.com/leadiq/apollo-link-defer I created it for a similar case where the websocket url is only known *after* an API call (and therefore after apollo-client) is already set up.

**Comment by jpikora** [comment]
@gijo-varghese you could also force socket reconnection at appropriate moment (e.g. after you've set the cookie)

```
const wsLink = new WebSocketLink({
  options: {
    reconnect: true,
    ...
  },
  ...
})

export const subscriptionClient = wsLink.subscriptionClient
```

```
import { subscriptionClient } from ...

subscriptionClient.close()
```

**Comment by gijo-varghese** [comment]
I've tried that. But after reconnecting subscriptions aren't working. Looks like a bug from `subscription-transport-ws`

**Comment by Akryum** [comment]
You can try something like [this](https://github.com/Akryum/vue-cli-plugin-apollo/blob/06699fcfbad8c4b394c1e8a9b676908d4f5a6e5f/generator/templates/default/src/apollo.js#L19).
