### ISSUE TITLE
Inline Fragments

### ISSUE THREAD

**Issue by Mcisah** [Akryum/vue-apollo#240]
Hello, 
I've been trying to make a query which makes use of inline fragments as shown below:

> query PostQuery{
>   article: post(id:2){
>     __typename
>     ... on PostNode{
>       post{
>     	__typename
>         id
>         title
>         excerpt
>       }
>     }
>     ... on Messages{
>       messages{
>         __typename
>         key
>         message
>       }
>     }
>   }
> }

The idea is to get a message type returning "Post not found" if the post does not exist.
It seems to work when I try it using insomnia.

![image](https://user-images.githubusercontent.com/17323570/37755708-df9d84a4-2da6-11e8-8079-f56fc2802de8.png)

Would like to know if inline fragments is being supported by vue-apollo or it's just my approach thats wrong here.

**Comment by paulpdaniels** [comment]
I think this would depend on the apollo-client that you are using

**Comment by Mcisah** [comment]
Ohh, You mean like a later or earlier version of vue-apollo would work ?

**Comment by Akryum** [comment]
See [the apollo docs](https://www.apollographql.com/docs/react/recipes/fragment-matching.html).
