### ISSUE TITLE
Subscription WebSocket connection closing occasionally

### ISSUE THREAD

**Issue by gijo-varghese** [Akryum/vue-apollo#242]
After building a VueJS app with Apollo Server graphql and vue-apollo for the client, the socket is occasionally disconnected on the first load itself. (It won't happen every time, maybe once in every 5-10 loads). Do you know the reason for this?

![152173961846741591](https://user-images.githubusercontent.com/23092846/37788272-02646d9c-2e27-11e8-86bc-6847b2773488.gif)
![screenshot from 2018-03-22 21-24-13](https://user-images.githubusercontent.com/23092846/37788273-029912c2-2e27-11e8-8ebb-a5119fe7459e.png)

**Comment by Akryum** [comment]
I don't know, maybe it usually happens with websockets?

**Comment by gijo-varghese** [comment]
Finally 
```
link.subscriptionClient.maxConnectTimeGenerator.duration = () => link.subscriptionClient.maxConnectTimeGenerator.max
```
That fixed the issue. The problem was with `subscriptions-transport-ws` library

**Comment by oluwajubelo1** [comment]
@gijo-varghese , where exactly should we place that code? Please, clarify because am also facing the same issue.Thanks

**Comment by gijo-varghese** [comment]
@oluwajubelo1 I don't remember exactly where. I've even left VueJS!

**Comment by oluwajubelo1** [comment]
@gijo-varghese Thanks for your prompt response

**Comment by Akryum** [comment]
I think that's when you create the websocket link for ApolloClient.
