### ISSUE TITLE
Setting metadata to smart query

### ISSUE THREAD

**Issue by jantajov** [Akryum/vue-apollo#247]
I am trying to set metadata to my smart query as follows.

    apollo: {
      realties: {
        metadata: {mainquery: true},
        query: gql`query { realties { name } }`
      }
    }

But cannot access them :(

```
const loadingLink = new ApolloLink((operation, forward) => {
  console.log('operation', operation)
  return forward(operation)
})
```

API reference for query show there can be metadata field.
https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query

How can I set metadata for my smart query and how can I access it in ApolloLink?

**Comment by Akryum** [comment]
Did you try using `context` instead?

**Comment by jantajov** [comment]
Works great!
