### ISSUE TITLE
"updateQuery" method of subscribeToMore never be called

### ISSUE THREAD

**Issue by wansj** [Akryum/vue-apollo#248]
Hi, guys! I have a ViewBooks component which lists some books, I want it to be reactive to Book Create/Update/Remove actions. I thought the subscription data from server will flow into the updateQuery method, where I can update the cached books. But it never be called!The Chrome console output nothing!
The subscribeToMore in my component:
```
apollo: {
    books: {
      query: AllBooksQuery,
      variables () {
        return {limit: this.pageSize, skip: 0}
      },
      result ({ data: { books } }) {
        this.initBooks({ books })
      },
      subscribeToMore: {
        document: BookChangedSubscription,
        updateQuery: (previousResult, { subscriptionData }) => {
          console.log(subscriptionData)
        }
      }
    }
  }
```
ApolloClient set up:
```
const wsLink = new WebSocketLink({
  uri: GRAPHQL_WEBSOCKET_ENDPOINTS,
  options: {
    reconnect: true,
    connectionParams: {
      authToken: localStorage.getItem(GC_AUTH_TOKEN)
    }
  }
})
let link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query)
    return kind === 'OperationDefinition' && operation === 'subscription'
  },
  wsLink,
  httpLink
)
// Create the apollo client
const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  connectToDevTools: true,
  link
})
```
On the server side, I followed the  [GraphQL subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/) tutorial to set up a GraphQL server.
The Subscription type:
```
const Subscription = `
  type Subscription {
    bookChanged: Book
  }
`
const SchemaDefinition = `
    schema { 
      query: Query
      mutation: Mutation
      subscription: Subscription
    }
  `
```
The Subscription resolver:
```
Subscription: {
      bookChanged: {
        subscribe: () => pubsub.asyncIterator(['bookAdded', 'bookDeleted'])
      }
    },
```
The pubsub instance:
```
const pubsub = new RedisPubSub({
  connection: {
    host: REDIS_DOMAIN_NAME,
    port: REDIS_PORT_NUMBER,
    retry_strategy: options => {
      return Math.max(options.attempt * 100, 3000)
    }
  },
  connectionListener: (e) => {}
})
```
SubscriptionServer  set up:
```
const ws = createServer((req, res) => {
  res.writeHead(404)
  res.end()
})
ws.listen('5000', async () => {
  const schema = await buildSchema()
  new SubscriptionServer({
    execute,
    subscribe,
    schema
  }, {
    server: ws,
    path: '/subscriptions'
  })
})
ws.on('error', (e) => {})
```
Publish payload in the Mutation:
```
Mutation: {
      addBook (obj, args, context, info) {
        const Book = context.db.model('Book')
        const book = new Book(args)
        return book.save({lean: true}).then((bookAdded) => {
          pubsub.publish('bookAdded', { bookAdded })
          return bookAdded
        })
      },
     delBookById (obj, { id }, context, info) {
        const Book = context.db.model('Book')
        return new Promise((resolve, reject) => {
          Book.findByIdAndRemove(id, { lean: true }, (err, bookDeleted) => {
            if (err) reject(err)
            else {
              pubsub.publish('bookDeleted', { bookDeleted })
``` 
The websocket connect frames:
<img width="1434" alt="network" src="https://user-images.githubusercontent.com/3777800/37944175-36566f9a-31ad-11e8-829f-d4f06ca42ca2.png">
I have been fussing about the problem for days. Help!!! Thanks in advance.

**Comment by Akryum** [comment]
Could you try with a simple `$subscribe`? ([docs](https://github.com/Akryum/vue-apollo#subscribe))

**Comment by wansj** [comment]
@Akryum ,thanks for your relpy. I tried $subscribe as below:
```
 apollo: {
    books: {
      query: AllBooksQuery,
      variables () {
        return {limit: this.pageSize, skip: 0}
      },
      result ({ data: { books } }) {
        this.initBooks({ books })
      }
    },
    $subscribe: {
      bookChanged: {
        query: BookChangedSubscription,
        result (data) {
          console.log(data)
        }
      }
    }
  }
```
But still got no response from the server. The chrome console has no output. The websocket connection has only send, no receive.
<img width="1434" alt="capture" src="https://user-images.githubusercontent.com/3777800/37958814-1b9a685a-31e4-11e8-965c-a8ed14b1f318.png">
Any mistake did I make?

**Comment by Akryum** [comment]
It seems you have an issue with your GraphQL server. Could you try with a simple `PubSub` from `graphql-subscriptions` without Redis?

**Comment by wansj** [comment]
@Akryum In fact, I had tried graphql-subscriptions originally and got the same result as RedisPubSub. By the way, my websocket server is listening at: localhost:5000/subscriptions and [micro](https://github.com/zeit/micro) server is listening at localhost:3000/graphql. I used split imported from [apollo-link](https://github.com/apollographql/apollo-link) to delegate subscription requests to websocket server and query/mutation requests to micro server. I thought graphql-subscriptions may be responsible for the problem, and that's why I turned to use RedisPubSub. I'll tried RedisPubSub again.

**Comment by wansj** [comment]
I tried graphql-subscriptions again, nothing changed. It should output subscription data to chrome console when result callback was called. But it didn't.
**Code changes:**
<img width="506" alt="default" src="https://user-images.githubusercontent.com/3777800/37962716-912441c2-31ee-11e8-816c-9381908ab8e8.png">
**I sended a delete Book Mutation and got successful response:**
<img width="1047" alt="default" src="https://user-images.githubusercontent.com/3777800/37962942-59522c54-31ef-11e8-9bd1-21cacb95a0e5.png">
**But no subscription data flow to client through the established websocket connection:**
<img width="1426" alt="default" src="https://user-images.githubusercontent.com/3777800/37963130-ec14e608-31ef-11e8-90da-ea58b9f38267.png">

**Comment by Akryum** [comment]
It doesn't seem to receive the sub event. Do you have a full minimal reproduction to share on GitHub for example?

**Comment by wansj** [comment]
Sorry, I can't reproduce it. I've spended a whole night creating a reproduction, nearly the same code(simplified), but not the same result.The simplified reproduction project can be reactive to Book creation even without subscribeToMore or $subscribe. It seems that routing from /addBook to /books causes the AllBooksQuery refetch  books from server again. The delete button which locates at the /books page,  can't cause the AllBooksQuery refetch. But it can trigger the 'result' callback of $subscribe. In one word, the reproduction project works normally. I'll continue to figure out the differences between my project and reproduction.

**Comment by wansj** [comment]
It seems that defining $subscribe in ancestor components can also receive published data, while sibling components can not.

**Comment by Akryum** [comment]
In your reproduction, the HelloWorld component is destroyed when you navigate to the `/addBook` route. You can both update the books query during the mutation with the `update` option ([example](https://github.com/Akryum/vue-apollo#mutations), [docs](https://www.apollographql.com/docs/react/essentials/mutations.html#update)) and use `fetchPolicy: 'cache-and-network'` on the HelloWorld component ([source](https://github.com/apollographql/apollo-client/blob/0882a809dc7381c7e95a17696130796d661d6678/packages/apollo-client/src/core/watchQueryOptions.ts#L9-L25)).

**Comment by wansj** [comment]
@Akryum Thanks for your reply. `fetchPolicy: 'cache-and-network'` works. But I don't understand why subscription on the `HelloWorld` component can't receive the published payload data originating from the `AddBook` component. It seems that they run in two thread. Otherwise, I don't need to change `fetchPolicy` from `cache-first` to `cache-and-network`.Just update the apollo cache in the `updateQuery` method of `subscribeToMore` and keep it up-to-date.

**Comment by Akryum** [comment]
As I said, the component is destroyed when you navigate to the other route, thus no longer running the subscription.

**Comment by wansj** [comment]
Got it, thank you for the explanation.I'll close this issue.
