### ISSUE TITLE
Multiple data from one query

### ISSUE THREAD

**Issue by apertureless** [Akryum/vue-apollo#249]
Sorry for the title. Not sure how to describe it best.

I have following query:

```gql
query allPalettes ($first: Int, $skip: Int, $orderBy: PaletteOrderBy) {
  allPalettes(first: $first, skip: $skip, orderBy: $orderBy) {
    id
    title
    colors
    votes {
      id
      user {
        id
      }
    }
  }
  totalCount: _allPalettesMeta {
    count
  }
}
```

So there are two datasets `allPallettes` and `totalCount`.
However I am not sure how to grab them in `vue-apollo`.

For a single node that would be simply:

```js
    apollo: {
      allPalettes: {
        query: ALL_PALETTES,
        variables: {
          skip: 0,
          first: PALETTES_PER_PAGE
        },
        loadingKey: 'loading'
      },
```

However this way I am not getting `totalCount`. It is working if I duplicate the query:

```js
    apollo: {
      allPalettes: {
        query: ALL_PALETTES,
        variables: {
          skip: 0,
          first: PALETTES_PER_PAGE
        },
        loadingKey: 'loading'
      },
      totalCount: {
        query: ALL_PALETTES,
        variables: {
          skip: 0,
          first: PALETTES_PER_PAGE
        },
        loadingKey: 'loading'
      }

```

However this feels kind of wrong. Is there a better way?

**Comment by Akryum** [comment]
Use `result` hook (see the [docs](https://github.com/Akryum/vue-apollo#advanced-options)).

**Comment by apertureless** [comment]
Thanks!

**Comment by dorian-marchal** [comment]
> Use `result` hook (see the [docs](https://github.com/Akryum/vue-apollo#advanced-options)).

I got the same question but the link is out of date.
I think the documentation is now here: https://apollo.vuejs.org/api/smart-query.html#options

```js
{
  query: gql`...`,
  manual: true,
  result ({ data, loading }) {
    if (!loading) {
      this.items = data.items
    }
  },
}
```

**Comment by yosh-ar** [comment]
buen día, hace algunos días he estado trabajando con vue, laravel y apollo y me encontrado con el siguiente problema.

estoy trantando de hacer un OrderBy en mi consulta Graphql y hasta el momento todo funciona a nivel Graphql Playground
pero cuando quiero implementarlo con vue y apollo no he podido. 

adjunto mi codigo quiza alguien pueda ayudarme.

![graphql](https://user-images.githubusercontent.com/46854447/104824184-5ba48c00-5815-11eb-895d-617fae2e96ab.png)
![vue](https://user-images.githubusercontent.com/46854447/104824187-62330380-5815-11eb-9357-41a84460c341.png)
