### ISSUE TITLE
Scaphold.io GraphQL starter kit app

### ISSUE THREAD

**Issue by kristianmandrup** [Akryum/vue-apollo#25]
I'm trying to create a hello world sample app for how to use Vue2 with Scaphol.io GraphQL service using your lib [here](https://github.com/kristianmandrup/vue2-apollo-scaphold)

I'm not sure how to read your docs, which GraphQL queries to add to the `apollo` Component property Object.

Please have a look at:

Mutations can be used standalone without being wrapped in `apollo` "container" ?

https://github.com/kristianmandrup/vue2-apollo-scaphold/blob/master/src/js/vue/components/App/App.vue#L77

https://github.com/kristianmandrup/vue2-apollo-scaphold/blob/master/src/js/vue/components/App/Login.vue#L49

https://github.com/kristianmandrup/vue2-apollo-scaphold/blob/master/src/js/vue/components/App/Register.vue#L54

Subscriptions:

https://github.com/kristianmandrup/vue2-apollo-scaphold/blob/master/src/js/vue/components/App/App.vue#L116

https://github.com/kristianmandrup/vue2-apollo-scaphold/blob/master/src/js/vue/components/App/App.vue#L126

I guess the subscription logic has to go in `apollo.subscriptions` and be referenced via `this.$apollo` ?

**Comment by Akryum** [comment]
- Mutations are actions and have to be used in the logic code (for example, inside methods). I didn't find useful to allow to declare them in the `apollo` option, but if we can find a use case for it, why not.
- Subscriptions can be declared in the `subscription` option inside the `apollo` option for convenience. In most cases, you shouldn't have to access them in your logic code after that.
