### ISSUE TITLE
Apollo-link-state

### ISSUE THREAD

**Issue by sandman18** [Akryum/vue-apollo#253]
I can’t seem to connect Apollo-link-state to a component?  The example on Apollo’s website is for react. Any suggestions?

**Comment by chriswingler** [comment]
Here's how we got it working:

https://codesandbox.io/s/zqqj82396p

**Comment by Akryum** [comment]
Added a section about local state [in the docs](https://github.com/Akryum/vue-apollo#local-state). Thanks @chriswingler for the example!
