### ISSUE TITLE
Question: Can I use the results from an apollo query from inside a computed property?

### ISSUE THREAD

**Issue by marcovc** [Akryum/vue-apollo#254]
Is this OK so far?

    export default {
        apollo: {
            reliability: {
                query: getReliabilityQuery,
            },
        },
        computed: {
            cReliability()  { return this.reliability; }
        }
    },

If it is, then I'll have further questions. 

Thanks.

**Comment by Akryum** [comment]
Yes.

**Comment by marcovc** [comment]
Thank you @Akryum,

As I understand it, for the code above, the first time cReliability property is accessed it will be null and as a side effect apollo will trigger a query. When the result of query is available, the cReliability is updated and any reactive things that depend on cReliability will be updated.

Is this how it works?

Thanks

**Comment by Akryum** [comment]
Yes.

**Comment by marcovc** [comment]
Ok great, thank you @Akryum !
