### ISSUE TITLE
[question] is there way to abort query in real time

### ISSUE THREAD

**Issue by ojczeo** [Akryum/vue-apollo#259]
@Akryum is there any way to abort query during executing, for example when reactive variables changes?
for now query is loading, even when variable is changed. I'm using `debounce` for debouncing inputs, anyway sometimes I would like force Apollo to stop request when variable has been changed.

**Comment by Akryum** [comment]
`fetch` requests c'ant be cancelled.

**Comment by thomasaull** [comment]
For anyone searching for this, in the meantime it is indeed possible to cancel fetch requests by using an `abortController`. For details check: https://evilmartians.com/chronicles/aborting-queries-and-mutations-in-react-apollo

And here is a quick example of how I did it in a project (with vue-apollo v2):
```js
const abortController = new window.AbortController()

this.$apollo.query({
  query: MyQuery,
  context: {
    fetchOptions: {
      signal: abortController.signal,
    },
  },
})

setTimeout(() => {
  abortController.abort()
}, 500)
```
