### ISSUE TITLE
Query execution hangs after a failed query

### ISSUE THREAD

**Issue by miel-dev0** [Akryum/vue-apollo#260]
Hello. Thank you for the exellent library.

One of components I'm currently building takes a user-inputted string as prop and use it as a query variable.

The GraphQL endpoint responds with an error if passed string is too short, or otherwise considered invalid (such as SQL injection).

If a GraphQL or network error occurs, the error itself is propagated correctly, but subsequent query hangs - $apolloData.loading is set to 1 and $apolloData.queries.[...].loading is set to true, without any actual request to the server being made.

```
searchAddress: {
  query: addressSearch,
  variables(): AddressSearchQueryVariables {
     return {
        keyword: this.keyword
     };
   }
}
```

**Comment by marcovc** [comment]
I have this problem also. Did you find any workaround? Thanks

**Comment by miel-dev0** [comment]
Unfortunately, No, I am forced to fall back to 2.1.0 at the moment. It seems this bug was introduced in version 3.

**Comment by marcovc** [comment]
Thanks for your reply. Interestingly, I just downgraded vue-apollo to version 2.1.0-rc.5 and the bug is still there. Must be in one of its dependencies...

**Comment by romain-web** [comment]
Hi, I found some same issue in [react-apollo issues](https://github.com/apollographql/react-apollo/issues/1385) and I have the same problem, I think the problem came with apollo-client a PR was [here](https://github.com/apollographql/apollo-client/pull/2871) and can solve the problem but not merged for the moment

**Comment by Akryum** [comment]
I think this is an upstream issue in apollo client as you pointed out.
