### ISSUE TITLE
refetch must be called to pass query variable if variable is prop

### ISSUE THREAD

**Issue by chriswingler** [Akryum/vue-apollo#262]
`this.$apollo.queries.hello.refetch({ name: namedProp })`

the scenario is:

- graphql query with a variable given the value of a prop
- component that is re-rendered in different routes with different prop values
- when component is re-rendered with a new prop value, apollo runs the query again, but does not update the value of the variable with the new prop value
- by calling the refetch, you are able to force the variable to update

**Comment by Akryum** [comment]
See https://vue-apollo.netlify.com/guide/apollo/queries.html#reactive-parameters
