### ISSUE TITLE
State not available in variables function

### ISSUE THREAD

**Issue by mbajur** [Akryum/vue-apollo#267]
Hello,

i have a nuxtjs app using vue-apollo for fetching backend data. This app is multilingual (one domain = one language) and i'm setting my language based on domain used in the vuex store. It's handled by a middleware module:

```
export default function ({ req, app, store, route, error, redirect, hotReload }) {
  // Check if middleware called from hot-reloading, ignore
  if (hotReload) return

  const hosts = {
    'en.website.127.0.0.1.xip.io:3000': 'en',
    'beta.website.com': 'en',

    'website.127.0.0.1.xip.io:3000': 'pl',
    'beta.website.pl': 'pl',
  }

  let locale = 'pl'
  let host = process.server ? req.headers['host'] : location.host

  if (hosts[host] !== undefined) {
    locale = hosts[host]
  }

  store.dispatch('i18n/setLocale', locale)
}

```

And all of this works great so far. Things gets tricky when i want to use that vuex-state `locale` to filter records returned by grpahql endpoint.

My apollo query code looks more or less like that:

```
apollo: {
    nodeQuery: {
      query: allCampaignsQuery,
      prefetch: true,
      variables () {
        return {
          filter: {
            type: "campaign",
            langcode: (this.$store) ? this.$store.state.i18n.locale : 'pl'
          }
        }
      }
    }
  },
```

And the thing is - when user enters that page, vue-apollo can't see the store (`this.$store = undefined`) so i need to do that inline if thing. Then, vue-apollo prefetches the query using the default language code (`pl`). After that, middleware changes the locale based on domain (why so late? Shouldn't that be done way earlier before everything else?) and vue-apollo see the change in the store `locale` so it refetches the query with new langcode filter. 

That's totally wrong as i need this thing to be prefetched in a proper language in a first place instead of doing two requests while the second is done by browser. I hope it's something easy and i just misunderstood something simple.

Thanks in advance!

**Comment by Akryum** [comment]
Use the `prefetch` option: https://github.com/Akryum/vue-apollo#prefetch-components
