### ISSUE TITLE
keep-alive router starting cached queries

### ISSUE THREAD

**Issue by Samuell1** [Akryum/vue-apollo#27]
Hey, I have some weird things happening. If I am using keep-alive on router apollo is doing cached requests from other routes.

**Example:**
If I open user route it's okay, but if I open other route from user route, apollo does the user route query again.

**Comment by mcesar** [comment]
Is there any workaround for this problem?

**Comment by Samuell1** [comment]
@mcesar i removed keep-alive for temp fix

**Comment by Akryum** [comment]
Do you have a reproduction link?

**Comment by Samuell1** [comment]
@Akryum i cant post repo its private, but i can create some example repo this week

**Comment by Samuell1** [comment]
@Akryum i tested it with new versions, its still doing :/

**Comment by Samuell1** [comment]
https://github.com/vuejs/vue/issues/5346 Maybe its because this?

**Comment by Akryum** [comment]
Please reopen if you still have the issue.

**Comment by ValdoGhafoor** [comment]
Hello everyone
I have the issue also using vue-apollo 3.0.0-beta.25

**Comment by samueleiche** [comment]
Hello
Same issue in our project using vue-apollo 3.0.7.
We solved it using skip() and $skipAll() - if our component is a view, we skip it if the active route is not the view route:
```
mySubscription: {
		skip() {
			return this.$route.name !== 'my.view.route.example'
		},
		...
},
```
But this is not a complete solution and we are looking to improve this workaround.
