### ISSUE TITLE
Conceptual issue: how to handle child components with vue-apollo

### ISSUE THREAD

**Issue by Fohlen** [Akryum/vue-apollo#271]
Hey there folks.
I am struggling to find a nice architecture with `vue-apollo`.
Currently I have a setup like this:

```
App.vue
Calendar.vue <-- has apollo queries, pushes to Vuex store
Event.vue <-- uses Vuex getters to use data pushed by Calendar.vue
```

Now, this works fine if your user goes the following way: 
- initializes App
- uses `/calendar` route
- this populates `Vuex` store
- uses `/calendar/event/:id` route
- accesses previously initialised Vuex Store 🔢 

Now comes the fun. `Event.vue` is a child component of `Calendar.vue`, but I wouldn't want to render it via `<render-view>` inside my `Calendar`, for obvious reasons. 
This means, that when I access the route directly, it will result in an empty store.
Usually one would fall back either to the `created` hook, or `navigation guards`, and simply re-populate the Store if it is empty.
This however is not easily possible with `VueApollo`. I tried to do the following:

```
import Vue from 'vue' 
import Calendar from ' ./Calendar.vue'

export default {
    created() {
        if (!this.$store.getters.events.length) {
           let CalendarComponent = Vue.extend(Calendar)
           let calendar = new CalendarComponent()
           calendar.$apollo.queries.events.refetch() # <- here comes the fun. Events query does not exist
       }
       this.event = this.$store.getters.eventById(this.$route.params.id) // needs a pre-populated list, obviously
    }
}
```

How could one achieve this sanely with `VueApollo`? I've been trying various other ways, but the only thing I could come up with is Mixins. But. This would be essentially bad because

- one would mix up the original component that is designed to do the query
- this effectively destroys all decoupling
- doing things like reactive queries with mixins may become an unpredictable mess
- (...) the list can go on for a while

I hope somebody has an idea how this could be achieved.
Regards, Fohlen

**Comment by Akryum** [comment]
What about this:
- Don't use vuex for this
- Use the same GraphQL query on multiple components (Apollo is smart)

**Comment by Fohlen** [comment]
@Akryum well this does of course work but leads to non-DRY code and overly complicated structure. I'll close it for now because it is of no more interest to me but generally there could be some work done.
