### ISSUE TITLE
receiving error if _this.$props is not defined

### ISSUE THREAD

**Issue by dohomi** [Akryum/vue-apollo#275]
Hello

the current Beta-9 results in following error of _loop function:

`TypeError: Cannot read property 'hasOwnProperty' of undefined
    at _loop`

Responsible for this error is that `_this.$props` is undefined. 

https://github.com/Akryum/vue-apollo/blob/master/src/index.js#L43

**Comment by dohomi** [comment]
Downgrading to `3.0.0-beta.5` is fixing the issue for me at the moment. @Akryum not sure why `$props|$data` is undefined in my code but it happens on route transition. Is it possible to change the lines to not rely that props or data is present?

**Comment by loitran** [comment]
Running into same issue. Was able to get around it by adding `props: []`

**Comment by dohomi** [comment]
@loitran where did you place the props:[]? I use vue-apollo combined with Nuxt and the current beta.9 is not working for me currently

**Comment by loitran** [comment]
@dohomi place it in your vue component.

`export default {
  name: 'organizations',
  props: [],
  apollo: {}
}`

I'm running 3.0.0-beta.9

**Comment by dohomi** [comment]
@loitran that is more-less not really an option for me. I use apollo quite extensively on https://github.com/lumen-cms/lumen-cms and for example in the usage with NuxtJs `pages` will never use props by nature

**Comment by loitran** [comment]
@dohomi @Akryum submitted a pull request with a fix.

https://github.com/Akryum/vue-apollo/pull/279
