### ISSUE TITLE
Grep http status codes from query result

### ISSUE THREAD

**Issue by DeroSavage** [Akryum/vue-apollo#277]
Hey there,

i'm trying to fetch the status code from the error obj but it seems that it is not possible. 
`    // Error handling
    error(error) {
      console.error('We\'ve got an error!', error)
    },`

How do i get the code in this function?

**Comment by jpikora** [comment]
Hi, try like this:

```
error ({ graphQLErrors, networkError }) {
  console.log(networkError.statusCode)
}
```

**Comment by DeroSavage** [comment]
@jpikora  works like a charm :3 Thanks!
