### ISSUE TITLE
why is force fetch set when starting?

### ISSUE THREAD

**Issue by manukall** [Akryum/vue-apollo#28]
hi,

i'm using the same query in 4 components of my app. this leads to the query being run 4 times when my app loads. i suspect that the following code in `SmartQuery` is the reason:

```javascript
if (this.starting) {
  this.options.forceFetch = true
}
```

so i'm wondering what the purpose of the force fetching is. why is it necessary to set this here?

**Comment by Akryum** [comment]
You are right, this is an error. 🍰

**Comment by manukall** [comment]
wow, that was quick. thanks!

also, i'm wondering if you have an opinion on unit testing components that use vue-apollo. right now i'm just not including apollo in my components during tests (i only `Vue.use(apollo)` when not in the test environment). does that make sense? is there a better approach?

**Comment by Akryum** [comment]
I think it's fine if you inject the data you would normally receive via Apollo. Maybe there are things to do to simulate a request (to test the component behavior with `loadingKey` changing from 1 to 0 for example).

**Comment by manukall** [comment]
thanks again! i tried stubbing `fetch` first. that worked as well but was a lot of work for when i wasn't actually testing apollo related things as well. i'm happier with skipping apollo in tests now :-)
