### ISSUE TITLE
Apollo Client caching information I don't want cached!

### ISSUE THREAD

**Issue by romucci** [Akryum/vue-apollo#285]
Hi there guys!
I am using apollo client for my vue app, but for example this happens:

1 - I login with an account.
2 - Navigate inside a component via vue-router.
3 - A query for a product list gets triggered.
4 - I logout.
5 - I login inside another account. (The queries are fetched by current User ID)
6 - I navigate to the same component via vue-router.
7 - I see the information from the other account for a split second and then the information from the current user appears.

I tried client.resetStore() and client.cache.clear() or client.cache.data.clear().

```
methods: {
    logout () {
      Object.values(this.$apollo.provider.clients)
        .forEach(client => client.cache.data.clear())
      sessionStorage.clear()
      localStorage.clear()
      this.$store.state.user = null
      this.$store.state.token = null
      this.$store.state.isUserLoggedIn = false
      this.$router.push('/login')
    }
  }
```
Nothing worked. :)

**Comment by paulpdaniels** [comment]
This sounds like it should be on the `apollo-client` repo then...

**Comment by romucci** [comment]
I don't actually know if its apollo client or vue-apollo causing the issue, anyway, I fixed it by emptying the objects and arrays when the component gets deactivated hAHHA
