### ISSUE TITLE
How to know the first time a query has run

### ISSUE THREAD

**Issue by JasonLi914** [Akryum/vue-apollo#287]
I have logic that I want to execute only once after the first time a query has resolved. I'm wondering if people have ideas on how to do something like this that does not involve setting some sort of flag.

**Comment by ScreamZ** [comment]
Simple example: 

1. Store a boolean in your component data.
2. Use apollo `result(ApolloQueryResult)` hook in order to update your boolean data.
3. You're done.

Have fun.
Regards

**Comment by JasonLi914** [comment]
Yeah thinking about my question more it seemed like a flag is correct here, not sure why I was so averse to it I tend to just dislike flags irrationally haha, thank you for your answers.
