### ISSUE TITLE
fetched data is immutable?

### ISSUE THREAD

**Issue by DreaMinder** [Akryum/vue-apollo#29]
I successfuly fetched an array from server, it stores in vue data. But when  I'm trying to modify it, I getting an error: 
`vuedraggable.js?bcd0:177 Uncaught TypeError: Cannot add/remove sealed array elements`
What should I do by design of apollo?  Clone this array in mutable one?

**Comment by Akryum** [comment]
The point is, apollo is designed to work with live queries, and the data may be updated at any time so you shouldn't modify it locally. What is your use case?

**Comment by DreaMinder** [comment]
I have a drag & drop list that renders from the fetched array. User should have ability to change it's elements sort.
But... if apollo restricts fetched data modification without some kind of solution, there are other use cases that wouldn't work as I thought. For example, v-model forms

**Comment by Akryum** [comment]
Well, you can call Apollo mutations when it is dragged (with optimistic response). Or you can clone objects when you enter the form. The thing is, the data is reactive and may be replaced by a newer version at any time.

**Comment by DreaMinder** [comment]
The thing is... I can't call mutations on non-cloned array. Even if I don't need to save list order to server, it's order can't be changed just in users' view.
Anyway, thanks for help, sorry for my English =)
