### ISSUE TITLE
Unknown custom element: <ApolloQuery> error

### ISSUE THREAD

**Issue by ganimp84** [Akryum/vue-apollo#290]
I am trying the following piece of code from Sara Vierra's blog

https://medium.com/yld-engineering-blog/using-vue-with-apollo-65e2b1297592

```
<template>
  <ApolloQuery :query="query" :variables="{ name: 'vue' }">
    <template slot-scope="{ result: { loading, error, data } }">
      <span v-if="loading">Loading...</span>
      <span v-else-if="error">An error occured</span>

      <section v-if="data">
          <ul v-if="data.allNameses.length">
            <li :key="name.id" v-for="name in data.allNameses" >
              {{name.name}}
            </li>
          </ul>
          
           <span v-else>No names, oh no :(</span>
      </section>
    </template>
  </ApolloQuery>
</template>

<script>
import { GET_NAMES } from "../queries.js";
export default {
  name: "Names",
  data() {
    return {
      query: GET_NAMES
    };
  }
};
</script>

<style scoped>
</style>
```

But, currently facing this error,

> [Vue warn]: Unknown custom element: <ApolloQuery> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I was assuming ApolloQuery is a globally registered component. Could help to understand what's missing?

Below is the dependencies list in package.json for reference,

```
"dependencies": {
    "apollo-boost": "^0.1.6",
    "apollo-cache-inmemory": "^1.2.1",
    "apollo-client": "^2.3.1",
    "axios": "^0.18.0",
    "graphql": "^0.13.2",
    "vue": "^2.5.11",
    "vue-apollo": "^3.0.0-beta.10",
    "vue-axios": "^2.1.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-3": "^6.24.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "file-loader": "^1.1.4",
    "vue-loader": "^13.0.5",
    "vue-template-compiler": "^2.4.4",
    "webpack": "^3.6.0",
    "webpack-dashboard": "^1.1.1",
    "webpack-dev-server": "^2.9.1"
  }
```

Thanks

**Comment by Akryum** [comment]
We need a full minimal reproduction on a repository to know what your issue is.

**Comment by ganimp84** [comment]
Hi, I have managed to get it working. 

here is the repo,
https://github.com/ganimp84/vue-apollo-example

**Comment by mrcasablr** [comment]
@ganimp84  I have the same error.  How did you get this working? Do you know what caused this?

**Comment by sumansarkarwd** [comment]
> @ganimp84 I have the same error. How did you get this working? Do you know what caused this?

I had the same problem.. Turns out I had a type.. Instead of Vue.use(VueApollo), I had Vue.use(apolloProvider)
