### ISSUE TITLE
default fetchPolicy not being applied

### ISSUE THREAD

**Issue by orocancourt** [Akryum/vue-apollo#291]
The documentation mentions we can set a default `fetchPolicy` for all requests, except it doesn't seem to work : whatever policy I put in the `defaultOptions.$query.fetchPolicy` in VueApollo provider is ignored.
After having a closer look to network calls, it seems the `'cache-and-network'` policy is applied, whatever default value I pass

However, overriding this default value in components queries works fine, but still I'd like to avoid repeating the fetchPolicy for every query I write and set it globally

Using 3.0.0-beta.11, with the following snippet :

```
export default new VueApollo({
  defaultClient: new ApolloClient({
    link: ApolloLink.from([
      ...
    ]),
    cache: new InMemoryCache(),
  }),
  defaultOptions: {
    $query: {
      fetchPolicy: 'no-cache',
    },
  },
})
```

Am I missing something ? 
Best regards

**Comment by Akryum** [comment]
Please update to latest release and report back if you still have the issue.

**Comment by orocancourt** [comment]
3.0.0-beta.11, which i'm using, is actually the latest release

**Comment by Akryum** [comment]
Latest is beta.13

**Comment by orocancourt** [comment]
Aahh sorry, was checking from your github releases instead of NPM

Moving to beta.13 solved the problem, thanks ! :)

**Comment by Sceat** [comment]
Hum npm was not updating, i tried manually both `rc.2` and `rc.4` but still have the issue, (using `vue-cli-plugin-apollo` btw)

Doing this make only one query and then no more until i reload the page

```js
// Create vue apollo provider
	const apolloProvider = new VueApollo({
		defaultClient: apolloClient,
		defaultOptions: {
			$query: {
				fetchPolicy: 'no-cache'
			}
		},
		errorHandler(error) {
			console.log('%cError', 'background: red; color: white; padding: 2px 4px; border-radius: 3px; font-weight: bold;', error.message)
		}
	})
```

doing this correctly remake the query everytime

```js
await apolloClient.query({
		variables: {
			email
		},
		query: gql`
			query($email: String!) {
				createResetCode(email: $email)
			}
		`
	})
```
