### ISSUE TITLE
production bulid fails

### ISSUE THREAD

**Issue by mygnu** [Akryum/vue-apollo#3]
I have adapted the example in my setup dev server runs fine but production build has the following error. please let me know if you need more information??
Great work btw!

`Hash: 309b2fe3f5f6a95a4d0c
Version: webpack 2.1.0-beta.20
Time: 4002ms
                  Asset       Size  Chunks             Chunk Names
     client.efaf137e.js    49.9 kB       0  [emitted]  client
     vendor.699ece51.js     852 kB       1  [emitted]  vendor
    styles.1c7b9d16.css  724 bytes       0  [emitted]  client
styles.1c7b9d16.css.map   96 bytes       0  [emitted]  client
 vendor.699ece51.js.map    1.06 MB       1  [emitted]  vendor
             index.html  383 bytes          [emitted]  
  [88] multi vendor 64 bytes {1} [built]
    + 92 hidden modules

ERROR in vendor.699ece51.js from UglifyJs
__SyntaxError: Unexpected token: name (apolloClient) [vendor.699ece51.js:30261,4]__`

**Comment by Akryum** [comment]
Fixed in [v1.0.0-beta.11](https://github.com/Akryum/vue-apollo/releases/tag/v1.0.0-beta.11)
