### ISSUE TITLE
apollo package is too big

### ISSUE THREAD

**Issue by xpepermint** [Akryum/vue-apollo#30]
This is not directly related to `vue-apollo` but because I write `vue` application I decided to address this issue here.

My Vue application file size (the final `build.js`) is around **250KB** (the whole application). When I attach `vue-apollo` and `apollo-client`, the file size exceeds to **350KB**. Apollo client equips you with powerful tools but `100KB+` well... I would say this is huge. 

What can we do about that?

**Comment by Akryum** [comment]
Did you try measuring this with gzip enabled?

**Comment by xpepermint** [comment]
@Akryum unfortunately not. This is the minified size that I'm talking about. I believe gzip should be just an additional optimization.

**Comment by Akryum** [comment]
gzipping should reduce the size of your app significantly.

**Comment by Akryum** [comment]
Here is an example on upnkg.com for unminified version of apollo-client:
![image](https://cloud.githubusercontent.com/assets/2798204/23121520/0771cdaa-f761-11e6-9689-0168f2d938e6.png)

**Comment by stubailo** [comment]
Yeah Gzip is definitely not optional IMO - almost every single library is assuming people use Gzip when measuring bundle size. Otherwise people writing code have to worry about doing really fine-grained optimizations that are much better handled by a machine.

**Comment by xpepermint** [comment]
ok, got it :)

**Comment by iamfrntdv** [comment]
Gzip doesn't reduces amount of js to be parsed. Not every server can use gzip.
