### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by archSeer** [Akryum/vue-apollo#301]
```
[Show/hide message details.] ReferenceError: regeneratorRuntime is not defined

app.js line 9278 > eval:1678:7
mutate
vue-apollo.esm.js:1667
mutate self-hosted:981:17 submit
PasswordReset.vue:65
invoker
vue.runtime.esm.js:2023
withMacroTask/fn._withTask
vue.runtime.esm.js:1822
```

**Comment by Samuell1** [comment]
@archSeer do you tried beta-16?

**Comment by archSeer** [comment]
Beta 16 is broken for me because of #295.

**Comment by archSeer** [comment]
Tried on beta 17, still broken, I'm just using a basic vue-cli 3 setup.

**Comment by Samuell1** [comment]
Do you have beta-17 in package-lock?

**Comment by fnoop** [comment]
I'm also seeing this while using onLogin to set an auth token:

<img width="645" alt="screenshot 2018-12-31 at 08 29 55" src="https://user-images.githubusercontent.com/8210968/50556854-516ad000-0cd6-11e9-9a8a-5f957e727f02.png">

**Comment by fnoop** [comment]
https://github.com/babel/babel/issues/5085

**Comment by fnoop** [comment]
Fixed for me by doing:
```
yarn add --dev @babel/plugin-transform-runtime
yarn add --dev @babel/core
```

and then in babel.config.js:
```
module.exports = {
  presets: ['@vue/app'],
  plugins: [
    "@babel/transform-runtime"
  ]
}
```

**Comment by Sameer447** [comment]
**Solved**
$ npm install --save-dev babel-plugin-transform-runtime
then In .babelrc, add the runtime plugin
{
  "plugins": [
    ["transform-runtime", {
      "regenerator": true
    }]
  ]
}
thanks me later

**Comment by Fahmiin-Abdullah** [comment]
Another solution for those stumbling to this error too
```
npm i -S core-js@latest regenerator-runtime@latest
```

Then in your Vue `main.js` file
```
// Import these two at the top
import 'core-js/stable'
import 'regenerator-runtime/runtime'
...
```
