### ISSUE TITLE
Update hook always triggered?

### ISSUE THREAD

**Issue by ebisbe** [Akryum/vue-apollo#303]
I'm trying to understand if the Update Hook will always be triggered? I'm trying to catch when an errors arises in the query but the update hook is triggered and I have to do something like this:

```
apollo: {
    userPhotos: {
      query: STREAM_QUERY,
      variables() {
        return {
          userId: this.userId,
          offset: itemsPerPage
        }
      },
      update: data => (data.hasOwnProperty('userPhotos') === 0 ? data.userPhotos : []),
      error() {
        this.error = 'Ups! Some error happened fetching your data...'
      }
    }
  },
```

Is this due to some graph QL standard that I'm not aware of?

**Comment by Samuell1** [comment]
Is your stream query same name?

**Comment by Akryum** [comment]
In GraphQL, you can get data and errors at the same time.

**Comment by ebisbe** [comment]
@Samuell1 Yes the loader is not the problem. I have just turned off the graphql server to try the errors.

@Akryum After been fighting is what I was thinking. Do you have any link with information related to that behaviour? It's all in the apollo?

thanks

**Comment by Akryum** [comment]
http://facebook.github.io/graphql/October2016/#sec-Response
