### ISSUE TITLE
ApolloQuery Component

### ISSUE THREAD

**Issue by Simskii** [Akryum/vue-apollo#316]
Instead of 
`
<ApolloQuery
  :query="require('../graphql/HelloWorld.gql')"
  :variables="{ name }"
`

How can use avoid using gql files and just use my imported query which is already transformed by graphql-tag?
For example 
`import {HelloWorld} from '@/graphql/queries
<ApolloQuery
  :query="HelloWorld"
  :variables="{ name }"
`

**Comment by jpikora** [comment]
You will have to reference imported query through data on component, e.g.

```
<apollo-query :query="queries.hello"></apollo-query>
```

```
import HELLO_QUERY from '@/graphql/queries'

export default {
  data () {
    return {
      queries: {
        hello: HELLO_QUERY
      }
    }
  }
}
```

**Comment by Simskii** [comment]
Yeah, That works. 
Thanks!

**Comment by kode8** [comment]
> queries: { hello: HELLO_QUERY }

Nice way of doing it dude
