### ISSUE TITLE
$apollo.queries.[myquery].refresh() doesn't return a promise

### ISSUE THREAD

**Issue by dimitri-koenig** [Akryum/vue-apollo#317]
Hi there

Using this.$apollo.mutate or this.$apollo.query I get a promise returned, but that's not the case for using $apollo.queries.[myquery].refresh(). Would be awesome if I could call that method and wait for a response till I alert the visitor of the refreshed list.

Any idea where to start this?

**Comment by jpikora** [comment]
I believe the function you are looking for is not `refresh` (used internally by vue-apollo to provide reactive requests), but `refetch` which will rerun the query and return a promise.

**Comment by dimitri-koenig** [comment]
Perfect, thx.
