### ISSUE TITLE
Is there interceptor or middleware here? 

### ISSUE THREAD

**Issue by wdysuccess** [Akryum/vue-apollo#322]
How can i interception the http request，for example 401.

**Comment by Akryum** [comment]
https://github.com/apollographql/apollo-link

**Comment by wdysuccess** [comment]
Thank you very much.

**Comment by emahuni** [comment]
What I intend to do is intercept all GraphQL queries to check on a common error my server throws for certain reasons, eg: USER NOT FOUND 

Then act on it globally in the frontend app.

I am still wondering how to do this, any help? I guess this could be great if written in the Docs also.

**Comment by emahuni** [comment]
Ok thanks I saw this: 

```
import { ApolloLink } from "apollo-link";
import { createHttpLink } from "apollo-link-http";
import { onError } from "apollo-link-error";

import { logout } from "./logout";

const httpLink = createHttpLink({ uri: "/graphql" });
const errorLink = onError(({ networkError }) => {
  if (networkError.statusCode === 401) {
    logout();
  }
});

// use with apollo-client
const link = errorLink.concat(httpLink);
```

going to give it a try.

**Comment by seandelaney** [comment]
@emahuni 

`import { logout } from "./logout";`

Can I see your `logout` ?

I need to access the Vuex store but unsure.
