### ISSUE TITLE
The composite identifier _id in the query replicates the first object [bug]

### ISSUE THREAD

**Issue by gustawdaniel** [Akryum/vue-apollo#326]
# Bug Report

Lets consider the following schema:

```
type KanbanId {
  user: String
  kanban: String
}

type KanbanList {
  _id: KanbanId
  count: Int
}

type Query {
  kanban_board: [KanbanList]
}
```

And simple resolver for `kanban_board` that return array

```
[
                {
                    "_id": {
                        "user": "u_1",
                        "kanban": "open"
                    },
                    "count": 1
                },
                {
                    "_id": {
                        "user": "u_2",
                        "kanban": "closing"
                    },
                    "count": 2
                }
]
```

Next when we use graphiql (graphical interface for testing queries) we can ask 

    {kanban_board {_id {user, kanban}, count}}

```
{
  "data": {
    "kanban_board": [
      {
        "_id": {
          "user": "u_1",
          "kanban": "open"
        },
        "count": 1
      },
      {
        "_id": {
          "user": "u_2",
          "kanban": "closing"
        },
        "count": 2
      }
    ]
  }
}
```

Of course simplest question (without `_id`) is solved correctly too

    {kanban_board { count}}

```
{
  "data": {
    "kanban_board": [
      {
        "count": 1
      },
      {
        "count": 2
      }
    ]
  }
}
```

These was examples of expected behavior. Unfortunately using this lib we can see that for code:

```
import gql from 'graphql-tag'
export default {
        apollo: {
            kanban_board: gql`{kanban_board { _id {user, kanban}, count } }`
        },
}
```

we obtain the following results

```
[
  {
    "count": 1,
    "_id": {
      "user": "u_1",
      "kanban": "open",
      "__typename": "KanbanId"
    },
    "__typename": "KanbanList"
  },
  {
    "count": 1,
    "_id": {
      "user": "u_1",
      "kanban": "open",
      "__typename": "KanbanId"
    },
    "__typename": "KanbanList"
  }
]
```

First object is replicated. For case:

```
import gql from 'graphql-tag'
export default {
        apollo: {
            kanban_board: gql`{kanban_board { count  } }`
        },
}
```

We have correct result:

```
[
  {
    "count": 1,
    "__typename": "KanbanList"
  },
  {
    "count": 2,
    "__typename": "KanbanList"
  }
]
```

# Analysis

Probably it can be connected with cashing. If _id is projected into string then "[object]" string is equal another "[object]". It can be connected with 

> https://github.com/apollographql/apollo-cache-persist/issues/19

Special treatment of _id is described here:

> https://github.com/apollographql/apollo-client/blob/2cd695fda1085aa957dde1d632bf3b08738b5036/packages/apollo-cache-inmemory/README.md#normalization

But omitting compound _id is probably in disagree with original docs

> https://graphql.org/learn/schema/#scalar-types

where ID is distinguished from string and described as

> ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.

**Comment by Akryum** [comment]
You need to setup `dataIdFromObject` (from [here](https://github.com/apollographql/apollo-client/blob/2cd695fda1085aa957dde1d632bf3b08738b5036/packages/apollo-cache-inmemory/README.md#normalization)).

**Comment by gustawdaniel** [comment]
I solved by configuring `apollo-cache-persist`. Thank you @Akryum 

```
import Vue from 'vue'
import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import VueApollo from 'vue-apollo'

const httpLink = new HttpLink({
    // You should use an absolute URL here
    uri: `${Meteor.settings.public.env === "prod" ? "https://v3.omnisys.pl" : "http://localhost:3000"}/graphql`,
});

// cache in memory package config
const cache = new InMemoryCache(
    {
        dataIdFromObject: object => {
            switch (object.__typename) {
                case 'KanbanList': return object.id && `${object._id.user}_${object._id.kanban}`; // use `key` as the primary key
                default: return object.id || object._id; // fall back to `id` and `_id` for all other types
            }
        }
    }
);

// Create the apollo client
const apolloClient = new ApolloClient({
    link: httpLink,
    cache,
    connectToDevTools: true,
});

// Install the vue plugin
Vue.use(VueApollo);

export const apolloProvider = new VueApollo({
    defaultClient: apolloClient,
});
```

**Comment by Akryum** [comment]
Missing a `_` here: `return object.id && `
