### ISSUE TITLE
ApolloQuery component could be a renderless component

### ISSUE THREAD

**Issue by gomezcabo** [Akryum/vue-apollo#341]
Hello everyone! 

My idea is basically let the component be a renderless component. Sometimes we don't want/need the ApolloQuery render any tag when used.

What I would do is to make set the default value of the `tag` prop to `undefined` and if the user provide a value for this prop, then render the tag. In any other case, just render the user default slot.

**Comment by jpikora** [comment]
True and even more relevant for `ApolloMutation`.

**Comment by Akryum** [comment]
Implemented
