### ISSUE TITLE
UpdateQueries do nothing

### ISSUE THREAD

**Issue by Samuell1** [Akryum/vue-apollo#35]
Hey, i have some updateQueries to update apollo cache but doesnt work.

Maybe this is related to https://github.com/apollographql/apollo-client/issues/1129 ?

Code:
```
        updateQueries: {
          animal: (previousQueryResult, { mutationResult }) => {
            return {
              animal: {
                ...previousQueryResult.animal,
                records: [mutationResult.data.createRecord, ...previousQueryResult.animal.records],
              }
            }
          }
        },
```

**Comment by Samuell1** [comment]
@Akryum Any plans to update to new apollo 8?

**Comment by Akryum** [comment]
It's planned.

**Comment by Samuell1** [comment]
@Akryum or maybe skip to 1.0rc https://dev-blog.apollodata.com/apollo-client-1-0-is-coming-23b74b13fbbb#.4g50jqacz

**Comment by Akryum** [comment]
Yup! :smile:

**Comment by Akryum** [comment]
See #42
