### ISSUE TITLE
How to implement connection to the database? question

### ISSUE THREAD

**Issue by rofiuddin15** [Akryum/vue-apollo#351]
I tried to connect vue-apollo to the database, the database used was postgresql, as a interface I used a sequelize tool, but I was confused where I had to place the settings. I put the dbconnection.js file in the utils folder in the apollo-server. please help. thanks.
This my code in dbconnection.js
```
import Sequelize from 'sequelize'

const sequelize = new Sequelize('database', 'postgres', 'Kambing1', {
    // gimme postgres, please!
    dialect: 'postgres',
    schema: 'pws',
    host: 'localhost'
})

const db = {
    // inisialisasi semua model disini
    crmaccount: sequelize.import('../models/crmaccount'),
}

db.sequelize = sequelize;
db.Sequelize = Sequelize;

export default db
```

**Comment by Slashgear** [comment]
Vue Apollo is a Vue plugin for helping people to insert GraphQL queries in a VueJS frontend App.
Your question is more about 
> "How to correctly generate a GraphQL server connected to a Postgresql base ?"

You will find many information in [Apollo Server Documentation](https://www.apollographql.com/docs/apollo-server/)
