### ISSUE TITLE
Catch Graphql Error

### ISSUE THREAD

**Issue by nasr18** [Akryum/vue-apollo#355]
Have to show the graphql error returned from the server to the user... 

![image](https://user-images.githubusercontent.com/7514936/43995662-c7e56cfc-9dcf-11e8-959f-cc47f0859e36.png)

the message also showing `GraphQL Error:`. How to remove that?

**Comment by Kocal** [comment]
How do you catch the error?

**Comment by nasr18** [comment]
finally got what I want.

**Comment by Kocal** [comment]
How did you do?

**Comment by bswank** [comment]
Try digging into the error a bit further @Kocal – there's more data that comes along with the object, and some of that data is a better error message. Here's my solution:

```javascript
const e = { error }
e.error.graphQLErrors.forEach(err => console.log(err.message))
```

**Comment by nasr18** [comment]
@Kocal use object destructuring method.....
`const { graphQLErrors, networkError } = err;`

**Comment by Kocal** [comment]
No need to be condescending, I'm just asking how did you resolve your problem in case of someone is having the same issue and seeking for a solution :slightly_smiling_face:
