### ISSUE TITLE
Handle dynamic where filter

### ISSUE THREAD

**Issue by jon-ht** [Akryum/vue-apollo#356]
Does somebody have an idea on how I can make a dynamic `where` filter ?

This is my use case :

In my filter I can have
- a name (which is used to filter by `firstName` or `lastName` or `birthName`)
- a country
- a start date
- an end date

<details>
<summary>My entity model</summary>

```
type Member {
  id: ID! @unique
  dateOfBirth: DateTime
  dateOfDeath: DateTime
  civility: CIVILITY
  firstName: String
  lastName: String
  birthName: String
  qualifier: String
  age: Int
  enabled: Boolean! @default(value: true)
  publishedAt: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!

  cities: [City!]!
}
```
</details>

## Queries

<details>
<summary>Query by name and city</summary>

```
query members($name: String, $zone: ID, $first: Int, $after: String) {
  membersConnection(
    first: $first
    after: $after
    where: {
      OR: [
        { AND: { firstName_contains: $name, cities_some: { id: $zone } } }
        { AND: { lastName_contains: $name, cities_some: { id: $zone } } }
        { AND: { birthName_contains: $name, cities_some: { id: $zone } } }
      ]
    }
  ) {
    aggregate {
      count
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        ...MemberListItem
      }
    }
  }
}
```
</details>

In this case if `$zone` is null, 20 results would be missing, and that's not what I want. To do so, I need to declare an other query with only `name filter`

<details>
<summary>Query by name only</summary>

```
query members($name: String, $first: Int, $after: String) {
  membersConnection(
    first: $first
    after: $after
    where: {
      OR: [
        { firstName_contains: $name }
        { lastName_contains: $name }
        { birthName_contains: $name }
      ]
    }
  ) {
    aggregate {
      count
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        ...MemberListItem
      }
    }
  }
}
```
</details>

----

And by default no filters are applied. By now, the only way that I see is to create a query by filter possibility, depending on what arguments are passed

**Comment by Slashgear** [comment]
That is not really an issue with Vue-Apollo but with your GraphQL query. You should look on optional arguments in GrapQL documentation.
