### ISSUE TITLE
How to call query manually？

### ISSUE THREAD

**Issue by jumpingfrog0** [Akryum/vue-apollo#36]
If I define a query below:

```
apollo: {
	getTickets: {
		query() {
			return ticketQuery
		} ,
		variables() {
			return {
				offset: this.filters.offset,
				limit: this.filters.limit,
			}
		},
		loadingKey: 'loading',
		update(data) {
			return data.show.rows;
		},
		result(data) {
			
		}
	}
}
```

I know `getTickets` will query automatically when vue components mounted.
But if I want to query manually, how to do?
Example, I click a button and then I want to resend this request.

**Comment by Akryum** [comment]
You can refresh a query with `this.$apollo.queries.<name>.refresh()`.

**Comment by yasser-sobhy** [comment]
> You can refresh a query with this.$apollo.queries.<name>.refresh().

The `refresh()` method is now `refetch()` `this.$apollo.queries.<name>.refetch()`.

**Comment by Samuell1** [comment]
@yasser-sobhy yes, because this issue is 7 months old

**Comment by SyedAman** [comment]
can we get `refetch()` in the documentation please?

**Comment by onurkose** [comment]
Well, I've found this thread when looking answers for "how to call query manually" but in my case, I don't want query to be called when the component is mounted. It's a problem because when you implement modal components triggered from datatables, you want fetch single row data a specific moment.

That so, refetch alone is not the case for this type of usage. But there's skip option to create a workaround;

```javascript
apollo: {
  tags: {
    // GraphQL Query
    query: gql`query tagList ($type: String!) {
      tags(type: $type) {
        id
        label
      }
    }`,
    // Reactive variables
    variables() {
      return {
        type: this.type,
      }
    },
    // Disable the query
    skip() {
      return this.skipQuery
    },
  },
},
data: () => ({
  skipQuery: true,
  type: 'a fine type of something'
}),
methods: {
  triggerMyQuery () {
    this.$apollo.queries.tags.skip = false
    this.$apollo.queries.tags.refetch()
  }
}

Just call `triggerMyQuery` whenever you need and you'll have your data on demand.

**Comment by Akryum** [comment]
@onurkose Did you try:

```js
`triggerMyQuery () {
  this.skipQuery = false
}
```

**Comment by onurkose** [comment]
Oops. That was the intention of making it dynamic right? :) 
It's a better shorthand indeed.

**Comment by HelenDias** [comment]
Hi! I usually do that, but recently I found a problem with cache or something like that.
In my API, I have a resolver in Coupon type (this one have active property), and active is generated through use cases related to the coupon type.
When I call this query manually at first time, I have my correct 'active'. But if I update anything that changes my 'active' to another value, this still has the previous value. If I execute this query with the same variables in my API, active has the updated value, but in apollo query not.
In common queries I have fetchPolicy as a option to this problem. In smart query I don't have this, that's correct?
Have some way to resolve this?

**Comment by urbgimtam** [comment]
I need to make a quick call when changing languages in i18n, right at the time of switching, to understand if the content is available in the new language.

I'm intercepting with the i18n callback app.i18n.beforeLanguageSwitch(), defined in a plugin.

But is it possible to make the apollo query call manually directly from the plugin?

**Comment by dsignr** [comment]
I am not sure if this is documented somewhere, but I just use `$apollo.query()` to manually call my queries. This is the way I do it. I create methods in your vue object for your queries like this:
(Please not the example below is in Coffeescript, but should be straightforward to convert to JS)

```coffeescript
getAccountProperties: (accountId) ->  
      @$apollo.query({
        query: listPropertiesQuery,
        variables:
          accountId: accountId
      }).then((response) =>
       # Do something with properties
       # properties = response.data.properties
      ).catch((response) =>
       # Something went wrong
        console.log response
      )
```
So, later, I can just call `this.getAccountProperties(12)`, for example. Or in pure coffeescript lingo, that would be `@getAccountProperties(12)`.

As an aside, I'm very happy with coffeescript, the learning curve is super low (since it's just basically JS without the BS, it saved 50% of my time and 50% fewer LOC to achieve the same thing with raw JS.

**Comment by jrainlau** [comment]
```
this.$apollo.query({
  query: gql``,
  variables: { ... }
})
```

**Comment by ikey2244** [comment]
> ```
> this.$apollo.query({
>   query: gql``,
>   variables: { ... }
> })
> ```
this could totally be in the docs.

**Comment by sharoneh** [comment]
I'm using `this.$apollo.queries.<name>.refetch()` and it does what I was looking for, so thank you very much!

but I'm calling this for every query in every page component because I wanted all the data to refresh when any route changes.
is there a better way to do this? configure it as default or something like that?

**Comment by EugenMaevskiy** [comment]
> > ```
> > this.$apollo.query({
> >   query: gql``,
> >   variables: { ... }
> > })
> > ```
> 
> this could totally be in the docs.

Maybe you can suggest how to provide "skip" inside this call?

**Comment by andreataglia** [comment]
> ```
> this.$apollo.query({
>   query: gql``,
>   variables: { ... }
> })
> ```

took me a while to figure out that variables need to go as an object and not as a method. Just in case somebody makes my same mistake.

So do this:
```
variables: { varName: ... }
```

instead of: 
```
variables() { 
return {
varName: ...
}
}
```

**Comment by DarkLite1** [comment]
> I'm using `this.$apollo.queries.<name>.refetch()` and it does what I was looking for, so thank you very much!
> 
> but I'm calling this for every query in every page component `mounted()` method because I wanted all the data to refresh when any route changes.
> is there a better way to do this? configure it as default or something like that?

I'm also asking myself the very same question. Ideally it would be great if the query was executed every time a component is mounted (or a route is changed). So I think your way of using the `refetch()` method is the way to go. 

If anyone else has a better approach I'm all ears.

**Comment by DarkLite1** [comment]
On [StackOverflow](https://stackoverflow.com/questions/51530499/how-to-force-apollo-query-component-to-re-run-query-when-parent-component-re-ren) I found a great tip. If all you need is getting data from the graphql server to generate a list when mounted this could help:

1. Set the useQuery option `fetchPolicy="no-cache". This will force the query to be executed every time the component is mounted.

```typescript
export default defineComponent({
  setup(_, context) {
    const { result, loading, error, refetch } = useRosterDispatchGroupQuery(
      () => {
        return { fromDate: new Date('2020-10-28') }
      },
      {
        pollInterval: 15 * 60 * 1000, // every 15 min
        fetchPolicy: 'no-cache',
      }
    )
```

2. Use the `refetch()` method while keeping the cache in place:

```typescript
export default defineComponent({
  setup(_, context) {
    const { result, loading, error, refetch } = useRosterDispatchGroupQuery(
      () => {
        return { fromDate: new Date('2020-10-28') }
      },
      {
        pollInterval: 15 * 60 * 1000, // every 15 min
      }
    )

    if (!loading.value) void refetch()
```

I hope this might help others with a similar question.

**Comment by sharoneh** [comment]
@DarkLite1 I was using the Apollo module for Nuxt and calling the refetch method also because of the caching, enabled by default. After some days searching for an answer I could work around the problem as I wrote [here](https://github.com/nuxt-community/apollo-module/issues/348). Hope this helps anyone as well.

**Comment by apo1967** [comment]
> How to call `refetch()` when using [Query Component](https://github.com/Akryum/vue-apollo#query-components)?

Has anybody a hint on that? If you are using the _ApolloQuery_ component and you want to, lets say, just refetch it on an add/delete/update subscription event, how can you get the smart query of the component in the subscription handler? _this.$apollo.queries.<queryname>_ does not list the component query in that case.

**Comment by pc386** [comment]
When I use refetch the loading doesn't get updated

**Comment by eertmanhidde** [comment]
> > How to call `refetch()` when using [Query Component](https://github.com/Akryum/vue-apollo#query-components)?
> 
> Has anybody a hint on that? If you are using the _ApolloQuery_ component and you want to, lets say, just refetch it on an add/delete/update subscription event, how can you get the smart query of the component in the subscription handler? _this.$apollo.queries._ does not list the component query in that case.

I could access the query but it was definitely not a pretty way, given the fact that your `ApolloQuery` component has the ref of `wrapper` you can acces it with:
```js
const query = wrapper.$_apollo.queries.query;
```
Now you can refetch with `query.refetch()`.

**Comment by mrtwinkler** [comment]
`this.$apollo.queries.<name>.refetch().then(result => ...)`

`result` will contain the cached data, not the refetched one. How and when can I get the new data after refetching?

**Comment by LiamKarlMitchell** [comment]
Refetch only works if query.value has data.
How to actually load the query even if its first time and wait for response to be fully loaded from network?
