### ISSUE TITLE
how to use vue-apollo in vue-typescript program

### ISSUE THREAD

**Issue by anymost** [Akryum/vue-apollo#369]
Hi! our program are using Vue with typescript, while using vue-property-decorator, I want to know how to use vue-apollo in our program

**Comment by paulpdaniels** [comment]
Have you checked the docs? https://akryum.github.io/vue-apollo/

**Comment by anymost** [comment]
thanks a lot @philmueller . when I use vue-apollo with vue-property-decorator, I found the support of vue-apollo is not good enough
