### ISSUE TITLE
Is refetchQueries supported?

### ISSUE THREAD

**Issue by ecerroni** [Akryum/vue-apollo#37]
There is no mention about it in the Readme section about mutations.

**Comment by Samuell1** [comment]
And query refetch is supported? http://dev.apollodata.com/core/apollo-client-api.html#ObservableQuery.refetch

**Comment by Akryum** [comment]
Not directly, but you can access the ObservableQuery with `this.$apollo.queries.<name>.observer`

**Comment by Akryum** [comment]
It is now officially supported.
