### ISSUE TITLE
Cannot read property attrs on undefined in SSR with vue-apollo.beta-20

### ISSUE THREAD

**Issue by JohannesLamberts** [Akryum/vue-apollo#380]
`prefetchAll` crashes with `cannot read property attrs on undefined` when vm.$createElement is called with `data = undefined` (passed to `child -> queue -> walkTree -> createFakeInstance`).

A possible fix might be `vm.$createElement = (el, data = {}, children = [])`

Another error I got is `Error while rendering {Component} - Cannot read property {foo} on undefined`,
where it seems as if vue/vue-apollo would try to render a component without calculating the computed value first.
`{foo}` is a property on a computed object. When I `console.log` inside the computed, I don't see any output before vue-apollo logs its error. Any ideas?

I'll hope the short information above are helpful. I'll try to get back later with more data if necessary.

**Comment by Akryum** [comment]
This should be closed by https://github.com/Akryum/vue-apollo/commit/f83eb6a56c95991616a3e5b1696e1db7c44d4f8d
