### ISSUE TITLE
"export 'willPrefetch' was not found in 'vue-apollo'

### ISSUE THREAD

**Issue by shubh453** [Akryum/vue-apollo#386]
Hi, I exported willPrefetch from 'vue-apollo' and my app compiled with warning "export 'willPrefetch' was not found in 'vue-apollo' . Seems like I wasn't able to import it properly. Please me help to resolve this as I am newbie to this. 

      import { willPrefetch } from "vue-apollo";

**Comment by Akryum** [comment]
As of beta 20 there is no `willPrefetch` anymore ([docs](https://akryum.github.io/vue-apollo/guide/ssr.html)).
