### ISSUE TITLE
Your "installation" is front-end only: doesn't instruct to follow server side installation

### ISSUE THREAD

**Issue by janat08** [Akryum/vue-apollo#39]
I'm following this guide: https://blog.meteor.com/create-a-simple-hello-world-app-with-meteor-and-apollo-64bab66a456f#.lre40nei5

Need to install graphql tools now.
import { makeExecutableSchema } from 'graphql-tools';

**Comment by janat08** [comment]
http://dev.apollodata.com/core/vue.html
Just if you don't know, but they link me to you. Maybe you could even ask for your very own category as you're currently under vanilla js which is somewhat misleading.

**Comment by Samuell1** [comment]
@janat08 vue-apollo working only with 0.5.X version of apollo-client because newest version have changes in api... etc

**Comment by janat08** [comment]
Well yea. Graphql also gets unmet and not even as dependency for vue-apollo (although I may have had apollo-client installed). graphql-server-express appears to be required now unlike what an article from late september would say which is about when 0.5 was released.

**Comment by janat08** [comment]
@Samuell1 any chance you actually have a working repo with meteor?

**Comment by Samuell1** [comment]
@janat08 No, i doesnt use meteor. Vue app with vue-apollo and apollo-client and graphql server thats all

**Comment by janat08** [comment]
oh well, it would be cool to peek at that. See what kind of versions I should be running.

**Comment by janat08** [comment]
https://dev.mysql.com/doc/refman/5.7/en/old-client.html

Do I need sql version 4, as I in fact have version 5 which is latest.

**Comment by janat08** [comment]
Simply copying/pasting package.json from server/client examples doesn't work.

**Comment by stubailo** [comment]
I don't understand why this package would need to have server-side installation directions. This is a GraphQL client - how you build a server is up to you and a totally separate concern.

**Comment by janat08** [comment]
I haven't got a clue. The graphql dependency is difficult to meet.

**Comment by janat08** [comment]
Not in love with read react guide and see if you have to refer to vanilla documentation.

**Comment by janat08** [comment]
@stubailo how do i complain about sequelize getting rejected?

**Comment by stubailo** [comment]
I feel like you're looking for something that doesn't exist right now. Our documentation is primarily for people who already have a GraphQL server, and want to build a frontend on top of that. So there is nowhere to go to talk about Sequelize, because Apollo is not really related to that. You could ask some questions on the Slack channel though, maybe people there will have some advice.
