### ISSUE TITLE
AWS AppSync Subscriptions

### ISSUE THREAD

**Issue by CiscoKidxx** [Akryum/vue-apollo#393]
I cannot find any documentation on how subscriptions are supposed to be configured when using AWS AppSync. If this isn't the right place to ask this, I apologize however I cannot find a single piece of documentation speaking to how this is achieved.

Can anyone point me in the right direction?

Thanks in advance....

**Comment by dimitraz** [comment]
Hi, any luck? I'm trying to do the same thing

**Comment by dimitraz** [comment]
Managed to get it working. No additional configuration is needed

**Comment by ebisbe** [comment]
Hello @dimitraz , I'm trying to achieve the same. When you say that 'No additional configuration is needed' What do you mean exaclty? In the subscription section of this docs says that we need to add the websocket link. If you can explain a little more would be really helpful.

**Comment by dimitraz** [comment]
Hey @ebisbe, so the websocket configuration described in the docs is not necessary for AppSync. You just need to configure your client with the AppSync GraphQL endpoint as normal, nothing extra is needed for subscriptions to work.

**Comment by ebisbe** [comment]
@dimitraz Thanks for clarifying that. I think I'm on the right path. For what I see I have to add the `ApolloSubscribeToMore` inside of the template of the `ApolloQuery`. Now at least I got some errors and the console.logs I added to check if I was entering the `updateQuery`.
At least that is not clear in the docs.

**Comment by trung-vu-ttlab** [comment]
@dimitraz 
Many thanks for your point-out. By exploring the aws-appsync source code, especially `AWSAppSyncClient` thing, yes, exactly the lib helps us to parse/initiate both httpLink & wsLink conveniently. Also many thanks to AWS SDK team.
It means we only have to setup the AWSAppSyncClient with the http graphql endpoint as paramter.
