### ISSUE TITLE
Can't install vue apollo client for a vue cli application

### ISSUE THREAD

**Issue by yathindra123** [Akryum/vue-apollo#397]
When adding the vue apollo plugin as well as doing manual installation, giving some errors. But there is no issue if create a webpack vue project like -> "vue init webpack projectname"

![capture](https://user-images.githubusercontent.com/32919513/45923416-eeadaf80-bf02-11e8-9ddd-ba369fda408a.PNG)

**Comment by Akryum** [comment]
That should go to [vue-cli-plugin-apollo](https://github.com/Akryum/vue-cli-plugin-apollo) and I think that's a duplicate of https://github.com/Akryum/vue-cli-plugin-apollo/issues/58

**Comment by yathindra123** [comment]
Not only the plugin. The manual installation also breaks.
