### ISSUE TITLE
Access data from vue component's methods.

### ISSUE THREAD

**Issue by frederikhors** [Akryum/vue-apollo#398]
Surely I'm the fool,

but I can not find a way to access the `data` of a query from the component's methods.

I can access from my template without a problem, ex:

`<template>{{myQuery.email_address}}</template>`

But what if I need to access this data from my component's method?

I can with the first `console.log()`, not with second one, **why?**

```js
  methods: {
    test () {
      console.log(
        'test -> 1:',
        this.$apollo.queries.myQuery.vm.$apolloData.data
          .myQuery.email_address
      )
      console.log(
        'test -> 2:',
        this.$apollo.queries.myQuery.email_address
      )
    }
```

**Comment by Samuell1** [comment]
You can access query like this: `this.myQuery.email_address`
