### ISSUE TITLE
npm install, installs beta9 only not beta11

### ISSUE THREAD

**Issue by mygnu** [Akryum/vue-apollo#4]
Beta 9 has error with the plugin registry with an error saying

`prepare not defined`

**Comment by mygnu** [comment]
actually the problem happens when you do
`
npm install vue-apollo -S
`
and then reinstall it again

**Comment by laurentpayot** [comment]
Also happens with `npm update`.

**Comment by Akryum** [comment]
Is it still an issue with the rc.1?

**Comment by mygnu** [comment]
I'll try again with rc

**Comment by laurentpayot** [comment]
For me `npm update` updated to the rc.1 as it was supposed to do.

**Comment by mygnu** [comment]
seems like fixed now
