### ISSUE TITLE
authentication when ssr?

### ISSUE THREAD

**Issue by beeplin** [Akryum/vue-apollo#400]
When using SSR, if the request from the client has the `Authorization` header with the JWT, that means we already have a logged-in user. But on the server side, when doing SSR, `ApolloSSR.prefetchAll` seems not able to make use of the `Authorization` header to prefetch proper data for the authenticated user. It only returns and renders data for unauthenticated guest user, and the client side must request the proper data after that, leading to page flashing. 

Is it possible to let `ApolloSSR.prefetchAll` inherit the JWT header from the client? Or more specifically, when using `vue-cli-plugin-apollo` together with `vue-cli-plugin-ssr`, in `entry-server.js` how to initialize our server-side apolloProvider/apolloClient in order to make a server-side `authLink` to use the JWT header from the HTTP `req`?

**Comment by Akryum** [comment]
When you open a webpage, the server only gets the cookies, not some `Authorization` header you set with javascript **after** the page is loaded. So use cookies.

**Comment by beeplin** [comment]
This issue really hurts when an already-authenticated user (with the jwt in their local storage) refresh (F5) their page. On the serve side the renderer fails to use the jwt from the client to prefetch proper data, so the returned page is actually for unauthenticated guest. Then the client side thinks the proper data has been prefetched, and therefore it skips fetching the initial data -- so the user just see a page just like he/she has not logged in. Only when he/she calls for another request to the server, the jwt can be effective.

**Comment by beeplin** [comment]
Thanks~ I will be trying cookies :)

**Comment by Akryum** [comment]
Your server doesn't have access to your clients `localStorage`.

**Comment by beeplin** [comment]
Yeah, thank you for pointing my silly mistake. :P  Closing it :)
