### ISSUE TITLE
SSR fails on async components

### ISSUE THREAD

**Issue by jakub300** [Akryum/vue-apollo#402]
**Steps to reproduce:**
1. Create project using vue cli with vue router, ssr and apollo.
2. In Home.vue replace HelloWorld component in `components` with `HelloWorld: () => import('@/components/HelloWorld.vue'),`
3. Error similar to the one below will be shown in terminal after ssr attempt (manual page enter/refresh):
```
(node:2248) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'props' of undefined
    at normalizeProps (E:\Projects\Learning\vue-test-1\node_modules\vue\dist\vue.runtime.common.js:1354:23)
    at Object.mergeOptions (E:\Projects\Learning\vue-test-1\node_modules\vue\dist\vue.runtime.common.js:1456:3)
    at exports.getMergedDefinition (E:\Projects\Learning\vue-test-1\node_modules\vue-apollo\lib\utils.js:14:27)
    at Promise.then.component (E:\Projects\Learning\vue-test-1\node_modules\vue-apollo\ssr\utils.js:188:19)
```

**The origin of the stack trace:**
* `/ssr/index.js`: `vm.$createElement` is called with component name and passes it to `resolveComponent `
* `/ssr/utils.js`: `resolveComponent ` calls `resolveAsset` that returns function (it is our function that returns import)
* that function is later passed to `getMergedDefinition` that passes it to Vue's `mergeOptions`
* `mereOptions` [reads](https://github.com/vuejs/vue/blob/636c9b4ef17f2062720b677cbbe613f146f4d4db/src/core/util/options.js#L374-L376) `.options` from it, at this point child is undefined because options exists only on real components
* `mergeOptions` is calling `normalizeProps` that attempts to read `.props`

**Comment by dohomi** [comment]
Any idea how to solve this issue? I'd like to publish a working solution for the apollo module on Nuxt

**Comment by Akryum** [comment]
It will be solved with https://github.com/vuejs/vue/pull/9017

**Comment by Akryum** [comment]
See #469
