### ISSUE TITLE
Docs for v3

### ISSUE THREAD

**Issue by NikitaLiashenko** [Akryum/vue-apollo#404]
Hi,
Please provide at least some basic docs about v3. I have a problem installing version 2 of this module cause looks like there is no such in npm anymore.
It's really difficult to develop something without any documentation.

**Comment by Akryum** [comment]
You mean [this one](https://akryum.github.io/vue-apollo/)?

**Comment by NikitaLiashenko** [comment]
@Akryum Yes, I suppose that docs are related to vue-apollo 2, right?

**Comment by Akryum** [comment]
Why?

**Comment by NikitaLiashenko** [comment]
Cause the code for basic example doesn't work.
I've created separate issue for this.

**Comment by NikitaLiashenko** [comment]
I think we could close this and move to another issue I opened today about non working example.
