### ISSUE TITLE
this.$apollo is not defined.

### ISSUE THREAD

**Issue by NikitaLiashenko** [Akryum/vue-apollo#405]
Hi,
I've tried to make some small code with documentation I found on your webpage and received a problem - this.$apollo is not defined.

Here is the code:
```
import Vue from 'vue'
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { onError } from 'apollo-link-error';
import { ApolloLink } from 'apollo-link';
import { HttpLink } from 'apollo-link-http';
import config from './config/config.js';
import { enableExperimentalFragmentVariables } from 'graphql-tag';
import VueApollo from 'vue-apollo';
import ElementUI from 'element-ui';

import App from './App.vue'
import router from './router'
import store from './store'

import 'element-ui/lib/theme-chalk/index.css'
import './assets/css/style.scss'

Vue.use(ElementUI);

Vue.config.productionTip = false;

const uri = `${config.VUE_APP_URI}/graphql`;
const httpLink = new HttpLink({uri});

const cache = new InMemoryCache({});

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors){
    graphQLErrors.map(({message, locations, path}) => {
      console.log(`[GraphQl error] : Message : ${message}, Location : ${locations}, Path : ${path}`)
    })
  }
  if (networkError){
    console.log(`[Network error]: ${networkError}`)
  }
});

const client = new ApolloClient({
  link : ApolloLink.from([
    errorLink,
    httpLink
  ]),
  cache,
  connectToDevTools : true
});

const apolloProvider = new VueApollo({
  defaultClient : client,
  defaultOptions : {
    $loadingKey : 'loading'
  }
});

Vue.use(apolloProvider);

new Vue({
  router,
  store,
  provide : apolloProvider.provide(),
  render: h => h(App)
}).$mount('#app');
```
The part of code where error occurred:
```
methods : {
    capture(){
      const {email} = this.form;
      if (!email || !validateEmail(email)){
        this.error = 'Please enter a valid email';
        return;
      }
      this.$apollo.mutate({
        mutation : CaptureEmail,
        variables : {email}
      })
        .then(({data}) => {
          this.submitted = true;
          this.error = false;
          console.log(data.captureEmail.id);
        })
        .catch(error => {
          if (error.graphQLErrors.length >= 1){
            this.error = error.graphQLErrors[0].message
          } else {
            this.error = 'Something went wrong';
          }
          console.log(error);
        })
    }
  }
```

I used:
node V10.10
Vue v2.5.17
Vue-apollo v3.0.0-beta.25 (also tested this with v3.0.0-beta.19)

![screenshot from 2018-10-02 12-12-08](https://user-images.githubusercontent.com/5084346/46342995-a5650a80-c63c-11e8-8f28-e3e3e3b8615e.png)
![screenshot from 2018-10-02 12-12-20](https://user-images.githubusercontent.com/5084346/46342996-a5650a80-c63c-11e8-9b64-1afa4fdf7bae.png)

**Comment by Akryum** [comment]
See [this release](https://github.com/Akryum/vue-apollo/releases/tag/v3.0.0-beta.20). Where did you find your code example on the docs? It needs to be changed.

**Comment by NikitaLiashenko** [comment]
I've just changed the code to 
```
new Vue({
  router,
  store,
  apolloProvider,
  render: h => h(App)
}).$mount('#app');
```
and this haven't fixed the issue.

However, using tutorial from this link(https://www.howtographql.com/vue-apollo) I have the code with `.provide()` and it works ok. The tutorial is official tutorial for Vue and GraphQL.

**Comment by NikitaLiashenko** [comment]
@Akryum For example project from How To GraphQL works with and without `.provide()`.
I suppose the first project I provided could have some misconfiguration, but at the same time another project works both ways, so it might be still supported.

**Comment by Akryum** [comment]
Yes, you should have a deprecation warning in the console. BTW howtographql is not the official documentation for vue-apollo. :smile_cat:

**Comment by NikitaLiashenko** [comment]
Well, I have no deprecation message.

**Comment by Akryum** [comment]
It's [here](https://github.com/Akryum/vue-apollo/blob/master/src/apollo-provider.js#L16). Are you 100% sure you are on 3.0.0-beta.25?

**Comment by NikitaLiashenko** [comment]
Yeah, here are screenshots.

![screenshot from 2018-10-02 17-02-50](https://user-images.githubusercontent.com/5084346/46357456-3223be80-c665-11e8-82a7-03a2690d7df5.png)
![screenshot from 2018-10-02 17-03-29](https://user-images.githubusercontent.com/5084346/46357469-38b23600-c665-11e8-969a-ec34ac72766c.png)

I suppose vue cli could suppress the message, but not sure.

**Comment by Akryum** [comment]
I meant in the browser console. But it doesn't seem the options are the cause of the issue.

**Comment by Akryum** [comment]
Okay I have re-red your code and I think the faulty line is this one:

```js
Vue.use(apolloProvider);
```

It should be the plugin, not the provider:

```js
Vue.use(VueApollo);
```

**Comment by Akryum** [comment]
Did it solve your issue?

**Comment by lggwettmann** [comment]
Same problem here with this config:

```
import Vue from 'vue'
import ApolloClient from 'apollo-boost'
import VueApollo from 'vue-apollo'

Vue.use(VueApollo)
const apolloProvider = new VueApollo({
  defaultClient: new ApolloClient()
})

new Vue({
  el: '#app',
  apolloProvider,
  components: {
    ...
  }
})
```

happening here: 
```
 mounted () {
    console.log('vue apollo loading?:' + this.$apollo.queries.myTestQuery.loading)
}
```

**Comment by Akryum** [comment]
All the tests are passing, and I can't reproduce this.
https://github.com/Akryum/vue-apollo/blob/dev/tests/demo/src/main.js#L14
