### ISSUE TITLE
Confused about warning <ApolloProvider>.provide() is deprecated. 

### ISSUE THREAD

**Issue by smolinari** [Akryum/vue-apollo#408]
Hi,

I am getting this warning trying to add the `.provide()` function to the provide property in vue. 

`<ApolloProvider>.provide() is deprecated. Use the 'apolloProvider' option instead with the provider object directly.`

I was looking through all the examples that add to the provide property, even the new Vue UI 😉 and they are also using the .provide() method. (Vue UI doesn't have this warning either.)

How can this warning be avoided?

Granted, I'm using Quasar, but it shouldn't matter. This is the code pluging in vue-apollo.
```
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import VueApollo from 'vue-apollo'
import fetch from 'node-fetch'
import { createHttpLink } from 'apollo-link-http'

const httpLink = createHttpLink({ uri: 'http://localhost:4000/graphql', fetch: fetch })

// Create the apollo client
const apolloClient = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache(),
  connectToDevTools: true
})

export const apolloProvider = new VueApollo({
  defaultClient: apolloClient,
  errorHandler ({ graphQLErrors, networkError }) {
    if (graphQLErrors) {
      graphQLErrors.map(({ message, locations, path }) =>
        console.log(
          `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
        )
      )
    }
    if (networkError) {
      console.log(`[Network error]: ${networkError}`)
    }
  }
})

export default ({ app, Vue }) => {
  Vue.use(VueApollo)
  app.provide = apolloProvider.provide()
}
```
Any suggestions would be greatly appreciated.

Scott

**Comment by Akryum** [comment]
```js
app.provide = apolloProvider.provide()
```

should be:

```js
app.apolloProvider = apolloProvider
```

See the [docs](https://akryum.github.io/vue-apollo/guide/installation.html#apollo-provider).

**Comment by smolinari** [comment]
Thanks Guillaume. I couldn't see the forest for the trees.

I was looking at the docs and for me, it wasn't and still isn't clear at all that I should be using. 

`app.apolloProvider = apolloProvider` 

In fact, the description shows the `.provide()` method. 

Or, maybe I am missing some sort of fundamental understanding of this package or Vue? 

Thanks again for your time. And I love the fact you pulled this package together for Vue!!! I think GraphQL is awesome. 😄 

Scott

**Comment by smolinari** [comment]
In fact, could it be the docs are wrong?

Shouldn't it be?
```
new Vue({
  el: '#app',
  apolloProvider,
  render: h => h(App),
})
```
??? @Akryum 

Scott

**Comment by Akryum** [comment]
Where is it wrong in the doc? (Which page?)

**Comment by smolinari** [comment]
The page you linked to above? I'm asking questions too, as I am definitely not certain. 

https://akryum.github.io/vue-apollo/guide/installation.html#apollo-provider

Scott

**Comment by Akryum** [comment]
![capture d ecran du 2018-10-04 18 28 11](https://user-images.githubusercontent.com/2798204/46488616-777df280-c803-11e8-8e14-8fa60b3c2c91.png)

**Comment by Akryum** [comment]
(I fixed the sentence on unpushed commits already.)

**Comment by smolinari** [comment]
I think you need to change the sentence to, don't you? Something like....

> The provider holds the Apollo client instances that can then be used by all the child components. Inject it into your components with the `apolloProvider` object.

Scott

**Comment by catskull** [comment]
Just documenting my issue:
I had my Apollo config in a seperate file that my webpack entry point(s) were importing. However the import wasn't named `apolloProvider`, just `provider` so the default config in the docs didn't work:
```
new Vue({
  el: '#app',
  provider,
  render: h => h(App),
})
```
I could have changed the name of the export, but instead I just did this:
```
new Vue({
  el: '#app',
  apolloProvider: provider,
  render: h => h(App),
})
```
