### ISSUE TITLE
`ApolloProvider` typings not updated with properties `defaultClient` and `clients`.

### ISSUE THREAD

**Issue by jhanschoo** [Akryum/vue-apollo#409]
From https://github.com/Akryum/vue-apollo/issues/52 it seems that `clients` was moved into `ApolloProvider` some time ago. However, the typings of `ApolloProvider` has not been updated to reflect that.

https://github.com/Akryum/vue-apollo/blob/master/types/apollo-provider.d.ts

**Comment by jhanschoo** [comment]
The docs for DollarApollo has not been updated as well.

https://akryum.github.io/vue-apollo/api/dollar-apollo.html

**Comment by dimensi** [comment]
![image](https://user-images.githubusercontent.com/11390039/47518917-e7c4e480-d894-11e8-9849-85b4648610c2.png)
this is normal?

**Comment by jhanschoo** [comment]
@dimensi As you can see, `client` is undefined. The docs for `DollarApollo` say

* `client`: current Apollo client for the component.

Per #52, the reference to the Apollo client has been moved from `this.$apollo.client` to `this.$apollo.provider.defaultClient`, etc.
