### ISSUE TITLE
Query fetchPolicy ignored in favour of cache

### ISSUE THREAD

**Issue by kendallroth** [Akryum/vue-apollo#411]
Recently ran into an issue with Apollo on Vue and I'm not sure where the problem lies (`vue-apollo` or `apollo-client`). The issue appears to be that Apollo is ignoring the `fetchPolicy` and is using cached values even when a `network-only` query should be refetched.

### Example

In this example (common throughout app), there is a "Details" page that has several lists of sub-items (or items with this entity as the parent). As the filter changes on the "Details" page, different components are mounted and unmounted (using the `v-if` directives). As each component mounts, it **should** be refetching its data from the network (using `fetchPolicy: "network-only"`). However, after the initial mount it **does not** refetch over the network again, but appears to use the cached values.

It should be noted that in this example, the query and variables **are not changing**. However, since I am using `network-only` I would expect it to send another network request anyway. Additionally, there is another location in the app that 

_The same is true when using `fetchPolicy: "no-cache" and `fetchPolicy: "cache-and-network"`_

```js
// ProjectDetails.vue
//    Details for a given project (and sub-item lists such as events or positions)

<template>
  ...
  <ProjectEvents v-if="filter==='events'" />
  <ProjectPositions v-else-if="filter==='positions'" />
  ...
</template>

export default {
  ...
  data: {
    return { filter: "events" };
  }
  ...
};
```

```js
// ProjectEvents.vue
//    List of events within a given project

export default {
  ...
  apollo: {
    events() {
      return {
        query: ProjectEventsQuery,
        variables: {
          projectId: this.$route.params.projectId
        }
        fetchPolicy: "network-first"
      };
    }
  }
};
```

```js
// ProjectPositions.vue
//    List of positions within a given project

export default {
  ...
  apollo: {
    positions() {
      return {
        query: ProjectPositionsQuery,
        variables: {
          projectId: this.$route.params.projectId
        }
        fetchPolicy: "network-first"
      };
    }
  }
};
```

### Temporary Fix

As a temporary fix I have been able to add a `refetch` call whenever the component mounts. While this does "solve" the issue it feels quite hacky and unnecessary (extra work to redo what should be done by `vue-apollo` or `apollo-client`).

```js
// ProjectPositions.vue
//    List of positions within a given project

export default {
  ...
  mounted() {
    this.$apollo.queries.positions.refetch({
      // Empty object should use default variables?
    });
  },
  apollo: {
    // Same as before
  }
  ...
};
```

_It should be noted that I do not know how to create a reproducible issue for this, but I have found it in other places while searching (but not answered or archived)._

**Comment by xshadowlegendx** [comment]
I also had the problem similar to yours. I have to generate ``presignUrl`` from the server and pass to client, and it will always return the cache value. My workaround was to change my ``presignUrl`` schema to add a ``tempId`` field on it, so that I could randomly generate short unique id as variable to it, so that It will not return me the cached value.

**Comment by Akryum** [comment]
This looks like an issue with apollo-client but I can't reproduce with `cache-and-network`:

```
Loaded 5 message(s) ChannelView.vue:120
Loaded 8 message(s) ChannelView.vue:120
```

**Comment by dehypnosis** [comment]
it maybe caused by `ssrMode` or `ssrForceFetchDelay`.
in my case, setting `ssrMode=false`, `ssrForceFetchDelay=0` for browser firgured out this problem.

```js
  const apolloClient = new ApolloClient({
    defaultOptions: {
      watchQuery: {
        fetchPolicy: 'cache-and-network',
      },
      query: {
        fetchPolicy: 'network-only',
      },
    },
    link: mergedHandler,
    cache,
    queryDeduplication: true,
    ...(
      IS_SSR ? { // to fetch only once on SSR
        ssrMode: true,
        ssrForceFetchDelay: 100,
      } : {
        ssrMode: false,
        ssrForceFetchDelay: 0,
        connectToDevTools: process.env.NODE_ENV !== 'production', // enable apollo dev tools
      }
    ),
  })
```
