### ISSUE TITLE
[Feature Request] need event `before` in ApolloMutation component

### ISSUE THREAD

**Issue by winter-ice** [Akryum/vue-apollo#412]
I'd like to use ApolloMutation component,but I want to validate form before submit.So could you please add a event `before` in ApolloMutation component.I think that will resolve my problem.

**Comment by joe-re** [comment]
@winter-ice 
Can you explain us more description?
I guess you can wrap your mutation with wrap or you can set `:disabled` property or others.
In my case, I'm using like below.

```
// isValid is computed property inside your Vue Component.

<ApolloMutation
  :mutation="require('@/graphql/userLogin.gql')"
  :variables="{
    email,
    password,
  }"
  @done="onDone"
>
  <template slot-scope="{ mutate, loading, error }">
    <button :disabled="loading || !isValid" @click="mutate()">Click me</button>
    <p v-if="error">An error occured: {{ error }}</p>
  </template>
</ApolloMutation>
```

**Comment by winter-ice** [comment]
resloved.
