### ISSUE TITLE
loadingKey and watchLoading don't work on a manually added smart query in mounted()

### ISSUE THREAD

**Issue by GlennMatthys** [Akryum/vue-apollo#415]
When manually adding a smart query, the "loadingKey" and "watchLoading" functions do not work. For example:

```
mounted()
{
    this.$apollo.addSmartQuery('telemetry',
        {
            query: gql`{some{query{here}}` ,
            variables()
            {
                return { myVar: this.myVar }
            },
            loadingKey: 'working',
            watchLoading(isLoading, countModifier)
            {
                console.log(isLoading);
            },
            manual: true,
            result({data})
            {
                doSomeWork(data);
            }
        }
    );
}
```

watchLoading() is never called.

**Comment by Akryum** [comment]
Added a passing test:

https://github.com/Akryum/vue-apollo/blob/dev/tests/demo/src/components/ManualAddSmartQuery.vue

https://github.com/Akryum/vue-apollo/blob/198b38330ae2c6aa6170cc510a9f3078a7b7caac/tests/demo/tests/e2e/specs/manual-smart-query.js#L2-L7

![image](https://user-images.githubusercontent.com/2798204/67199061-99dbb180-f400-11e9-8393-a5ee081c65d7.png)
