### ISSUE TITLE
Passing 0 to pollInterval should mean "don't poll"

### ISSUE THREAD

**Issue by paulEisen** [Akryum/vue-apollo#416]
The vue-apollo [query docs](https://github.com/Akryum/vue-apollo/blob/master/docs/api/apollo-query.md)' descriptions of `pollInterval` simply links to the Apollo query docs, which [say](https://www.apollographql.com/docs/react/essentials/queries.html#refetching) that a value of `0` means that no polling takes place. But when `0`, or any invalid value such as `-1` or `undefined`, is passed to the `pollInterval` prop, vue-apollo polls the query as fast as possible. The `startPolling()` function behaves slightly better, as it errors out on falsey values.

**Comment by Akryum** [comment]
I'm not doing something special regarding polling, just passing the option along to apollo-client.
