### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by luckyboy07** [Akryum/vue-apollo#417]
Can somebody explain or help me why im getting with this error..  im using chainwebpack for my vue config file.

` 
chainWebpack: config => {
    config.module
      .rule('compile')
      .test(/\.mjs$/)
      .pre()
      .include
      .add(
        [
          /node_modules/,
          /src\/vendor/,
          /test/,
          /node_modules\/webpack-dev-server\/client/,
          /node_modules\/vue-echarts/,
          /node_modules\/resize-detector/,
          /node_modules\/vue-masonr/
        ])
      .end()
      .use('babel-loader')
      .loader('babel-loader')
      .options({
        presets: [
          '@babel/preset-env'
        ]
      })

    config.module
      .rule('js')
      .test(/\.js$/)
      .pre()
      .include
      .add(
        [
          /src\/vendor/,
          /test/,
          /node_modules\/webpack-dev-server\/client/,
          /node_modules\/vue-echarts/,
          /node_modules\/resize-detector/,
          /node_modules\/vue-masonr/
        ])
      .end()
      .use('babel-loader')
      .loader('babel-loader')
      .options({
        presets: [
          '@babel/preset-env'
        ]
      })
    config.merge({
      resolve: {
        extensions: [".webpack.js", ".web.js", ".mjs", ".js", ".json"]
      },
    })

  },`

and im getting this error : 
![image](https://user-images.githubusercontent.com/17866364/46991077-e7ab4300-d136-11e8-9de6-b30850d6c031.png)

**Comment by Akryum** [comment]
I'm not sure how this is related to vue-apollo?
