### ISSUE TITLE
[Question] Extending vue-apollo

### ISSUE THREAD

**Issue by robsontenorio** [Akryum/vue-apollo#418]
Is there any way to override globally  vue-apollo default methods like `query()` and `mutate()`?

**Scenario:**

I'm trying to convert responses from `query()` into Models by using some custom parser:

```js
data()
{
   return {
       users: []
   }
},
apollo:{
    users: {
       query: USERS_QUERY,
       result({data}){
           this.users = MyModelParser(data)
       }
    }
}
```
As we know we have the `result()`  will be called allowing us to "transform" the response once received. But, right now this should be done in every single apollo query response.

So, i intend to override globally the `query()` method in order to execute automatically my custom parser after response.

**Comment by Samuell1** [comment]
For what you want to convert response? You want remove field or change fields?

**Comment by robsontenorio** [comment]
I don't know if this is the best approach, but i can handle it by implementing "default options" from "apollo provider".

```js
apolloProvider.defaultOptions = {
    $query: {
      update: (data) => {
        // recursive map response into Models (ES6 classes) by using __typename from each object from JSON response
        return GraphParser.map(data)
      }
    }
  }
```
