### ISSUE TITLE
[BUG] Data is an empty object when having ACL errors

### ISSUE THREAD

**Issue by kavalcante** [Akryum/vue-apollo#420]
I'm having an issue in queries with ACL using Schema Directives. The return of the call contains a `data` object containing the data that the current user can see, including a error object telling the user that he can't see other part's of the data.

However, when using `vue-apollo`, both `update` and `result` hooks bring an empty object on data property, e.g:

```js
result({ data }) {
  console.log(data); // --> {}
},
```

Is there any solution or workaround for this kind of problem? I need bring this data, because in this specific view, some companies name's the user can't see, and others he can.

**Comment by Akryum** [comment]
See: https://www.apollographql.com/docs/react/features/error-handling.html#policies

**Comment by ebisbe** [comment]
@Akryum I think this should be explained/pointed out in some parts of the docs. It feels really frustrating searching 'error' and not having any hit. Before finding that issue I already found that same link but I was not sure how to proceed.
