### ISSUE TITLE
ApolloQuery scoped-slot supports `fetchMore` `refetch` etc

### ISSUE THREAD

**Issue by beeplin** [Akryum/vue-apollo#423]
Apollo React supports injecting functions like `fetchMore`, 'refetch` etc together with `data` `loading` `error`: https://www.apollographql.com/docs/react/api/react-apollo.html#query-render-prop

Currently in vue-apollo it seems that we can only call `fetchMore` from an `apollo` option in the component. It would be wonderful to inject these functions to the `ApolloQuery` scoped-slot.

**Comment by PaulKujawa** [comment]
Would love this feature. `$this.apollo.queries` is always an empty object when Apollo components are used.

**Comment by Elazul** [comment]
That would be very useful for pagination

**Comment by alukos** [comment]
I think the `quest` is enough.
I have here is so works: 

Product.vue:
```
...    
<ApolloQuery
  :query="require('@/graphql/Product.gql')"
  :variables=""{limit: $options.numOnPage}"
  #default="{ result: { loading, error, data }, query }"
>
  <masonry :products="product" />
  <infinite-loading @infinite="loadMore(query, $event)" />
</ApolloQuery>
...
<script>
...
  data: () => ({
    page: 1,
  }),
  numOnPage: NUM_ON_PAGE,
  methods: {
    loadMore(query, $state) {
      query.fetchMore({
        variables: {
          offset: this.page++ * NUM_ON_PAGE,
        },
        updateQuery: (prev, { fetchMoreResult }) => {
          if (!fetchMoreResult || fetchMoreResult.product.length === 0) {
            $state.complete();
            return prev;
          }
          $state.loaded();
          return Object.assign({}, prev, {
            product: [...prev.product, ...fetchMoreResult.product],
          });
        },
      });
    },
  },
...
```

**Comment by Elazul** [comment]
that works great thank you !
