### ISSUE TITLE
SmartQuery result isn't updated when result comes from the cache

### ISSUE THREAD

**Issue by SebastienTainon** [Akryum/vue-apollo#425]
Hello,

I have here an autocomplete query that is pretty much like the code from the doc: https://akryum.github.io/vue-apollo/guide/apollo/queries.html#reactive-parameters

```
<template>
    <div>
        <h3>Autocomplete</h3>
        <input v-model="input" placeholder="Enter a user" />
        <p>
            {{autocompleteUser}}
        </p>
    </div>
</template>

apollo: {
  autocompleteUser: {
    query: gql`query AutocompleteUser($message: String!) {
      autocompleteUser(query: $message) {
        id
      }
    }`,
    variables() {
      return {
          message: this.input,
      }
    },
  },
},
```

I then try to type things in the input: everytime it's a new query that I haven't tried before, a network query to my GraphQL endpoint is triggered and it works well. But when I type something that I had typed before, and the result comes from the Apollo Cache, my `autocompleteUser` data is not updated by Vue-apollo as it should: the data is still the same as my previous search.

With the Apollo Chrome extension I can verify that in the Apollo cache I have the right data, so I suspect that the problem comes from vue-apollo.

I use this as ApolloClient:

```
const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData: schema,
});
const apolloClient = new ApolloClient({
    link: link,
    cache: new InMemoryCache({ fragmentMatcher }),
    connectToDevTools: true,
});
```

Is there a trick that I'm not aware of to trigger the refresh everytime, even when the results come from the Apollo cache? If I add `fetchPolicy: 'no-cache'` to the query it works, but that's far from optimal...

Thanks!

**Comment by SebastienTainon** [comment]
After a bit of research and debugging, I've found this thread that explains the issue better, it's a long read but very interesting: https://github.com/apollographql/apollo-client/issues/2712#issuecomment-402769106

It is explained the actual role of `setVariables` for an `ObservableQuery` and from what I understand, the maintainer says that this method shouldn't be used the way Vue-Apollo uses it - in fact it shouldn't even be public. In short, the ObservableQuery will notify its observers only for changes to data in the store. In my case, the variables of the query change but as the result has already been fetched and stored in the store, the store itself doesn't change, hence there is no notification to the observer, hence Vue-Apollo doesn't update the value of the `data` attribute.

That can cause a lot of problems for people using Vue-Apollo this way and should definitely be fixed in my opinion, however there doesn't seem to be a clear fix for this yet, these people are thinking about updating the Apollo interface and making `setVariables` private but I don't see a good alternative yet in the thread. The best that is suggested is : 

> This can be worked around however by checking the cache first to see if a match exists, before firing the refetch

I'd be curious to have your opinion on this issue and the suggested workaround @Akryum

**Comment by miel-dev0** [comment]
I made a PR which solves this issue (#343), but I think your thread describes the issue better than mine.

ObservableQuery.refetch should work but considering the current implementation of SmartQuery, it may be simpler to just create a new ObservableQuery object on variable change.

**Comment by SebastienTainon** [comment]
Hello @miel-dev0,
Thanks I can confirm that with your PR, this observation issue is solved and the cache works as expected.
I agree with you :+1:
