### ISSUE TITLE
ApolloQuery crash due to the new cloneDeep methods from 'apollo-utilities'

### ISSUE THREAD

**Issue by Hugome** [Akryum/vue-apollo#431]
It is a funny one : 

After a simple npm update all my ApolloQuery component crashed :
![image](https://user-images.githubusercontent.com/1301995/47364249-201fc380-d6d9-11e8-8df9-b8a3351b18c4.png)
After digging into dependencies and source :
3/4 days ago 'apollo-utilities' change its 'deepClone' function from a npm package 'fclone' to a custom one.

The query result come from network -> apollo -> vue-apollo, and in this process the query result is 'deepClone' somewhere but the properties from the result have one value and get/set from vue :
![image](https://user-images.githubusercontent.com/1301995/47364722-498d1f00-d6da-11e8-853e-dce71cf718fa.png)

I hope this is clear enough

Thanks !

**Comment by Hugome** [comment]
Nevermind, just fixed : https://github.com/apollographql/apollo-client/commit/e1f8da4ae9818f664ba7961eb6795387989bccc4

**Comment by jannishuebl** [comment]
same problem here. @Hugome have you figure out versions of the packages that work together?
