### ISSUE TITLE
[BUG] An error occurs when you do multiple queries and in subsequent queries use the value from the first query.

### ISSUE THREAD

**Issue by Erbolking** [Akryum/vue-apollo#432]
I've noticed that this issue arise with "**apollo-utilities@1.0.16**"

Step to reproduce:

1. Do a query with a variable
2. Change the variable value to something
3. Return the variable value to the initial value

You will see an error like:
`"TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>"`

https://codesandbox.io/s/436n4pnow7

**Comment by NicoAiko** [comment]
Can confirm!
This also happens when trying to `refetch` stuff.

**Comment by Akryum** [comment]
See: https://github.com/apollographql/apollo-client/issues/4034

**Comment by cschroeter** [comment]
If you use the vue apollo cli plugin - you just need to set the resolutions property for apollo-utilities. Thats it ;)

```json
  "dependencies": {
    "apollo-client": "2.4.3",
    "graphql": "14.0.2",
    "vue": "2.5.17",
    "vue-apollo": "3.0.0-beta.25"
  },
  "resolutions": {
    "apollo-utilities": "1.0.21"
  },
```

**Comment by mariomka** [comment]
It was fixed in the last version. Just update apollo-client to 2.4.4.

**Comment by dimensi** [comment]
bug again appear in 2.4.5

**Comment by Akryum** [comment]
@benjamn

**Comment by dimensi** [comment]
If i install apollo-utilities directly bug disappear @benjamn.
@Akryum maybe better add apollo dependencies directly in package.json if we install "vue-apollo" via vue-cli ?
