### ISSUE TITLE
Add Option `polling` to Smart Query

### ISSUE THREAD

**Issue by jantajov** [Akryum/vue-apollo#452]
According to [documentation](https://akryum.github.io/vue-apollo/api/smart-query.html#options) polling can be started only by calling `startPolling(<int>)` method.

@Akryum Please add option `polling` to Smart Query!

It would take int (in ms) as its value.

**Comment by paulpdaniels** [comment]
Docs may not reflect it properly, but there should be a `pollInterval` key available for smart queries which is simply passed to apollo-client.

**Comment by jantajov** [comment]
@paulpdaniels Works for me!
