### ISSUE TITLE
Subscriptions instructions need to be updated?

### ISSUE THREAD

**Issue by jamiewilson** [Akryum/vue-apollo#46]
Hey there. Following the instructions for subscriptions here (https://github.com/Akryum/vue-apollo#subscriptions), I'm getting an error:

```
Uncaught TypeError: _subscriptionsTransportWs.Client is not a constructor
apollo.js?af01:29
```

Looking at the API for [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws#subscriptionclient), it looks like maybe the `Client` constructor you're referencing here `import { Client } from 'subscriptions-transport-ws'` has been renamed to `subscriptionClient`?

**Comment by tahaykACF** [comment]
yes I think you are right, and it is `SubscriptionClient` not `subscriptionClient`:
`import {SubscriptionClient} from 'subscriptions-transport-ws';`

**Comment by Akryum** [comment]
The documentation has been updated already. :wink:
