### ISSUE TITLE
fetchPolicy not used?

### ISSUE THREAD

**Issue by dsbert** [Akryum/vue-apollo#47]
I am trying to force a cache invalidation and the fetchPolicy appears not to be working.

```javascript
      await this.$apollo.query({
        fetchPolicy: 'network-only',
        query: this.query,
        variables: {
          id: this.id,
        },
      });
```

**Comment by stubailo** [comment]
Looks like this has a whitelist of options it supports. I think after 1.0 is released with a stable API it will be a good idea to update this package: https://github.com/Akryum/vue-apollo/blob/11d2a1ea0f30375ebb695646e6171390b1d991cb/src/smart-apollo.js#L133

**Comment by Samuell1** [comment]
This package is now only for 0.5.x ... see https://github.com/Akryum/vue-apollo/issues/42

**Comment by Akryum** [comment]
I will update vue-apollo soon to catch up with apollo-client rc.1 :smile:

**Comment by Akryum** [comment]
@stubailo Actually, this is the blacklist for `vue-apollo` options, to get the apollo-client ones
