### ISSUE TITLE
Setting tag="" on ApolloMutation to output table rows doesn't render rows

### ISSUE THREAD

**Issue by mwidmann** [Akryum/vue-apollo#479]
My component renders a <tr> inside a table inside a higher level component. The whole component is wrapped inside an ApolloMutation component. As the default output tag of such a component is div, leaving it as default, the table display is broken. If I change the `tag` attribute to an empty string like I did successfully in other components, no content is displayed at all.

```
<template>
  <ApolloMutation
    :mutation="UPDATE_PERMISSIONS_MUTATION"
    :variables="{permissions, userId: user.id}"
    tag=""
  >
    <template slot-scope="{mutate, loading, error}">
        <tr v-if="error">
          <td colspan="2">
            <Error :error="error">
          </td>
        </tr>
        <tr>
          <td>{{user.name}}</td>
          <td>{{user.email}}</td>
        </tr>
    </template>
  </ApolloMutation>
</template>
```

removing the tag attribute, renders everything but breaks the layout of the table. For now I changed the `tag` to `tr` and removed the error displaying table row, but that's not how it is supposed to work.

**Comment by mwidmann** [comment]
I was able to solve it by using https://github.com/y-nk/vue-fragment and setting `tag="fragment"`.

**Comment by Akryum** [comment]
When `tag` is falsy, the component is only rendering the first child as Vue doesn't support fragments (yet).
