### ISSUE TITLE
Cache-only call result twice

### ISSUE THREAD

**Issue by karonl** [Akryum/vue-apollo#48]
`
apollo:{  
    oncehello: {query:gql`{oncehello:hello{content}}`, fetchPolicy: 'cache-only', result(data){
        console.log(data)
    }}
}
`
When i use the 'cache-only' to query, it can call result() twice ? But ohters are not wrong.   
In my opinion, the query should that read the data from the cache once, and call result once. 
version: vue-apollo@2.0.0-beta.2

**Comment by karonl** [comment]
vue-apollo@2.0.0-beta.2

**Comment by Akryum** [comment]
Do you have a repro?

**Comment by karonl** [comment]
I build the sample. In this case, i don't know why i get the result() call twice in the 'cache-only' mode.  Others is normal.     
https://github.com/karonl/graphql-server-test

**Comment by Akryum** [comment]
This is because the result is first returned with the loading state being true, then return again with loading state being false. To fix this, use the manual mode:

```javascript
{
  query: gql`...`,
  manual: true,
  result ({ data, loading }) {
    if (!loading) {
      this.items = data.items
    }
  },
}
```
