### ISSUE TITLE
typo in configuration example?

### ISSUE THREAD

**Issue by laurentpayot** [Akryum/vue-apollo#5]
In the readme it says we should import Apollo client like so:
`import ApolloClient, { createNetworkInterface, addTypename } from './apollo-client';`

But it is only working after removing the curent directory prefix:
`import ApolloClient, { createNetworkInterface, addTypename } from 'apollo-client';`

**Comment by Akryum** [comment]
Thanks for reporting this!

Le jeu. 29 sept. 2016 13:57, Laurent Payot <notifications@github.com> a
écrit :

**Comment by laurentpayot** [comment]
@Akryum You're welcome. Beware the typo is still present in the [npm page](https://www.npmjs.com/package/vue-apollo). I don't know if it needs a manual change or if it will refresh by itself from github in a moment.
