### ISSUE TITLE
guidelines for vue-apollo and nuxt

### ISSUE THREAD

**Issue by dohomi** [Akryum/vue-apollo#51]
Hi @Akryum 

thanks for this great package. I'm using it for a while and it worked great so far. Now with the recent changes in for 2.1.x I'm wondering about the best practice if I run it with `Nuxt` and SSR // server-client hydrations.

Do you have any recommended guidelines for it?
Thanks

**Comment by jvbianchi** [comment]
This might be related with https://github.com/nuxt/nuxt.js/issues/504

**Comment by dohomi** [comment]
@Akryum great news about the new SSR api. Did you already figure out, how to make use of it inside of the NUXT context? Thanks

**Comment by dohomi** [comment]
@Akryum do you have any news about the best way to integrate `vue-apollo` into `NUXT`? Thanks!

**Comment by t0ker** [comment]
No updates?

**Comment by frankspin89** [comment]
Yea I would love to see a update on this issue. Really looking forward to combine both of my favourite projects.

Any updates on this

**Comment by ImTheDeveloper** [comment]
Any news?

**Comment by dohomi** [comment]
I'll close this as the module is released now: https://github.com/nuxt-community/apollo-module
