### ISSUE TITLE
option to bind to an arbitrary local variable name

### ISSUE THREAD

**Issue by hmexx** [Akryum/vue-apollo#512]
I've only started using vue-apollo, so apologies if I've missed something, but why does vue-apollo assume we would want to use a local variable name that matches the graphql name?

In the following code, I would like to rename my local property from `users` to `local_users`, WITHOUT changing the graphql query.

```typescript
@Component<Hasura>({
  apollo: {
    users: {
      query() {
        return gql`query {${this.USER_GQL}}`;
      }
    },
  }
})
export default class Hasura extends Vue {
  users = []
  id = 5;

  get USER_GQL() {
    return `
      users(where: {id: {_eq: ${this.id}}}) {
         id
         first_name
         last_name
      }`;
  }
</script>
```

The only option I could come up with by perusing the documentation is:

```typescript
@Component<Hasura>({
  apollo: {
    users: {
      query() {
        return gql`query {${this.USER_GQL}}`;
      },
      manual: true,
      result({ data, loading }) {
        if (!loading) {
          this.local_users = data.users;
        }
      }
    }
  }
})
export default class Hasura extends Vue {
  local_users = []
  id = 5;

  get USER_GQL() {
    return `
      users(where: {id: {_eq: ${this.id}}}) {
         id
         first_name
         last_name
      }`;
  }
</script>
```

Is the the recommended way of binding to a local variable that doesn't match the graphql query? Seems a little weird to have to use the manual flag for such a common use-case. The other option I can think of is to let vue-apollo bind to a matching variable name, but then add a computed property in my class to rename it. Again, seems a little excessive.

I think I must have missed something obvious, but could not find any other place to get an answer, so apologies for polluting your github issues.

Thank you!

**Comment by paulpdaniels** [comment]
Normally I just use an alias in the query but if you don't want to change the query you can just tell vue-apollo what to use with the `update` function.

```
  apollo: {
    local_users: {
      query() {
        return gql`query {${this.USER_GQL}}`;
      },
      update ({users}) {
        return users;
      }
    },
  }
```

**Comment by hmexx** [comment]
I have to embarassingly admit, that I did not realise aliases existed in graphql. I'm happy with that solution.

For some reason, asliasing doesn't work with $subscribe, so in that case I will use the `result` function in a simlar fashion to the `update` you suggested above. This is fine as I won't be using subscription as much.  Below are my two snippets now for queries and subscription. I will close the issue. thank you for your help!

> Query, with aliasing

```typescript
@Component<Hasura>({
  apollo: {
    users: {
      query() {
        return gql`query
         { users: ${this.USER_GQL} }`;  // aliased to 'users'
      },
    }
  }
})

```

> Subscription, with `result`

```typescript
@Component<Hasura>({
  apollo: {
    $subscribe: {
      users: {
        query() {
         return gql`subscription
          { ${this.USER_GQL} }`;
        },
        result(r) {
          this.users = r.data.user;  // reassigned to 'users' manually
        }
      }
    }
  }
})
```


> Subscription, with aliasing (**does not work**)

```typescript
@Component<Hasura>({
  apollo: {
    $subscribe: {
      users: {
        query() {
         return gql`subscription
          { users: ${this.USER_GQL} }`;  
        }
      }
    }
  }
})
```

**Comment by Akryum** [comment]
@hmexx Subscriptions are different than queries and do not modify your component data automatically.
