### ISSUE TITLE
Publish v3.0.0?

### ISSUE THREAD

**Issue by dominik-bln** [Akryum/vue-apollo#516]
First of all thanks for your great work on this plugin!

What I'd like to ask/suggest is to move out of beta and publish `v3.0.0`. To be honest, a beta28 seems a bit high and the package has been in beta for over a year by now.

Is there anything that is holding this up, that you absolutely want in `v3.0.0`? Maybe something the community could help out with?

We are using the beta in a production system and it's working completely fine, but in an enterprise environment it's often appreciated to not rely on a beta state (even if that's just some arbitrary label).

Thanks and best regards.

**Comment by mrcasablr** [comment]
I hope #506 and #510 gets merged before 3.0.0 release.

I also hope 3.1.0-beta gets released with apollo client 2.5.0-beta with seamless management of local state

**Comment by mrcasablr** [comment]
Apollo client / apollo boost 2.5.0 / 0.3.0 with integrated local state management is released - https://blog.apollographql.com/announcing-apollo-client-2-5-c12230cabbb7

**Comment by DaveSanders** [comment]
Is there any kind of timeline for releasing with apollo 2.5?  What can be done to help that out?

I'm just getting into Apollo + Vue on a new project and we'd like to use the latest apollo and eliminate Vuex entirely. So I know very little about vue-apollo right now, and don't know what challenges there might be to get it to apollo 2.5. But if I can help, I will.

**Comment by Akryum** [comment]
Vue-apollo is already compatible with Apollo Client 2.5.

**Comment by chanlito** [comment]
Hey all, seriously when will Vue Apollo be out of beta? What's holding back? What's the current focus of the project? What's on the roadmap?

**Comment by Akryum** [comment]
Soon!
