### ISSUE TITLE
How to refresh a ApolloQuery component ?

### ISSUE THREAD

**Issue by yann-yinn** [Akryum/vue-apollo#534]
Hello, thanks for the hard work on Vue-apollo. ❤️ 

I would like my ApolloQuery to refresh / refetch data when `queryVariables` changes, but this does not work : if I mutate my queryVariables object, nothing happens and i have no way to update my query. Also, i thought this component would create a "smartQuery" automatically but my `this.$apollo.queries` are empty, so it seems i have no way to refresh this query.

```html
      <ApolloQuery
        :query="require('@/app/graphql/queries/getUsers.gql')"
        :variables="queryVariables"
      >
        <template slot-scope="{ result, isLoading }">
          <v-card-text>
            <div v-if="isLoading">loading...</div>
            <div v-if="result.error">{{result.error}}</div>
            <div v-if="result.data">
              <DataTable :data="result.data.getUsers"/>
            </div>
          </v-card-text>
        </template>
      </ApolloQuery>
```

And here is what my component logic looks like

```js
export default {
  //...
  data() {
    return {
      queryVariables: {
        page: 1,
        pageSize: 2,
        search: "test",
      },
    };
  },
  methods: {
    onFiltersSubmit(inputs) {
      this.queryVariables.search = inputs.search
    }
  },
};
```

**Comment by Akryum** [comment]
Use `deep` prop on `ApolloQuery`.

**Comment by yann-yinn** [comment]
Oh, I missed that, thanks ! And is that normal than the query is then not visible inside `this.$apollo.queries` ?

**Comment by Akryum** [comment]
Yes, it's in the `ApolloQuery` component.

**Comment by njwest** [comment]
Any chance of some example code for an ApolloQuery component with deep and refetch? I'm still not clear on how to achieve this functionality with the component...

**Comment by Akryum** [comment]
https://vue-apollo.netlify.com/guide/components/query.html#query-operations

**Comment by alexanderVu** [comment]
Sorry, but the reference docs do not cover an example code for an ApolloQuery component with deep and refetch.

**Comment by marcos-vinicius-dev** [comment]
Any solution?

**Comment by Akryum** [comment]
`this.$apollo.queries` will always empty, your component doesn't manage any query. Your query is managed by `<ApolloQuery>`.

Deep usage ([docs](https://vue-apollo.netlify.com/api/apollo-query.html#props)):

```<ApolloQuery deep>```

Refetch usage:

```
<ApolloQuery
    :query="/* query */"
    v-slot="{ result: { loading, error, data }, query }"
  >
    <!-- Display data here -->
    <button @click="query.refetch()">Refresh</button>
 </ApolloQuery>
```

[Query slot prop example](https://vue-apollo.netlify.com/guide/components/query.html#query-operations)
[SmartQuery docs](https://vue-apollo.netlify.com/api/smart-query.html#methods)

**Comment by sgarciac** [comment]
I'm using this:
In the parent component, put a ref inside the ApolloQuery, i.e.:
```
<ApolloQuery
	ref="queryComponentRef"
         //etc
```
and then you can use something like this in the parent component code when you need to refetch:
```
this.$refs.queryComponentRef.getApolloQuery().refetch();
```
