### ISSUE TITLE
Update dependency on apollo-cache-inmemory above 1.3.6

### ISSUE THREAD

**Issue by cameroncf** [Akryum/vue-apollo#540]
I'm running into a bug that I believe has been fixed in apollo-client@2.4.3 and apollo-cache-inmemory@1.3.6 per his comment/thread:
https://github.com/apollographql/apollo-client/issues/3992#issuecomment-432021595

In the current version of vue-apollo, it looks like apollo-client is tied to "^2.4.1" (ok) and apollo-cache-inmemory is tied to "^1.2.9" (not ok). 

It would be lovely to see this dependency tested and updated in the vue-apollo package.

**Comment by Akryum** [comment]
`1.3.6` matches `^1.2.9` in semantic versioning.

**Comment by cameroncf** [comment]
Oh you are 100% correct. However, I am still running into the listed problem. Might not be a version issue after all though. I'll see if I can get a good isolated test case going. Thanks!
