### ISSUE TITLE
A suggest

### ISSUE THREAD

**Issue by karonl** [Akryum/vue-apollo#55]
I have been using "this.$apollo.option" in methods, but I have not seen in the document, will later rename it?I worry the function will be removed. I feel it is useful, should write examples in the document.

**Comment by Akryum** [comment]
Well, I can make this api public (it's what powers the `apollo` option in the component description), but I may change the name. Does this seem ok for you?

**Comment by Akryum** [comment]
See [addSmartQuery](https://github.com/Akryum/vue-apollo#manually-adding-a-smart-query).

**Comment by karonl** [comment]
This is awesome! Strong expansion.
