### ISSUE TITLE
Error: Expecting a parsed GraphQL document

### ISSUE THREAD

**Issue by apertureless** [Akryum/vue-apollo#554]
I've setup a new nuxt project with `vue-apollo` and `@nuxt/apollo`.

However I am receiving the error:

```
Invariant Violation
Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql
```

# Reproduction

As mentioned it is a fresh project.

- `yarn create nuxt-app frontend`
- `cd frontend && yarn add @nuxtjs/apollo graphql-tag`

<details>
<summary>Nuxt.js apollo config</summary>

```js

  modules: ['@nuxtjs/apollo'],

  /**
   * Apollo Configuration
   */
  apollo: {
    clientConfigs: {
      default: '~/apollo/client/index.js'
    }
  },
```

</details>

<details>
<summary>Apollo Client config</summary>

```js

export default function(context) {
  return {
    httpEndpoint: process.env.NODE_ENV === 'development' ? endpoint : endpoint,
    httpLinkOptions: {
      credentials: 'include'
    }
  }
}

```

</details>

<details>
<summary>Package.json</summary>

```json
 "dependencies": {
    "@nuxtjs/apollo": "^4.0.0-rc4",
    "cross-env": "^5.2.0",
    "dotenv": "^7.0.0",
    "graphql": "^14.1.1",
    "graphql-tag": "^2.10.1",
    "nuxt": "^2.4.0"
  },
```

</details>

Now I've tried different approaches. But **all** result in the same error.

1. GQL Files

*courses.gql*

```gql

query courses {
  courses {
    id
    name
    description
  }
}

```

2. Javascript files

```js

import gql from 'graphql-tag'

export const ALL_COURSES_QUERY = gql`
  query courses {
    courses {
      id
      name
      description
    }
  }
`

```

## Example page:
I've tried to  use *gql* files, the javascript files and inline with like here:

```vue

<template>
  <div>
    <h1>Here are all available courses</h1>
    <h2 v-if="loading">Loading</h2>
    <ul v-else>
      <li v-for="course in courses" :key="course.id">
        {{ course.name }} - {{ course.description }}
      </li>
    </ul>
  </div>
</template>

<script>

/* eslint-disable */
import { ALL_COURSES_QUERY } from '~/apollo/queries'
import courses from '~/apollo/queries/courses.gql'

import gql from 'graphql-tag'

export default {
  name: 'CourseList',
  data: () => ({
    courses: null,
    loading: 0
  }),
  mounted() {
    console.log(ALL_COURSES_QUERY)
  },
  apollo: {
    courses: {
      query: gql` query courses {
               courses { id, name, description }
             }`
    },
    loadingKey: 'loading'
  }
}
</script>

```

However nothing works. If I `console.log(ALL_COURSES_QUERY)`, it is indeed an object and transformed by gql. So it's not a string or something.

**Comment by ydfzgyj** [comment]
Your `loadingKey` option was on wrong place, you must put it into the `courses` object.
Now it will be seen as a query but vue-apollo can't get query definition in it.

**Comment by bastianhilton** [comment]
For people in the future that is running into this issue, here is what i did to fix this error message in Nuxtjs.

`  apollo: {
    blogs: gql`{
        blogs {
          id
          name
          Excerpt
          image {
            url
          }
          published_at
        }
      }`
  },`

**Comment by nuochong** [comment]
me to
