### ISSUE TITLE
[bug] `skip` freezes SSR even with PR #511

### ISSUE THREAD

**Issue by beeplin** [Akryum/vue-apollo#560]
After 3.0.0-beta.28, SSR freezes with `skip` option === true. This bug is also refered in https://github.com/nuxt-community/apollo-module/issues/199. #511 meant to fix it, but the bug seems remains.  

Steps to repeat: 

1. `$ vue create test` (with lint & router)
1. `$ cd test`
1. `$ vue add apollo` (with example code & graphql server)
1. `$ vue add @akryum/ssr`
1. imports `components/ApolloExample.vue`  into `views/Home.vue` and add a `:skip="true"` in any of the`<ApolloQuery>`s in it.
1. `$ yarn apollo`
1. `$ yarn ssr:serve`
1. go to apolloExample page and refresh -- it freezes.
1. edit `vue-apollo.esm.js` with the fix in #511 and refresh
1. it still freezes.

**Comment by beeplin** [comment]
It turns out that #511 does solve the skip issue. Use `vue-apollo.esm.js` from https://github.com/ydfzgyj/vue-apollo/tree/temp/dist from @ydfzgyj and it works fine.

**Comment by Lahori-Jawan** [comment]
I am using it via `apollo-module` with `vue-apollo`: `3.0.0-rc.2` & had the same problem. After copy/pasting the above mentioned PR file, it does solve the problem but somehow it didn't get into the build i.e. `vue-apollo.esm.js`
