### ISSUE TITLE
how  to use in  vue-cli@3,and TypeScript   &&  'vue-cli-plugin-apollo/graphql-client'

### ISSUE THREAD

**Issue by keanebj** [Akryum/vue-apollo#566]
Argument of type '{ router: VueRouter; store: Store<{}>; apolloProvider: any; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Object literal may only specify known properties, and 'apolloProvider' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.

**Comment by praveenpuglia** [comment]
Duplicate of https://github.com/Akryum/vue-apollo/issues/444

**Comment by praveenpuglia** [comment]
Try this https://github.com/Akryum/vue-apollo/issues/444#issuecomment-452690462
