### ISSUE TITLE
VueComponent.provide is broken using vue-apollo

### ISSUE THREAD

**Issue by antsteyer** [Akryum/vue-apollo#571]
Hello there.

I'm using Vue-Apollo aside with Vuetify and others packages in my project. I notice that with some components of Vuetify, an error is raised in the console: `[Vue warn]: Error in beforeCreate hook: "TypeError: Cannot read property 'XXX' of undefined"`. This error never occured using only Vuetify.

VueJS Version : `2.6.10`
vue-apollo: `3.0.0-beta.28`
vuetify: `1.5.7`

I made a codesandbox to illustrate it : https://codesandbox.io/s/l4w35qmlj9?fontsize=14

**Comment by JohannesLamberts** [comment]
Seems that provide is called in https://github.com/Akryum/vue-apollo/blob/4d4cdab23e8ee56a739a4f162d06853c4e763ace/src/mixin.js#L21, but may only be called after data and props are initialized (https://github.com/vuejs/vue/blob/569b728ab19d1956bf935a98c9c65a03d92ac85f/src/core/instance/init.js#L58).

It is however only called for backwards-compatibility. You should get around the error if you add apolloProvider as option on the root Vue instance (as in https://vue-apollo.netlify.com/guide/installation.html#manual-installation).

**Comment by antsteyer** [comment]
Thank you for the explanation. 

It's actually fixed with apolloProvider option to Vue instance. I was not using it because my apollo provider is used in a script (local custom API) and I use it as a prototype to Vue.
