### ISSUE TITLE
Different loading indicator for fetchMore

### ISSUE THREAD

**Issue by keligijus** [Akryum/vue-apollo#575]
Is there any (preferred) way to differentiate between the initial query load and using fetchMore?

It seems that the only way to know when a query is loading is via `this.$apollo.queries.myQuery.loading`, but this is the same for both, the initial and calls with fetchMore.

**Comment by jeissler** [comment]
@keligijus I use the apollo query component and there is an option for smart query loading state (isLoading) as well as initial query (loading). I don't see that in the regular dollar apollo query docs anywhere, but for smart queries it seems like [watchLoading](https://akryum.github.io/vue-apollo/api/smart-query.html#options) may be what you're looking for. I've switched to using mostly apollo components so I can't answer for absolutely sure, but hopefully this will get you going in the right direction. If nothing else you might also dig into the apolloQuery component source code a bit to see what exactly its happening to differentiate between query loading/isLoading.

**Comment by keligijus** [comment]
@jeissler thanks! I've tried `watchLoading` and it works well. Thanks to your comment, I've started using `loadingKey` property and it does what I need it to do :)
