### ISSUE TITLE
$apollo directive read-only

### ISSUE THREAD

**Issue by Ethaan** [Akryum/vue-apollo#58]
while trying to update the Vue [Apollo "hello world" example app ](https://github.com/Akryum/frontpage-vue-app) im getting the following error

```
[Vue warn]: Error in render function: "TypeError: Cannot assign to read only property '1' of object '[object Array]'"

found in

---> <PostList> at /Users/Ethaan/projects/akryum/frontpage/frontpage-vue-app/src/PostList.vue
       <App> at /Users/Ethaan/projects/akryum/frontpage/frontpage-vue-app/src/App.vue
         <Root>
```

and the line that is causing this is the following

```
sortedPosts() {
   return this.posts.sort((x, y) => y.votes - x.votes);
}
```

Seems like [this directive declaration ](https://github.com/Akryum/vue-apollo/blob/4918e2fd50d11ff5a527d4403ba09e88cfa97d80/src/index.js#L100)is causing the error, adding `writable: true` should fix the issue, but maybe im loosing an obvious point here 

[Here is the repo](https://github.com/Ethaan/frontpage-vue-app) with the error

**Comment by Akryum** [comment]
Apollo results are now readonly, so you need to clone the array:

```javascript
sortedPosts() {
   return this.posts.slice().sort((x, y) => y.votes - x.votes)
}
```

**Comment by Ethaan** [comment]
Make sense, thanks =D
