### ISSUE TITLE
Queries that specify the cache-first and cache-only fetchPolicies cannot also be polling queries

### ISSUE THREAD

**Issue by morigs** [Akryum/vue-apollo#592]
Hello. I'm using vue-apollo with nuxt-apollo module.
I created a simple smart query that works perfectly. But after I added fetchPolicy and pollInterval it stopped working. I'm getting the following error in the console:
`Error Queries that specify the cache-first and cache-only fetchPolicies cannot also be polling queries.`
My query has these options:
```js
apollo: {
  dashboard: {
    query: gql`...`,
    variables: {},
    fetchPolicy: 'network-only',
    pollInterval: typeof window === 'undefined' ? null : 3000
  }
}
```

**Comment by firstaml-dima** [comment]
Same problem here.

I'm using

> fetchPolicy: 'cache-and-network',

**Comment by morigs** [comment]
I think it may be because of this

https://github.com/Akryum/vue-apollo/blob/2293adb03f23429af75723cc441ce01916699a83/src/smart-query.js#L32-L34

Or because options are not passed to the Apollo client

When I call to `query.startPolling` in the mounted hook `this.$isServer` is `false`,` query.options.fetchPolicy` is `network-only`. However, I'm getting this error because by some reason fetchPolicy in `this.$apollo.getClient().queryManager.queries.get('1').observableQuery` is set to default value `cache-first`

![image](https://user-images.githubusercontent.com/13474134/57216450-8ffff680-6ff8-11e9-96d6-18a24d6c3038.png)

**Comment by internalfx** [comment]
+1

**Comment by Blancowicz** [comment]
Same issue here

**Comment by BrockReece** [comment]
I hit this issue this morning, I found a workaround is that you can set the `pollInterval` for the query in your mounted hook. 

I also had to explicitly reset the fetchPolicy too, without this I was still getting the error above.

```js
apollo: { 
  timeline: {
    query: timelineQuery,
    fetchPolicy: 'cache-and-network'
  }
},
mounted() {
  this.$apollo.queries.timeline.setOptions({
    pollInterval: 10000,
    fetchPolicy: 'cache-and-network'
  })
},
```

I hope this helps?

**Comment by BrockReece** [comment]
BTW, I think this issue is part of the underlying `apollo-client` lib rather than being anything specific with vue-apollo.

I found this comment useful when working through my solution above.
https://github.com/apollographql/apollo-client/issues/3775#issuecomment-440266949
