### ISSUE TITLE
ApolloQuery Component Prefetch Option

### ISSUE THREAD

**Issue by jeissler** [Akryum/vue-apollo#594]
Version `"vue-apollo": "^3.0.0-beta.28"`

@Akryum It seems there is no way to set the prefetch option to false on an ApolloQuery component... there was a note in old docs that I found for `<ApolloQuery no-prefetch>` but it seems removed now. The only way I'm able to set prefetch to false is using the apollo option inside scripts... Looking at the source for the ApolloQuery component there is no prop for it. Am I really forced to use `apollo: {}` in scripts to set prefetch option on a query or is there some other workaround for the component? I really don't want to switch my apollo components out as I was enjoying how they worked until running into this. Please advise.

**Comment by pouyamiralayi** [comment]
hi! i do not know why this issue has been closed! i am experiencing the same issue and although i can work around this by using a dummy skip function, i really need this one to work because i am in a nuxt environment and using skip will keeps my loading true for ever!
cheers!
