### ISSUE TITLE
prepare is not defined

### ISSUE THREAD

**Issue by laurentpayot** [Akryum/vue-apollo#6]
I'm evaluating the amazing [Quasar](http://quasar-framework.org/) framework with vue-apollo.

Im using the following setup from the readme file in the app.js startup file (Vue being already imported by Quasar):
```javascript
import ApolloClient, { createNetworkInterface, addTypename } from 'apollo-client';
import VueApollo from 'vue-apollo';
 
// Create the apollo client 
const apolloClient = new ApolloClient({
  networkInterface: createNetworkInterface({
    uri: 'http://localhost:8080/graphql',
    transportBatching: true,
  }),
  queryTransformer: addTypename,
});
 
// Install the vue plugin 
Vue.use(VueApollo, {
  apolloClient,
});
```
and I get `Uncaught ReferenceError: prepare is not defined`, pointing [here](https://github.com/Akryum/vue-apollo/blob/master/src/vue-plugin.js#L201).

**Comment by Akryum** [comment]
May you try the latest beta.13?

**Comment by laurentpayot** [comment]
I was using the beta 9. Using the beta 13 fixed this 👍
