### ISSUE TITLE
Example uses VueApollo.collect() method which no longer exists.

### ISSUE THREAD

**Issue by skucza** [Akryum/vue-apollo#60]
./src/main.js

```
const ensureReady = apolloProvider.collect()

...

ensureReady().then(results => {
  console.log(results.length, 'queries ready')
})
```

This causes an error:

`Uncaught TypeError: apolloProvider.collect is not a function`

**Comment by ellipticaldoor** [comment]
Same error

**Comment by foxhoundhcm** [comment]
same error

**Comment by pangboww** [comment]
same error

**Comment by enginkartal** [comment]
same error

**Comment by Akryum** [comment]
@enginkartal Which example?

**Comment by zsavicreative** [comment]
so  what was the fix for this? or the cause?

**Comment by Akryum** [comment]
This was an old experimental API for SSR support.

**Comment by zsavicreative** [comment]
Thank you for the quick response. That's all I needed. All working now 😄
