### ISSUE TITLE
result data types is wrong

### ISSUE THREAD

**Issue by orblazer** [Akryum/vue-apollo#605]
Hello,
I report an problem on types.

**Problem 1** :  The `result` queries arguments is not correctly defined. This need defined with (i am not sure for loader) :
```ts
result?: (this: ApolloVueThisType<V>, result: ApolloQueryResult<R>, loader: any) => void
```
**Problem 2** : The `result` argument is wrong, when have an error the object is : `{ data: {}, error: Error, networkStatus: 8 }` except `{ data: {}, errors: [GraphQLError], networkStatus: 8 }` look the interface of `ApolloQueryResult` in apollo-client.

Note : I don't know why but for result i am obliged to specific `this` like :
```ts
result (this: ApolloVueThisType<AdmEditWebTemplatePage>, { data, loading, error }: ApolloQueryResult<{ getWebsiteTemplate: Website.WebsiteTemplate }>) {
}
```

Thanks.

**Comment by Akryum** [comment]
Should be fixed with the new types.
