### ISSUE TITLE
Dynamically change fetch policy

### ISSUE THREAD

**Issue by Blancowicz** [Akryum/vue-apollo#616]
Hi there,

I'm trying to change fetchPolicy every time the device loses connection, but anything I've tried works.

I would like to set fetchPolicy to cache-only if there's no connection, and set it back to cache-and-network when connection comes back.

Setting disableNetworkFetches or fetchPolicy to false on $apolloProvider.defaultClients does not work.
```
....
  methods: {
    onNetworkStatusChanged(status: Boolean): void {
      this.online = status;
      this.$apolloProvider.defaultClient.disableNetworkFetches = !this.online;
      this.$apolloProvider.defaultClient.fetchPolicy = this.online ? 'cache-and-network' : 'cache-only';
    },

    onNetworkStatusDown(): void {
      this.onNetworkStatusChanged(false);
    },

    onNetworkStatusUp(): void {
      this.onNetworkStatusChanged(true);
    },
  },

  created(): void {
    window.addEventListener('online', this.onNetworkStatusUp);
    window.addEventListener('offline', this.onNetworkStatusDown);
  },

  destroyed(): void {
    window.removeEventListener('online', this.onNetworkStatusUp);
    window.removeEventListener('offline', this.onNetworkStatusDown);
  },
....
```

Can I disable fetching from network dynamically in some way?

**Comment by Blancowicz** [comment]
Just for closing,

the best way I've found to manage __fetchPolicy__ depending on network status is to use __fetchPolicy__ as function on every query. That way changes on $root.online will set the correct value.

As example, our generic list component query looks like this:
```javascript
apollo: {
  results: {
    query() {
      return this.query;
    },
    [...]
    fetchPolicy() {
      return !this.$root.online ? 'cache-only' : 'cache-and-network';
    },
    debounce: 500,
  },
},
```
This way the query will not trigger a network request if there's no connection.

**Comment by rafael-paiva** [comment]
Are you sure this works? I have tried to do the same but in my case it doesn't work. Apparently the `fetchPolicy` function is never called. I'm intrigued about how it worked for you 🤔

**Comment by Blancowicz** [comment]
Hi @rafael-paiva, you should recreate your apollo provider to trigger that change, as you say that function will not be called unless a new `new VueApollo({...})` is used.

When facing this problem it was quite simple to solve because we can just "reload" the app when entering in offline mode, so apollo used cache.
