### ISSUE TITLE
Prefetch not working?

### ISSUE THREAD

**Issue by Austio** [Akryum/vue-apollo#623]
Copying this from @homerjam https://github.com/nuxt-community/apollo-module/issues/210

But am experiencing on a project.  We are moving from a custom built SSR to nuxt and we are unable to get the state of our apollo queries before the component renders.  

In our beforeNuxtRender the value of the cache.extract() is an empty object.
```
  beforeNuxtRender(({
      nuxtState
    }) => {
      nuxtState.apollo = ApolloSSR.getStates(apolloProvider);
    });
  }
```

![Screenshot from 2019-05-22 16-29-33](https://user-images.githubusercontent.com/1709860/58210383-db7bfb00-7cae-11e9-8396-ef745daf6f92.png)

**Comment by MarcelloTheArcane** [comment]
I'm finding this within the `computed` property, which ends up throwing a nuxt error (blanking the entire page)

**Comment by Akryum** [comment]
Can't reproduce: 

![image](https://user-images.githubusercontent.com/2798204/67194046-a824d000-f3f6-11e9-8d97-ea9d61447fe2.png)

**Comment by homerjam** [comment]
@Akryum the issue refers to SSR - I'm not sure why but we no longer seem to get the server side `console.log` in CodeSandbox. Previously it read:

```
server: true allCars: undefined
```

Possibly you only get it in editor mode??

**Comment by Akryum** [comment]
Well, when the component instance is created on the server, the data isn't available in the `created` hook because the apollo query needs to be completed and it takes time.

**Comment by homerjam** [comment]
Does that mean vue-apollo officially doesn't support SSR - eg. Nuxt universal?
