### ISSUE TITLE
Interface 'VueApolloMutationOptions<V, R>' incorrectly extends interface 'MutationOptions<R, OperationVariables>'

### ISSUE THREAD

**Issue by orblazer** [Akryum/vue-apollo#628]
Hello,
I have update to `3.0.0-beta.30` but now i have an error when build my project.

The error :
![Screenshot_20190524_182018](https://user-images.githubusercontent.com/1344792/58342454-b2936b80-7e50-11e9-9ce1-7da76ca0769b.png)

Thanks.

**Comment by iharmanpannu** [comment]
already submitted PR #627

**Comment by orblazer** [comment]
oh ok @iharmanpannu i have miss check in the PR, by bad
