### ISSUE TITLE
 Cannot read property 'freezeResults' of null

### ISSUE THREAD

**Issue by le0l1** [Akryum/vue-apollo#630]
current version: ^3.0.0-beta.11
error message:
![image](https://user-images.githubusercontent.com/20632096/58415628-a0643800-80b1-11e9-84ea-181aa97fae70.png)

I found the reason is about `apollo-cache-inmemory@1.6.0`, the new version asks the cache config cannot be null
https://github.com/apollographql/apollo-client/blob/d9e93e31fa40da6d9ee55e99e8e1cb114dba6639/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L133
![image](https://user-images.githubusercontent.com/20632096/58415922-91ca5080-80b2-11e9-97c2-2d2daed2e0d7.png)

and now I can only reinstall apollo-cache-inmemory@1.5.1 to lock the version

**Comment by piemekanika** [comment]
Had the same problem.

**Comment by rigwild** [comment]
Related to #631 

Another workaround was given by @danrocha by editing the `vue-apollo.js` file:

> ```js
> import { InMemoryCache } from 'apollo-cache-inmemory';
> 
> const defaultOptions = {
>   // ...
>   // Override default cache
>   cache: new InMemoryCache(),
> }
> ```
