### ISSUE TITLE
Can we use this package in an Electron-Vue project?

### ISSUE THREAD

**Issue by OpsSingular** [Akryum/vue-apollo#64]
Not sure if this is the right place to ask but wondering if this package can be used from within -Electron-Vue(https://simulatedgreg.gitbooks.io/electron-vue/en/) to communicate to a Apollo server?

**Comment by Samuell1** [comment]
Yes you can it will work like charm! 👍

**Comment by OpsSingular** [comment]
@Samuell1  Oh good to know... I am using Electron-Vue boilerplate and i don't seem to understand where i need to add the packages related to Apollo i.e inside the Main process or inside the Renderer? I have tried both ways but none work. May i ask what was your approach and how you got this working? a code snippet would be brillant

**Comment by Samuell1** [comment]
Main process is only for Electron, you need to put Apollo in Renderer and bind in on Vue :)

**Comment by OpsSingular** [comment]
@Samuell1 thanks for the information. I am able to get a simple project running. There were couple of errors but none related to Vue-Apollo.
