### ISSUE TITLE
refetching a query breaks loadingKey if no new data is returned

### ISSUE THREAD

**Issue by manukall** [Akryum/vue-apollo#65]
at least i think that's what's causing it.

here's what happens: when i call `this.$apollo.queries.myQuery.refetch()` on a query with `loadingKey`, loading key gets increased but not decreased when the query finishes. i'm pretty sure that it happens when the data returned from my server has not changed. and i think it's because `next` is not called on the observer in this case. i'm not sure how to fix this, though. any pointer?

**Comment by Samuell1** [comment]
I think i have same issue

**Comment by manukall** [comment]
@Samuell1 i've submitted a pull request that fixes this issue for me at https://github.com/Akryum/vue-apollo/pull/74. maybe give it a try and report back if it works for you, too.

**Comment by Samuell1** [comment]
@manukall yes your fix is working for me
