### ISSUE TITLE
Testing vue-apollo using vue-test-utils

### ISSUE THREAD

**Issue by praveen7557** [Akryum/vue-apollo#656]
I am new to testing and GraphQL. I am trying to test my VueJS app which uses GraphQL using vue-test-utils and jest. I have a component which gets the categories from a graphql server in mounted hook.

```
mounted() {
  this.$apollo
    .query({
      query: getCategories
    })
    .then(res => {
      this.categoriesData[0].options = res.data.categories;
    });
}
```
In my `StepTwo.spec.js` in I am adding Vue-apollo to vue instance.

```
const Vue = createLocalVue();
Vue.use(VeeValidate);
Vue.use(BootstrapVue);
Vue.use(VueApollo);

test("Step Two ", async () => {
  const wrapper = shallowMount(StepTwo, { localVue: Vue });
});
```
When I'm trying to mount my component I'm getting  `TypeError: Cannot read property 'query' of undefined`. Any help would be appreciated.

I have posted the same question in SO also: https://stackoverflow.com/questions/56525280/testing-vue-apollo-using-vue-test-utils

**Comment by Austio** [comment]
IMO you should not test apollo as part of unit tests.  That is something more fitting for an integration test with cypress, webdriver/other selenium variant.

To enable this, we have a wrapper that mounts vue inside of our app with all the stuff that is specific to our setup.  For apollo, we set our `component.apollo = undefined` before calling mount.

With this, you can test your component like a function by setting the data values you need and ensure thing are rendered properly.
