### ISSUE TITLE
Update docs on https://akryum.github.io

### ISSUE THREAD

**Issue by ralph** [Akryum/vue-apollo#662]
Hi, I've realised that the documentation on the master branch on Github is more up to date than the version published on https://akryum.github.io.

Example:
* Github: https://github.com/Akryum/vue-apollo/blob/master/docs/guide/local-state.md
* Website: https://akryum.github.io/vue-apollo/guide/local-state.html

Could you update the docs on https://akryum.github.io to reflect the latest changes?

**Comment by Akryum** [comment]
That's not the docs website, I forgot to delete the GitHub pages.

**Comment by ralph** [comment]
Whoa you're right, the correct one is https://vue-apollo.netlify.com. I guess I ended up on GH pages by using Google. Good that you deleted the old version, this was causing some confusion.
