### ISSUE TITLE
Global mutation error handler (interceptor)?

### ISSUE THREAD

**Issue by ZaidBarghouthi** [Akryum/vue-apollo#670]
this error handler doesn't intercept mutation errors

```js
export default new VueApollo({
  defaultClient: client,
  defaultOptions: {
    $query: {
      fetchPolicy: 'cache-and-network',
    },
  },
  errorHandler(error) {
    // works for queries only
  },
});
```

am I doing something wrong? what is the right way? is there such a thing?

**Comment by ZaidBarghouthi** [comment]
solved.

```js

const errorHandler = onError(({ networkError, graphQLErrors }) => {
  console.log({ graphQLErrors, networkError})
  if (networkError && networkError.statusCode === 401) {
    window.location = '/login'
  }
})


const client = new ApolloClient({
  link: from([
    // order matters
    acceptJsonMiddleware,
    errorHandler,
    httpLink,
  ]),
  cache,
});
```

**Comment by go4cas** [comment]
Thanks, @ZaidBarghouthi! 

Was struggling with this.

Now, I can see the errors logged in the console, from the global handler, but how do I access these errors from within a component?

I am using `<ApolloQuery>` and `<ApolloMutation>`. For mutations, the `error` and `gqlError`from `<template v-slot="{ mutate, loading, error, gqlError }">` is always empty.

Any ideas?

**Comment by go4cas** [comment]
It seems it works fine for `<template v-slot="{ result: { loading, error, data }, query }">`, in `<ApolloQuery>`, but not for mutations.

**Comment by jrglaber** [comment]
Hello, i'm the problem:

apollo.js?c149:31 Uncaught ReferenceError: from is not defined

**Comment by SilentDepth** [comment]
Sorry for bothering in this closed issue, but I wonder if there is or will be a global error handler for mutations? The error link solution is sure a way to do that, however since there is already a `errorHandler` in apollo provider options capturing errors of smart queries and subscriptions, why not expand its ability to cover mutations?

**Comment by samuelhgf** [comment]
@ZaidBarghouthi Where did you get this function onError? I tried to implment and get onError is not defined

**Comment by ZaidBarghouthi** [comment]
@samuelhgf,

```js
import { onError } from 'apollo-link-error'
```

**Comment by gustawdaniel** [comment]
@ZaidBarghouthi I was trying to use your solution but have

```
 from is not defined
```

**Comment by liaoliaojun** [comment]
I use `concat` handlerError link

```
import {HttpLink} from 'apollo-link-http'
import {onError} from 'apollo-link-error'

const httpLink = new HttpLink({
  uri: 'xxx',
  credentials: 'include',
})

const errorHandler = onError(({ networkError, graphQLErrors }) => {
  console.log({ graphQLErrors, networkError})
})

new ApolloClient({
  link: errorHandler.concat(httpLink),
});
```

**Comment by developernaren** [comment]
> solved.
> 
> ```js
> const errorHandler = onError(({ networkError, graphQLErrors }) => {
>   console.log({ graphQLErrors, networkError})
>   if (networkError && networkError.statusCode === 401) {
>     window.location = '/login'
>   }
> })
> 
> 
> const client = new ApolloClient({
>   link: from([
>     // order matters
>     acceptJsonMiddleware,
>     errorHandler,
>     httpLink,
>   ]),
>   cache,
> });
> ```

where do you add this code and from where did you import `acceptJsonMiddleware` and `httpLink`. I just cannot seem to get this working.

**Comment by developernaren** [comment]
@ZaidBarghouthi thanks

**Comment by tiago-henriquem** [comment]
Hey, what about interceptor in request and not a error handling? Before request been executed? Like axios.interceptors.request.use function


Like use a header's parameter dinamically in request interceptor

**Comment by tiago-henriquem** [comment]
Like use a header's parameter dinamically in request interceptor
