### ISSUE TITLE
Typescript typings errors

### ISSUE THREAD

**Issue by airgram** [Akryum/vue-apollo#672]
Some typings have errors. Please check out [pull request 671](https://github.com/Akryum/vue-apollo/pull/671).

1. The [following typings](https://github.com/Akryum/vue-apollo/blob/master/types/vue-apollo.d.ts#L56-L58) are for smart requests and inconsistent with `apollo-client` typings.
```
export interface DollarApollo<V> {
 // ...
  query<R=any>(options: VueApolloQueryOptions<V, R>): Promise<ApolloQueryResult<R>>;
  mutate<R=any>(options: VueApolloMutationOptions<V, R>): Promise<FetchResult<R>>;
  subscribe<R=any>(options: VueApolloSubscriptionOptions<V, R>): Observable<FetchResult<R>>;
```

2. Interface [`VueApolloSubscriptionOptions`](https://github.com/Akryum/vue-apollo/blob/master/types/options.d.ts#L63) has missed option `client`.

```
export interface VueApolloSubscriptionOptions<V, R> extends SubscriptionOptions {
  query: DocumentNode;
  variables?: VariableFn<V>;
  skip?: (this: ApolloVueThisType<V>) => boolean | boolean;
  result?: (this: V, data: FetchResult<R>) => void;
}
```

3. Argument `data` in callback [`result`](https://github.com/Akryum/vue-apollo/blob/master/types/options.d.ts#L40) has type `ApolloQueryResult<R>`, but no `R`
```
interface ExtendableVueApolloQueryOptions<V, R> extends _WatchQueryOptions {
  // ...
  result?: (this: ApolloVueThisType<V>, data: R, loader: any, netWorkStatus: NetworkStatus) => void;
}
```

**Comment by Akryum** [comment]
Should be resolved in latest versions.
