### ISSUE TITLE
Broken subscriptions on top of queries with reactive variables

### ISSUE THREAD

**Issue by jpikora** [Akryum/vue-apollo#677]
I'm creating this issue to raise up the persisting problem since version `3.0.0-beta.25`. There was a discussion directly on commit which caused this bug, so I'll just link it here for the reference: https://github.com/Akryum/vue-apollo/commit/202103a1521592ce21f4145de52489c6704e6da4

**Comment by Akryum** [comment]
A runnable reproduction would be very appreciated so I can jump on this issue when I have the time :)

**Comment by SlIdE42** [comment]
In order to circumvent the problem, you need to refresh subscriptions manually after updating a reactive query:
```JavaScript
Object.keys(this.$apollo.subscriptions).map(subscription => {
  this.$apollo.subscriptions[subscription].refresh();
});
```
