### ISSUE TITLE
Could I create local component in Template?

### ISSUE THREAD

**Issue by thearabbit** [Akryum/vue-apollo#69]
```html
<template>
   ..........
   <my-component></my-component>
</template>
-------
<script>
var Child = {
  template: '<div>A custom component!</div>'
}

export default {
  // ...
  components: {
    'my-component': Child
  }
}
</script>
```

**Comment by Akryum** [comment]
Hi! Thanks for filling up this issue, but it seems like a general Vue question unrelated to vue-apollo. Please ask your question in more appropriate places like the official VueJS forums or the gutter.

**Comment by thearabbit** [comment]
Sorry, I should be post this to `vue-meteor`.
