### ISSUE TITLE
Missing ... attribute on result

### ISSUE THREAD

**Issue by emahuni** [Akryum/vue-apollo#700]
Hi. Great package! I am not sure issue #10 was fixed seeing that it is still happening. I am brand new to this package and i followed the example in Usage in Vue exactly as given and it seems like I ran into this issue. I got it working after implementing the workaround `update....` So I am reopen this here to have this fixed.

Here is some code that is similar to the [documentation](https://vue-apollo.netlify.com/guide/apollo/#queries), but producing the bug: 
```vue
<template>
  <div v-for="opt of options">
    {{opt.label}}
  </div>
</template>

<script>
  import gql from 'graphql-tag';

  export default {
    apollo: {
      options: gql` query {
          agentStatus {
            label
          }
        }`
    },
  };
</script>
```

throws:
```js
Missing options attribute on result
```

The following works, but it is not as desirable as the documented; terse and much cleaner and intuitive.
```vue
<template>
  <div v-for="opt of options">
    {{opt.label}}
  </div>
</template>

<script>
  import gql from 'graphql-tag';

  export default {
    apollo: {
      options: {
        query: gql` {
          agentStatus {
            label
          }
        }`,
        update(data) {
          return data.agentStatus;
        },
      },
    },
  };
</script>
```

**Comment by emahuni** [comment]
Oh yah, I used `apollo-boost` to get up and going, maybe that's where the issue is originating from.

**Comment by Akryum** [comment]
Apollo won't guess which data you want to put in the component from the query result. By default, it will just try the one you are using in the component, in this case `options`. If the names don't match, you can either use `update` which is available for this purpose, or rename the field in the document directly:

```gql
query {
  options: agentStatus {
    label
  }
}
```

**Comment by emahuni** [comment]
yah sorry I figured this out and had come here to correct myself thanks after playing around with it for a while, now I understand more what's going on. But I think this should be mentioned in the documentation so that you don't have newbies scratching their heads and going like aaaahhhhh noooo! bug! Please update the docs otherwise this will always happen.

**Comment by emahuni** [comment]
I added your explanation in the docs in a newbie's approach 😅 and an example, about to do a PR...

can you please put:
```js
query {
  options: agentStatus {
    label
  }
}
```
 in the following syntax example?  I have don't this:
```js
 apollo: {
      agentStatus:
        gql` query {
          agentStatus {
            label
          }
        }`,
    },
```
and it's not working

**Comment by emahuni** [comment]
created a PR, you need to edit that part I am not clear with
Clarify a common newbie gotcha #702

**Comment by adarisGmbH** [comment]
I'm taking advantage of the fact that GQL allows for several queries to coexist in a single request, like so:
`
query globalsearch($keyword: String!) {  
  crm {
    contacts (filter: { byName: { search: $keyword } })
    {
      items 
      {        
        oid    
        firstName      
      }             
    }
  }

  courseMgmt {
    courses (filter: { byName: { search: $keyword } })
    {
      items 
      {            
        name
        status      
      }             
    }
  }

  sales{  
    salesInvoices(filter: { byKeyword: { search: $keyword }    })
    {
      items { 
        oid
        date
        number
      }
    }
  }    
}
`
This throws an exception named "Missing gloabalSearch attribute on result". I don't understand why. I explicitly want three independent arrays to be returned from the server in one request. Thoughts?

**Comment by paul121** [comment]
A simpler solution was mentioned in the above commit: https://github.com/vuejs/vue-apollo/commit/6d270b16c822ddb83819664666fc0a020b679300

Copying it here so that others coming across this issue might see it.

> You can also rename the field in the GraphQL document directly:
>
> ```js
> apollo: {
>   world: gql`query {
>      world: hello
>   }`
> }
> ```

**Comment by Toni-hr98** [comment]
Is it possible to merge the query to 1 request. as an array? 

```
query example($locale:String) {
    cookiemelding: globalSets(handle: "cookiemeldingPlein", siteId: $locale) {
        ... on cookiemeldingPlein_GlobalSet {
            id
            siteId
            avgTekst
            cookiemelding {
                   id
                 title
            }
        }
    }
    footer: globalSets (handle: "footerPlein", siteId: $locale) {
        ... on footerPlein_GlobalSet {
            id
            title
        }
    }
}


export default {
apollo: {
		cookiemelding: {
			query: global,
			variables() {
				return {
					locale: "4"
				}
			}
		},
		footer: {
			query: global,
			variables() {
				return {
					locale: "4"
				}
			}
		}
	},
}

```

**Comment by Toni-hr98** [comment]
I tried everything, but cant figure it out... i would love to get something like this:

```
query example($locale:String) {
    cookiemelding: globalSets(handle: "cookiemeldingPlein", siteId: $locale) {
        ... on cookiemeldingPlein_GlobalSet {
            id
            siteId
            avgTekst
            cookiemelding {
                   id
                 title
            }
        }
    }
    footer: globalSets (handle: "footerPlein", siteId: $locale) {
        ... on footerPlein_GlobalSet {
            id
            title
        }
    }
}


export default {
apollo: {
		globals: {
			query: global,
			variables() {
				return {
					locale: "4"
				}
			}
		}
	},
}


vue example:

globals.footer[0].title

or 

globals.cookiemelding[0].title
```
