### ISSUE TITLE
NO reactive data property when using addSmartQuery()

### ISSUE THREAD

**Issue by joelmandell** [Akryum/vue-apollo#706]
I get an error in the console when I am manually adding a Smart Query.

![bild](https://user-images.githubusercontent.com/109020/61459227-91d92500-a96c-11e9-8794-1c4baa024170.png)

And the code is as follows:

![bild](https://user-images.githubusercontent.com/109020/61459272-a9181280-a96c-11e9-887a-2f3641994727.png)

If a declare property on the data object it works. Is addSmartQuery not creating the properties?

**Comment by Akryum** [comment]
This is expected behavior. By using `addSmartQuery` manually, vue-apollo can't automatically add the corresponding data property in the `data` option. In this case, you have to do it yourself.

**Comment by joelmandell** [comment]
Is it by design or could it be possible to implement? 
What if a PR on this?

**Comment by Akryum** [comment]
This is by design.

**Comment by joelmandell** [comment]
Okay so not any chance for accepting a possible PR? 😊
