### ISSUE TITLE
Retreive flattened data from apollo

### ISSUE THREAD

**Issue by metalmatze** [Akryum/vue-apollo#71]
Hey, so far a really nice experience. :+1: 
Right now I'm wondering, if it's somehow possible to get flattened data from apollo, when doing nested queries.
Thanks!

**Comment by Akryum** [comment]
Well, you can do it yourself. :smile:
One of the main principle of GraphQL is you get what you ask for, which also means the answer matches the query as much as possible.

**Comment by metalmatze** [comment]
Yep. I'm already flattening the responses before storing inside of vuex.
To be more specific: Is there a way to get the data which is stored inside of apollo's cache? Because from what I can see that data is already flattened.
If this is not possible, I will simply continue to flatten it myself.

**Comment by stubailo** [comment]
What do you mean by "flattened"? It would help to have a more concrete use case. Also, do you get a big benefit by storing the data into VueX?

**Comment by ralphchristianeclipse** [comment]
I think vuex has no sense in graph ql as the queries are already cached in the apollo client store maybe if someone can map the vuex store to the apollo store it would be better

**Comment by tadejstanic** [comment]
@metalmatze  I'm also curious what is the reason behind using Vuex along with Apollo?

**Comment by timpharo** [comment]
Other state stored apart from that retrieved using graphql seems to make sense, such as user input data, but as @ralphchristianeclipse has mentioned i also think that mapping Vuex store to Apollo store would make sense

**Comment by Austio** [comment]
At least for me, the data coming from apollo would be immutable if it were in vuex or redux or anywhere really, so it is fine leaving in redux.

In the Apollo Roadmap they mention that they are shooting for a pluggable store. 
 Once that happens would be great to create a plug for vuex https://github.com/apollographql/apollo-client/blob/master/ROADMAP.md
