### ISSUE TITLE
Variable prop doesn't accept full object and results to undefined

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Akryum/vue-apollo#72]
### Problem
I'm passing a full object in the variables prop in the apollo mutate method 

Like this

```javascript
	mounted() {
		
		this.$apollo.mutate({
			mutation: gql.mutations.saveProduct,
			variables() {
				console.log(this);
				return {...this.product}
			}
		})
	}
```
### Expected Result
I'm expecting that it would be valid and graph ql will use the full object
### Unexpected Result

But it results to this

![image](https://user-images.githubusercontent.com/25447231/27000377-9b9df968-4de2-11e7-8ddf-21843579df15.png)

Any Thoughts?

**Comment by ralphchristianeclipse** [comment]
Ok found the answer like this
```javascript
		this.$apollo.mutate({
			mutation: gql.mutations.saveProduct,
			variables: this.product
		})
```

**Comment by Samuell1** [comment]
If you use this.$apollo you cant use variables as function, it needs to be a object
```
		this.$apollo.mutate({
			mutation: gql.mutations.saveProduct,
			variables: { ...this.product }
		})
```
