### ISSUE TITLE
"TypeError: Cannot read property 'defaultClient' of undefined"

### ISSUE THREAD

**Issue by imd-solutions** [Akryum/vue-apollo#761]
Hi,

I implemented Apollo/ GraphQL into my Nativescript-vue project, but since I did the update to NativeScript 6, I am getting the above error.

Would appreciate any help.

Thanks

**Comment by Austio** [comment]
@imd-solutions could you please setup a reproducable repo for this?

**Comment by imd-solutions** [comment]
Hi,

Sorry for the delay. I have managed to fix the issue.

I couldn't tell you what the problem was as I had to reinstall my Mac OS system and start again.

Thanks for you help.

**Comment by souljorje** [comment]
Solution: https://github.com/nuxt-community/apollo-module/issues/298#issuecomment-670970029
