### ISSUE TITLE
Error update vue-apollo

### ISSUE THREAD

**Issue by felisio** [Akryum/vue-apollo#77]
Hi, i am update version "vue-apollo": "^1.3.0" for "vue-apollo": "^2.1.0-beta.9" and plot this error:
![captura de tela 2017-06-28 as 10 36 59](https://user-images.githubusercontent.com/647676/27639904-1a129c7c-5bee-11e7-9fa0-24458de18358.png)

I update apollo client to for "apollo-client": "^1.6.0". Any ideia? Thanks

**Comment by Austio** [comment]
Have you recently updated node?  Either way would try this first.

1. npm/yarn install
2. Remove node_modules/node cache and reinstall

**Comment by gijo-varghese** [comment]
@felisio install because you're trying to install vue-apollo 2.0. User `"apollo-client": "^1.9.3",` 

2.0 support is coming soon https://github.com/Akryum/vue-apollo/issues/117
