### ISSUE TITLE
Typescript: Property 'myProperty' does not exist on type 'Vue'.

### ISSUE THREAD

**Issue by Nick-Ewer** [Akryum/vue-apollo#780]
Given the code below, the property being referenced in the apollo query will error with this error:
`Property 'myProperty' does not exist on type 'Vue'.ts(2339)`

```
@Component({
  apollo: {
    myQuery: {
      variables() {
        return {
          // this.myProperty does not exist on type 'Vue'
          someVariable: this.myProperty,
        }
      }
    }
  }
})
export default class MyComponent extends Vue {
  public myProperty: string = 'hello';
}
```
This error does not occur in version of `vue-apollo` prior to `3.0.0-rc.3`.

**Comment by ralph** [comment]
I have the same error. Currently, I use this workaround to avoid errors:

```typescript
variables() {
  const _this = this as MyComponent
  return {
    someVariable: _this.myProperty
  }
}
```

**Comment by chanlito** [comment]
Yes saw these errors. BTW if you use class components, you should try https://www.npmjs.com/package/vue-apollo-decorator I think it's easier this way.

**Comment by Tinoooo** [comment]
The issue still prevails for me.

That's my code:
```javascript
export const Component = Vue.extend({
  render(h: CreateElement): VNode {
    return h(SomeComponent, {
      props: {
        items: this.items // <--
      }
    });
  },
  apollo: {
    items: {
      query: QUERY_ITEMS
    }
  }
});
```
