### ISSUE TITLE
Resend auth headers through websocket when logged in

### ISSUE THREAD

**Issue by MarcelloTheArcane** [Akryum/vue-apollo#783]
Related to https://github.com/Akryum/vue-apollo/issues/520, but this is about websocket headers.

I am using this as `~plugins/apollo.js`:

```js
export default context => {
  const client = context.app.apolloProvider.defaultClient
  const token = context.app.$apolloHelpers.getToken()

  client.wsClient.connectionParams = () => {
    return {
      headers: {
        Authorization: token || '',
      },
    }
  }
}
```

Which works fine for setting the authorization token _if the user is logged in on initial load_.

However, if the user is not logged in _initially_, none of the subscriptions will work even **after** logging in.

Is there a way to refresh the client connection params once the user has logged in, and there is a token?

**Comment by Avyiel** [comment]
The solution is to restart the websockets after login. You can do something like this:

```javascript
import {restartWebsockets} from 'vue-cli-plugin-apollo/graphql-client';

export async function onLogin(apolloClient, token) {
  if (typeof localStorage !== 'undefined' && token) {
    localStorage.setItem(AUTH_TOKEN, token);
  }
  // this is the key part here
  if (apolloClient.wsClient) restartWebsockets(apolloClient.wsClient);
  try {
    await apolloClient.resetStore();
  } catch (error) {
    console.log('%cError on cache reset (login)', 'color: orange;', error);
  }
}
```

This function saves pending subscriptions, force-closes the connection (to avoid automatic reconnects) and then restores the saved subscriptions. [Source is here.](https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/graphql-client/src/index.js#L184)

**Comment by Akryum** [comment]
I'm closing since this is not related to the repository.
