### ISSUE TITLE
$apollo.loading is always 0

### ISSUE THREAD

**Issue by AdamNimDev** [Akryum/vue-apollo#788]
I'm having trouble linking page/element loading states to Apollo's loading state. The value seems to never update.

I am running a query in a method like this: 

```methods: {
    login() {
        await this.$apollo.query({
            query: login,
            fetchPolicy: "network-only"
        });
    }
}

```

...and my element is linked to the loader like this :loading="$apollo.loading"

I don't have any errors at all during the entire auth process utilising vue-apollo's onLogin method. 

Vue cli project using:
 "vue-apollo": "^3.0.0-beta.11",
 "vue-router": "^3.0.3",
 "vuetify": "^2.0.0"

**Comment by Akryum** [comment]
Doing queries manually won't update `$apollo.loading`. Also in your example maybe you want to do a mutation instead.

**Comment by austinbv** [comment]
We also noticed that `network-only` cache policys don't update the apollo loading state
