### ISSUE TITLE
Can't mock $apollo, readonly value

### ISSUE THREAD

**Issue by johnrazeur** [Akryum/vue-apollo#798]
Hi,

I can't mock $apollo with @vue/test-utils, I have got the following error:

> [vue-test-utils]: could not overwrite property $apollo, this is usually caused by a plugin that has added the property as a read-only value

The code which throw the error is:

```javascript
const query = jest.fn().mockResolvedValue({ data: { login: { token: 'token' } } });
const wrapper = mount(Login, {
  localVue,
  mocks: {
    $apollo: {
      query,
      provider: {
        defaultClient: jest.fn(),
      },
   },
 },
});
```

How can I mock $apollo in my jest test ?

Thanks for your help !

**Comment by georgyfarniev** [comment]
Hello @johnrazeur, solution that comes to my mind is to NOT install vue-apollo plugin in case if you use components for test (e.g., exclude Vue.use(VueApollo)), and therefore you will not overwrite anything. Please let me know if it solves your problem.

**Comment by johnrazeur** [comment]
Yes, I exclude the Vue.use(VueApollo) when NODE_ENV is test, and it works !
Thank you for your help !
