### ISSUE TITLE
Why is the previousResult in upadateQuery() equal to the current result?

### ISSUE THREAD

**Issue by stique** [Akryum/vue-apollo#80]
Hi! I've got a little trouble with updating a previous query on my vue-apollo app. Here is my code:

```javascript
apollo: {
        services: {
            query() {
                return servicesQuery;
            },
            loadingKey: 'servicesLoading',
            variables() {
                return {
                    session_id: this.sessionId,
                    first: this.firstItemInQuery,
                    offset: this.offset,
                }
            },
...
methods: {
        showMoreServices(event) {
            event.stopPropagation();
            this.firstItemInQuery += this.offset;
            this.$apollo.queries.services.fetchMore({
                variables: {
                    first: this.firstItemInQuery,
                    offset: this.offset,
                },
                // Mutate the previous result
                updateQuery: (previousResult, { fetchMoreResult }) => {
                    const newServices = fetchMoreResult.services.items;
                    const hasMore = fetchMoreResult.services.hasMore;

                    console.log(previousResult.services.items); // is equal to newServices
                    console.log(newServices);

                    this.showMoreEnabled = hasMore;
                    return {
                        services: {
                            items: [
                                ...previousResult.services.items,
                                ...newServices,
                            ],
                            hasMore,
                        },
                    };
                },
            });
        },
```
As a result, I get an array consisting of two equal parts each equal to the newServices. Could you please explain what my mistake is and how to fix it? Thanks in advance!

**Comment by stubailo** [comment]
It looks like you're passing the same query twice?

> first: this.firstItemInQuery,

Seems like for the `fetchMore` it should be maybe the last item from the previous query, or have a different offset or something?

**Comment by stique** [comment]
> It looks like you're passing the same query twice?

I think I don't. firstIteminQuery is always being updated before the updateQuery() is called:
```javascript
this.firstItemInQuery += this.offset;
```
And it's really the new query because when it is sent in the second time I'm receiving the fresh data with the first item equal to 50 (in the case of offset is 50).

**Comment by stubailo** [comment]
Can you post your query as well?

**Comment by stique** [comment]
Sure! Here you are!

```javascript
const servicesQuery = gql`
    query services($session_id: String!, $first: Int!, $offset: Int!) {
        services(session_id: $session_id, first: $first, offset: $offset) {
            hasMore
            totalCount
            items {
                service_id
                ...
                autorenew {
                    enabled
                    ...
                }
                state_alerts {
                    type
                    l10n_key
                    l10n_params {
                        ...
                    }
                    actions {
                        type
                    }
                }
            }
        }
    }
`;
```
Sorry but some fields are still hidden with ellipsis by me. Though the structure corresponds to reality.

**Comment by Akryum** [comment]
Maybe you can share a full repro of this issue?

**Comment by mekhami** [comment]
I'm having this same issue but cannot share the reproduction.

**Comment by mekhami** [comment]
On a gut instinct, @Akryum it seems like the previousResult object is being updated to the new query result before fetchMore.updateQuery() is being called.

**Comment by mekhami** [comment]
Also, I'm noticing when I fetchMore and the result set is empty, it empties out my entire state for that query. There's definitely a big problem with fetchMore and updateQuery here.

**Comment by Samuell1** [comment]
I using this and its working fine:

```
        updateQuery: (previousResult, { fetchMoreResult }) => {
          if (!fetchMoreResult) { return previousResult }
          return Object.assign({}, previousResult, {
            recordsOfAnimalsPaginated: {
              __typename: 'RecordPaginated',
              data: [...previousResult.recordsOfAnimalsPaginated.data, ...fetchMoreResult.recordsOfAnimalsPaginated.data],
              totalCount: fetchMoreResult.recordsOfAnimalsPaginated.totalCount
            }
          })
        }
```

**Comment by mekhami** [comment]
@Samuell1 what version of vue-apollo and apollo-client are you on, out of curiosity? When I console.log previousResult, it's not equal to the ROOT_QUERY state, which I would expect it to be.

**Comment by mekhami** [comment]
```        updateQuery: (previousResult, { fetchMoreResult }) => {
          console.log('previous', previousResult)
          console.log('fetchmore', fetchMoreResult)
          console.log(fetchMoreResult.samplePage.samples === previousResult.samplePage.samples)
          const newSamples = fetchMoreResult.samplePage.samples
          const hasMore = fetchMoreResult.samplePage.hasMore

          return {
            samplePage: {
              __typename: previousResult.samplePage.__typename,
              samples: [...previousResult.samplePage.samples, ...newSamples],
              hasMore
            }
          }
```

This is my updateQuery code,you can see I am including the __typename.

When I console.log the previous and fetchmore results, they don't match with expectations.

I have open apollo dev tools. My initial page state loads with the watched query, page 0, renders correctly.

When I call this showMore function, I see a second watched query, with page 1, but also the original query that was page 0 is also page 1, meaning I have duplicated records in my store. I have page 1 twice. It makes sense if previousResult is updating before updateQuery is called, because my returned object will be [...page1, ...page1]. That's the behavior I'm seeing.

If I call showMore again, I have three watched queries. The original query is now on page 2, then there's a page 1 and a page 2 query. Again, previousResult seems to be the page 2 query, and it makes sense as my current store has [...page2, ...page2] as its state.

**Comment by Samuell1** [comment]
@mekhami i using 
apollo-client:1.9.2
vue-apollo: 2.1.0-rc.5

**Comment by mekhami** [comment]
I'm on the same thing except vue-apollo: 2.1.0-rc.4

**Comment by mekhami** [comment]
There's also an interesting problem in that, when I look at the Apollo client state, this query is not being added as a member of the ROOT_QUERY.

I have ROOT_QUERY.foo.0, ROOT_QUERY.bar.0, but it doesn't show this ROOT_QUERY.samplePage.0, which I would expect it to populate.

**Comment by mekhami** [comment]
For posterity, here is the apollo instance for this component.

```
  apollo: {
    samplePage: {
      query: SAMPLES_QUERY,
      variables () {
        return {
          name: this.filters.sampleId,
          sampleTypeName: this.filters.sampleType,
          desc: this.filters.sampleNote,
          owner: this.filters.sampleOwner,
          inWorkflowInstance: JSON.parse(this.filters.inWorkflowInstance),
          page: this.page,
          pageSize: PAGE_SIZE
        }
      }
    }
  },
```

I'd expect when apollo issues this query, for ROOT_QUERY.samplePage.0 to exist in dev tools, but it does not.

**Comment by mekhami** [comment]
When I `console.log(this.$apollo)` inside a mutation elsewhere, I see my `queries.sampleTypes`, but not my `queries.samplePage` (despite both of these queries being issues, and appearing in Apollo Dev Tools "Watched Queries"

**Comment by mekhami** [comment]
@stique I feel like an idiot, but my problem was that I had a reactive 'page' variable in my query. So in my 'showMore' function, Of course I'm going to get page 1 and page 1, because I made 'page' reactive.

Does changing it to a constant solve your problem? I set `page: 0` in my code and the problem was solved.
