### ISSUE TITLE
Memory leak with Nuxt SSR

### ISSUE THREAD

**Issue by kieusonlam** [Akryum/vue-apollo#806]
We have simple `@nuxt/apollo` module intergrate `vue-apollo` into `nuxt`, using `vue-cli-plugin-apollo`.

The memory is growing up with every request to the server and didn't going down. I don't have experience about garbage collecting or memory debugging. Can you guys give me a help?

Related issue with reproduction example: https://github.com/nuxt-community/apollo-module/issues/231

**Comment by Akryum** [comment]
Fixed in https://github.com/Akryum/vue-apollo/commit/c3b840c368d50cb21f7410119a50443596baa537
