### ISSUE TITLE
Question: can I add this feature

### ISSUE THREAD

**Issue by georgyfarniev** [Akryum/vue-apollo#809]
Hello. @Akryum, I apologize if it's not correct place for questions, but I wasn't able to get answer in discord chat and unable to find you there.

I want to add option for writing graphql queries in Vue SFC block, using reworked version of existing loader:  https://github.com/zephraph/vue-graphql-loader

Everything I want to do is just to add automatic configuration of this loader to vue-cli-plugin-apollo, and update vue-apollo documentation to mention this. But before I start working on this, I would like to know your feedback. 

I think it would be nice to have this option, because it's standard approach for vue to structure application. It really worth to be a part of vue-apollo.

So, can I try to create PR for this?

**Comment by Akryum** [comment]
I guess this should go to the vue-cli-plugin-apollo repository then :smile_cat:

**Comment by georgyfarniev** [comment]
@Akryum apology, fixed it: https://github.com/Akryum/vue-cli-plugin-apollo/issues/221
