### ISSUE TITLE
Multiple mutations

### ISSUE THREAD

**Issue by felisio** [Akryum/vue-apollo#81]
Hi, How i use multiple mutations in vue-apollo?
ex: http://dev.apollodata.com/react/mutations.html#basics

**Comment by Samuell1** [comment]
You mean something like this ?

```js
someFunction () {
  this.$apollo.mutate({ ... }).then((responseFirst) => {
    console.log(responseFirst)
    this.$apollo.mutate({ ... }).then((responseSecond) => {
      console.log(responseSecond)
    })
  })
  
}
```

```js
async someFunction () {
  const firstMutation = await this.$apollo.mutate({ ... })
  const secondMutation = await this.$apollo.mutate({ ... })
}
```

**Comment by Rebolon** [comment]
@Samuell1 this means that it will do 2 HTTP Call whereas the node server could accept only one and manage the 2 mutations inside ?

**Comment by Samuell1** [comment]
@Rebolon it will do 2 calls but not in same time only after first is success

**Comment by Akryum** [comment]
Mutations in one graphql document are executed sequentially.
