### ISSUE TITLE
Subscrption ws connection error - failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by MeStrak** [Akryum/vue-apollo#824]
Hi, I'm running nest.js with GraphQL and vue-apollo on the front end.

I've created a subscription type in my schema to notify me of new items. From GraphQL playground (http://localhost:3000/graphql) it's working ok - when I load the subscription, a new item is sent everytime it's created.

When I try to connect from vue-apollo I get this error:

> client.js?633a:111 WebSocket connection to 'ws://localhost:3000/graphql' failed: WebSocket is closed before the connection is established.

several times, then finally:

> sockjs.js?9be2:2998 WebSocket connection to 'ws://localhost:8080/sockjs-node/925/qjrucnhu/websocket' failed: WebSocket is closed before the connection is established.

If I watch the console when I test the subscription in GraphQL playground I see the following network connection. I'm also able to create a connection to ws://localhost:3000/graphql with a websocket connection tester (Chrome extension).

> **General**
> _Request URL: ws://localhost:3000/graphql
> Request Method: GET
> Status Code: 101 Switching Protocols_
> 
> **Response headers**
> _Connection: Upgrade
> Sec-WebSocket-Accept: 1N58TpBf3DNKajLSExtZjcULt24=
> Sec-WebSocket-Protocol: graphql-ws
> Upgrade: websocket_
> 
> **Request headers**
> _Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.9
> Cache-Control: no-cache
> Connection: Upgrade
> Host: localhost:3000
> Origin: http://localhost:3000
> Pragma: no-cache
> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
> Sec-WebSocket-Key: faauEp+FY+4FDJulBsK/dA==
> Sec-WebSocket-Protocol: graphql-ws
> Sec-WebSocket-Version: 13
> Upgrade: websocket
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36_

I have the following main.ts in my Vue.js app. Can you see anything wrong?

```import App from "./App.vue";
import Vue from "vue";
import router from "./router";
import store from "./store";
import "./registerServiceWorker";

import vuetify from "./plugins/vuetify";

import VueApollo from 'vue-apollo'
import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
// New Imports
import { split } from 'apollo-link'
import { WebSocketLink } from 'apollo-link-ws'
import { getMainDefinition } from 'apollo-utilities'

// import { createProvider } from './vue-apollo.js';

// import ApolloClient from 'apollo-boost'

const httpLink = new HttpLink({
  // You should use an absolute URL here
  uri: 'http://localhost:3000/graphql',
});

// Create the subscription websocket link
const wsLink = new WebSocketLink({
  uri: 'ws://localhost:3000/graphql',
  options: {
    reconnect: true,
  },
});

// using the ability to split links, you can send data to each link
// depending on what kind of operation is being sent
const link = split(
  // split based on operation type
  ({ query }) => {
    const definition = getMainDefinition(query)
    return definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
  },
  wsLink,
  httpLink,
);

// Create the apollo client
const apolloClient = new ApolloClient({
  link,
  cache: new InMemoryCache(),
  connectToDevTools: true,
})

// Install the vue plugin like before
Vue.use(VueApollo)

const apolloProvider = new VueApollo({
  defaultClient: apolloClient,
})

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  vuetify,
  apolloProvider,
  render: h => h(App)
}).$mount("#app");```

**Comment by Akryum** [comment]
Please provide a minimal runnable reproduction so I can diagnose the issue.

**Comment by MeStrak** [comment]
@Akryum actually when I retested this again today it was working fine with no changes. I guess maybe the issue was something related to my PC network settings rather than the ws implementation but I have no idea what that could be.

Anyway, closing this issue.

Thanks
