### ISSUE TITLE
Simple & fast way of querying data

### ISSUE THREAD

**Issue by dimitri-koenig** [Akryum/vue-apollo#83]
Hi there

It would be awesome if one could have a quick & brief way of querying simple stuff.

Current solution:
```javascript
<script>
import gql from 'graphql-tag'

const allProjectsQuery = gql(`
  query allProjectsQuery {
    projects: allProjects {
      id
      title
    }
  }
`)

export default {
  data () {
    return {
      projects: [],
    }
  },

  apollo: {
    projects: allProjectsQuery,
  },
}
</script>
```

Proposed solution:
```javascript
<script>
export default {
  apollo: {
    projects: `
      query allProjectsQuery {
        projects: allProjects {
          id
          title
        }
      }
    `,
  },
}
</script>
```

* No import of gql
* No additional assignment for data object (one could be using $set
* Code is much cleaner and less overloaded

What do you think?

Best
Dimitri

**Comment by stubailo** [comment]
FYI - the `gql` thing is so that you can use tools like https://github.com/apollographql/eslint-plugin-graphql

Otherwise, it's very hard to use any tools that expect to be able to identify GraphQL queries in your code. Same goes for Prettier, for example.

**Comment by Akryum** [comment]
I think we won't support this for now.
