### ISSUE TITLE
Could not refetch

### ISSUE THREAD

**Issue by alperklc** [Akryum/vue-apollo#85]
Hi,

I would like to make a infinite scrolling list of items with a search bar on the top. I'm making experiments in order to achieve this. I have a query with a variable:

```
query searchByCategoryName($keyword: String!){
  records: allRecords(orderBy: date_DESC first: 20  filter:{category: {name_contains: $keyword}}) {
    id
    date
    category {
      icon
      name
    }
    vendor {name}
    price
    currency
  }
}`;
```

Already defined the a field under data for storing search keyword:
```
  data: () => ({
    records: [],
    searchKeyword: '',
  }),
```

Which is set as model on an input:
```<input v-model="searchKeyword" placeholder="u" />```

And the keyword is defined under apollo as well:
```
  apollo: {
    records: {
      query,
      loadingKey: 'loading',
      variables: () => ({
        keyword: this.searchKeyword || '',
      }),
    },
  },
```

I defined a function for re-fetching which is called by a button for now, will add debounce for input field. The function is making this call:

``` this.$apollo.queries.records.refetch(); ```

When I click on the button for making a re-fetch, I'm receiving the this error on the console:
> ListView.vue?40e1:61 Uncaught TypeError: Cannot read property 'queries' of undefined
>     at VueComponent.updateSearch (ListView.vue?40e1:61)
>     at boundFn (vue.esm.js?65d7:178)
>     at HTMLButtonElement.invoker (vue.esm.js?65d7:1795)

I have following dependencies on my package.json:

    "apollo-client": "^1.9.0-0",
    "graphql-tag": "^2.4.2",
    "vue": "^2.3.3",
    "vue-apollo": "^2.1.0-beta.18",
    "vue-infinite-loading": "^2.1.3",
    "vue-router": "^2.3.1"

Anyone experienced this error? 
Thanks!

Alper

**Comment by Akryum** [comment]
Did you install the plugin with `Vue.use(VueApollo)`?

**Comment by alperklc** [comment]
yes, installed in main.js:

`Vue.use(VueApollo);`

**Comment by alperklc** [comment]
It was about arrow function in object literal. Changed variables to this and it worked:
```
      variables: function variables() {
        return {
          keyword: this.searchKeyword || '',
        };
      },
```

**Comment by Akryum** [comment]
Okay, I didn't spot it! :smile:
You can also write this:

```javascript
      variables () {
        return {
          keyword: this.searchKeyword || '',
        };
      },
```
