### ISSUE TITLE
Error handler not firing. Not sure if bug or not.

### ISSUE THREAD

**Issue by michaelpumo** [Akryum/vue-apollo#86]
I have the following in my Vue.js component:

```
  methods: {
    signin () {
      const email = this.email
      const password = this.password

      this.$apollo.mutate({
        mutation: signinMutation,
        variables: {
          email,
          password
        },
        error (error) {
          console.error('This never fires...', error)
        }
      })
      .then((data) => {
        // This never fires on an error, so I can't
        // show the user the errors in the network repsonse.
        console.log(data)
      })
      .catch((error) => {
        // Error in this part fires in the console
        // but I'm unable to show the JSON response
        // errors because the 'then' above doesn't execute.
        console.error(error)
      })
    }
  }
```

Then I get an error in the console:

> Error: GraphQL error: No user found with that information at new ApolloError (eval at (app.js:956), :34:28) at eval (eval at (app.js:1353), :139:33)

I'm trying to show errors to the user, but the error() method doesn't seem to do anything.

In the network response, I see some custom error messages I want to display to the user, but I'm unable to access them in any error handler. I'm really a bit lost on how to do this.

I have a StackOverflow question in more depth here:
https://stackoverflow.com/questions/45199311/show-apollo-mutation-error-to-user-in-vue-js

I'm not sure if this is a bug or if I've done something wrong. I'm looking to here for an example:
https://github.com/Akryum/vue-apollo#mutations

Thanks

**Comment by Samuell1** [comment]
I think error function doesnt exists in mutation only catch

you can catch that message like: `error.graphQLErrors[0].message`
