### ISSUE TITLE
Optimistic response for parent data from mutation in child component?

### ISSUE THREAD

**Issue by ojczeo** [Akryum/vue-apollo#89]
Many times when I'm passing part of parent data (fetched using `Apollo`) to a child component as a prop, I wish I could make an optimistic response update to parent data. 
Is it possible currently? How could I achieve this?  🤔  Many times when I'm operating on collection I do not want to bind mutations with parent component, cause it making it too big and unclear, but when I'm binding to child components I can't update parent data with optimistic response.
And also when I'm making delete mutation which remove one element of collection I wish I could call optimistic remove for this element from child component, but I can't. 🤕 
Is it possible to achieve? If not how could I upgrade my implementation? 🆘 
Thanks for help!

**Comment by Akryum** [comment]
You can modify the cached data with the [Direct Cache Access API](http://dev.apollodata.com/core/read-and-write.html), which will update the queries associated with this data.

**Comment by ojczeo** [comment]
@Akryum I've tried your solution, store cache's updating, but data binded to parent component not refreshing. How should I set query for this component?

**Comment by Akryum** [comment]
You may also check [this doc](http://dev.apollodata.com/react/cache-updates.html) about updating the store.

**Comment by yazer79** [comment]
Please update the links, they are not valid anymore
