### ISSUE TITLE
Problem with passing parameters

### ISSUE THREAD

**Issue by Reached** [Akryum/vue-apollo#90]
Hi there,

Great package! I have an issue with my parameters not being passed to my query, what am I doing wrong here?

If i pass the id directly into the query it works.

I use Graph.cool as my backend if that has anything to say on the query side.

```
apollo: {
            Post: {
                query: gql`query {
                  Post(id: $id) {
                    id
                    imageUrl
                    description
                  },
              }`,
              variables: {
                  id: 'cj5ee2kinck8x01119naqouv3'
                  
              },
            }
        }
```

**Comment by Akryum** [comment]
Your GraphQL query should include parameters. For example:

```graphql
query myQuery ($id: ID!) {
  Post (id: $id) {
    id
    imageUrl
    description
  }
}
```

**Comment by Reached** [comment]
Hi @Akryum ,
I haven't tested this yet, will do soon! Thanks for getting back to me :)
