### ISSUE TITLE
How to define GraphQL input type.

### ISSUE THREAD

**Issue by thes01** [Akryum/vue-apollo#91]
I can't figure out, where to load custom input type, i.e.
`input SongPart{
    id: Int!
    lyrics: String
}` so that i could use it in a mutation. 

Please see:
https://stackoverflow.com/questions/45332321/how-to-define-graphql-input-type-in-vue-apollo-client

**Comment by kevinrfx8** [comment]
Hi. if I'm not wrong in front end you should do something like

```javascript
const MUTATION = Apollo.gql`
	mutation($user: customInputTypeName){
  	createUser(user:$user){
    	id
    }
  }
`
```

and then 
```javascript
     mutation:MUTATION,
      variables:{
      	user:{ name:"name", role:ADMIN"}
      }
```
Hope it helps you.

**Comment by thes01** [comment]
Actually the problem is solved - I just needed to define in backend, not in frontend. I got little confused as I use laravel-graphql (php) implementation.
