### ISSUE TITLE
__typename Conflicts

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Akryum/vue-apollo#92]
### What is happening
![image](https://user-images.githubusercontent.com/25447231/28745377-b0501722-74a9-11e7-9dd3-a5195ed39fe0.png)

### What is expected
![image](https://user-images.githubusercontent.com/25447231/28745381-ba9773f6-74a9-11e7-9954-039c153eca28.png)

Any ideas?

**Comment by Akryum** [comment]
What is the query that you use in your component? Maybe you could try it in
graphiql with the exact same parameters, preferably on the exact same
graphql server. On the screenshots, it seems the queries you are comparing
are different.

**Comment by ralphchristianeclipse** [comment]
@Akryum what im pointing out is the type name 

it works when i change one field to another name and the typename will be correct

**Comment by ralphchristianeclipse** [comment]
Like this one #31

**Comment by JanMP** [comment]
I also got query results polluted with __typename entries that I never requested in any of my queries.

**Comment by Akryum** [comment]
> I also got query results polluted with __typename entries that I never requested in any of my queries.

Those are necessary for apollo to work and should be automatically added in all of you queries.

**Comment by Akryum** [comment]
We may need a full repro to be able to find where the issue is coming from. Make sure all the data returned by your graphql server contains a `__typename` field.
