### ISSUE TITLE
SSR Vue Template renders before all results are returned

### ISSUE THREAD

**Issue by sgtfrankieboy** [Akryum/vue-apollo#94]
When using SSR with an expensive GraphQL query the template is rendered before its content is handled by Apollo.

I use the following code on the server to handle the prefetch:
```JavaScript
Promise.all([
  ...matchedComponents.map(component => {
    return component.preFetch && component.preFetch(store)
  }),
  apolloProvider.prefetchAll({
    route: router.currentRoute
  }, matchedComponents)
]).then(() => {
  isDev && console.log(`data pre-fetch: ${Date.now() - s}ms`)
  // Inject the Vuex state and the Apollo cache on the page.
  // This will prevent unecessary queries.

  context.apolloState = apolloProvider.exportStates()
  context.state = store.state
  resolve(app)
}).catch(reject)
```

The VueJS component I'm trying to render using SSR has 3 GraphQL queries. I've added logs to each one of them, and the computed properties that make use of them to see what gets called first.

```
data pre-fetch: 434ms
result: Query A
result: Query B
compute: Uses Query A
compute: Uses Query C
result: Query C
```

The compute that uses `Query A` works and properly returns its data. However the one that uses `Query C` returns nothing.

Now, when I change the order of the queries in the `apollo` property in my vue component. (Moved `C`, to be first)  I get the following:

```
data pre-fetch: 179ms
compute: Uses Query A
result: Query A
result: Query B
compute: Uses Query C
result: Query C
```

Now neither of the computed properties are returning a result.

What I think is happening is that the prefetch promises are returned before the vue component's data property is populated. Causing it to be empty when the Vue renderer is started (which happens because all promises are done). 

The `window.__APOLLO_STATE__` variable does contain the results of all queries though.

**Comment by Akryum** [comment]
Do you have a repro to share?

**Comment by sgtfrankieboy** [comment]
I can't really easily make a repro, sorry.

I did discover that it only happens when the query uses variables. If I remove those it works fine. But the weird thing about that is I have other components that use variables without any issues.

**Comment by Akryum** [comment]
Do you have some not-working code to show?

**Comment by sgtfrankieboy** [comment]
Here is the relevant VueJS components javascript: https://gist.github.com/sgtfrankieboy/9831f4a568f9342e0a7af34db6fd75ed

The first query under apollo is the one causing problems. If I move it down the other two queries properly set the data, if I remove the variables all three queries run without issue.

**Comment by Akryum** [comment]
Is this component in the `matchedComponents` of the router? If not, you have to wrap it in the `willPrefetch` method ([doc](https://github.com/Akryum/vue-apollo#prefetch-components)).

**Comment by sgtfrankieboy** [comment]
It is in the `matchedComponents` of the router. Also tried wrapping it in `willPrefetch` but that doesn't work either. 

the prefetch just returns before the 3 graphql calls are done.

**Comment by sgtfrankieboy** [comment]
I figured out what was causing the issue. the results from the `variables` and `prefetch` methods did not correspond which was causing issues. Making sure they are the same fixed it.

Might be an idea to add this to the documentation?

**Comment by Akryum** [comment]
Sure! Maybe you can do a PR :smile:
