### ISSUE TITLE
Support for refetchQueries and updateQueries on $apollo.mutate

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Akryum/vue-apollo#99]
this would be handy or if this is already mapped to the apollo client maybe add it to the readme on how to use it :)

**Comment by SebT** [comment]
Both are already mapped. But yes, adding it to the README would be nice. `updateQuery` is mentioned but not `refetchQueries`.

**Comment by Samuell1** [comment]
`updateQuery` will be deprecated and replaced by `update`

**Comment by Akryum** [comment]
You should use `update` as shown in the [doc](https://github.com/Akryum/vue-apollo#mutations).

**Comment by dohomi** [comment]
@Akryum is there a specific reason why vue-apollo does not forward the option updateQueries of apollo? Just asking because I made use of this in one of the previous versions of vue-apollo and it was very handy in specific cases.

**Comment by Akryum** [comment]
@dohomi I should, since it just passes all the options you set to the apollo mutate method.

**Comment by dohomi** [comment]
Ok but then I'm afraid something does not work. I use updateQueries in one of my $apollo.mutate() calls and the query is not updating. Currently I use a dispatch in my component and call querieries.queryName.refetch() which works alright, but its a little bit more code writing

**Comment by Hernanm0g** [comment]
Ive been dealing with the same problem with refetchqueries and non of the solutions worked for me, so i finally ended up triggering a refresh() in the update function, as Akryum suggested, like this:

```javascript
this.$apollo.mutate({
         mutation: <Your mutation object>,
         variables:item,
         update: () => {
            this.$apollo.queries.cashouts.refresh() // Remember to refresh your query in the update function
         },
       })
```

Thanks @Akryum.

Hope it helps!
